Repository cylc/cylc-flow, pull requests merged in 2018-05, with the labels that each got.

#2646 Fix graph_parser validation for incorrect syntax order in a node
  lib/cylc/graph_parser.py
Labels: bug

#2593 Improve task polling and timeout handling
  doc/src/cylc-user-guide/suiterc.tex
  lib/cylc/suite_db_mgr.py
  lib/cylc/task_action_timer.py
  lib/cylc/task_events_mgr.py
  lib/cylc/task_job_mgr.py
  lib/cylc/task_pool.py
  lib/cylc/task_proxy.py
  tests/broadcast/07-float-setting.t
  tests/cylc-poll/13-comm-method.t
  tests/cylc-poll/14-intervals.t
  tests/cylc-poll/16-execution-time-limit.t
  tests/cylc-poll/16-execution-time-limit/reference.log
  tests/cylc-poll/16-execution-time-limit/suite.rc
  tests/events/task/bin/log-check.sh
  tests/events/task/events.log
  tests/jobscript/05-global-config.t
Labels: bug

#2649 Make T-submit respect suite UTC mode.
  bin/cylc-jobs-submit
  lib/cylc/batch_sys_manager.py
  lib/cylc/task_events_mgr.py
  lib/cylc/task_job_mgr.py
  tests/job-submission/07-multi.t
Labels: bug

#2648 cylc version now handled by bin/cylc
  bin/cylc
  bin/cylc-help
  bin/cylc-version
Labels: small

#2653 cylc help fixes
  bin/cylc
  bin/cylc-help
  bin/cylc-warranty
  tests/cli/00-cycle-points.t
  tests/cli/00-cycle-points/suite.rc
  tests/cli/01-help.t
  tests/cli/test_header
Labels: bug, small

#2638 Fix stop kill multi notifications
  lib/cylc/scheduler.py
  lib/cylc/task_events_mgr.py
  lib/cylc/task_job_mgr.py
  lib/cylc/task_state.py
Labels: bug

#2657 remove duplicate parsers
  lib/cylc/cycling/iso8601.py
Labels: efficiency

#2662 cat-log: fix is_remote arguments
  bin/cylc-cat-log
Labels: bug

#2666 scan/gscan: consistent default behaviour
  CHANGES.md
  bin/cylc-scan
  lib/cylc/daemonize.py
  lib/cylc/gui/gscan.py
  lib/cylc/network/port_scan.py
Labels: bug

#2667 cat-log --host=HOST tail mode now tidies up
  bin/cylc-cat-log
Labels: bug

#2670 scan HOST: default to suites of current user
  bin/cylc-scan
Labels: bug

#2675 trap error after cylc message success
  lib/cylc/job.sh
Labels: bug?

#2674 Cat log remote tidy fix.
  CHANGES.md
  bin/cylc-cat-log
  lib/cylc/remote.py
  tests/cylc-cat-log/05-remote-tail.t
Labels: bug

#2678 Fix restart task action timers load old poll timer
  lib/cylc/task_pool.py
Labels: bug

#2680 check-software: revise TeX module search function
  bin/cylc-check-software
Labels: bug

#2683 check-software: fix undefined variable traceback
  bin/cylc-check-software
Labels: bug
