Repository cylc/cylc-flow, pull requests merged in 2019-07, with the labels that each got.

#3184 Correctly store stop_point, etc for restart
  CHANGES.md
  bin/cylc-check-versions
  bin/cylc-diff
  bin/cylc-get-suite-config
  bin/cylc-graph
  bin/cylc-list
  bin/cylc-submit
  bin/cylc-validate
  cylc/flow/config.py
  cylc/flow/option_parsers.py
  cylc/flow/scheduler.py
  cylc/flow/scheduler_cli.py
  cylc/flow/state_summary_mgr.py
  cylc/flow/suite_db_mgr.py
  cylc/flow/task_pool.py
  cylc/flow/tests/test_scheduler.py
  cylc/flow/ws_data_mgr.py
  cylc/flow/xtrigger_mgr.py
  tests/authentication/05-full-control.t
  tests/authentication/basic/suite.rc
  tests/cli/02-now.t
  tests/cylc-take-checkpoints/00-basic.t
  tests/database/00-simple/select-suite-params.out
  tests/execution-time-limit/04-poll/suite.rc
  tests/hold-release/15-hold-after.t
  tests/hold-release/hold-after/suite.rc
  tests/pre-initial/12-warm-restart.t
  tests/restart/19-checkpoint.t
  tests/restart/36-auto-restart-incompatible.t
  tests/restart/44-stop-point.t
  tests/restart/45-stop-task.t
  tests/restart/46-stop-clock-time.t
  tests/restart/47-no-auto-stop.t
  tests/restart/48-enable-auto-stop.t
  tests/restart/49-enable-auto-stop-2.t
  tests/restart/50-ignore-stop-point.t
  tests/restart/51-ignore-final-point.t
Labels: bug

#3205 Fix version file creation for new repo name.
  CHANGES.md
  etc/dev-bin/create-version-file
Labels: bug

#3204 [7.8.x] fix `cylc run --icp=now SUITE` restart
  CHANGES.md
  lib/cylc/config.py
  tests/cli/02-now.t
Labels: bug

#3215 Use contextlib for suppressing IOError and closing socket
  cylc/flow/hostuserutil.py
Labels: small

#3214 Fix duplicate test name test_strip_and_unquote_list
  cylc/flow/tests/parsec/test_validate.py
Labels: small

#3211 Compare with not instead of using empty list
  cylc/flow/network/schema.py
Labels: small

#3213 Update docstrings
  cylc/flow/network/server.py
Labels: doc, small

#3217 Fix schema error & in turn per-suite UI data provision
  cylc/flow/network/schema.py
Labels: bug

#3228 Remove possibility for very slow cylc print
  bin/cylc-print
  cylc/flow/network/scan.py
  cylc/flow/suite_srv_files_mgr.py
Labels: bug?, efficiency

#3239 Remove acknowledgement file
  ACKNOWLEDGEMENT.md
Labels: small

#3241 Remove unused imports
  bin/cylc-client
  bin/cylc-ls-checkpoints
  bin/cylc-report-timings
Labels: small

#3238 Comment comments in issue and PR templates?
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: small

#3243 Use correct variable to avoid traceback
  bin/cylc-check-versions
Labels: small

#3246 Remove one more mention/link of ACKNOWLEDGEMENT.md
  README.md
Labels: small

#3247 Add unit tests for cylc.flow.network.scan
  cylc/flow/tests/network/test_scan.py
Labels: small

#3251 extract-pkg-resources: update docstring w/ rename
  bin/cylc-extract-pkg-resources
Labels: doc, small

#3254 separate authentication and authorisation code
  cylc/flow/cfgspec/globalcfg.py
  cylc/flow/cfgspec/suite.py
  cylc/flow/network/__init__.py
  cylc/flow/network/authentication.py
  cylc/flow/network/authorisation.py
  cylc/flow/network/client.py
  cylc/flow/network/server.py
  cylc/flow/tests/test_zmq.py
Labels: efficiency
