Repository cylc/cylc-flow, pull requests merged in 2019-09, with the labels that each got.

#3342 Removed obsolete command categories.
  bin/cylc
Labels: bug

#3344 Remove zmq message logging
  cylc/flow/network/server.py
Labels: small

#3353 Fix exception when set-severity receives invalid logging level
  bin/cylc-set-verbosity
  tests/cli/03-set-verbosity.t
Labels: bug

#3366 updated cylc-deprecate tests
  tests/deprecations/00-pre-cylc8.t
  tests/deprecations/00-pre-cylc8/suite.rc
  tests/deprecations/01-cylc8-basic.t
  tests/deprecations/01-cylc8-basic/suite.rc
Labels: small

#3363 Remove duplicate and unnecessary tail_tmpl variable in cylc-cat-log
  bin/cylc-cat-log
Labels: small

#3370 Allow camel or snake sort key
  cylc/flow/network/resolvers.py
  cylc/flow/network/schema.py
Labels: small

#3371 fix-version-no-in-__init__
  cylc/flow/__init__.py
Labels: bug

#3374 parsec: improve file parse error messages
  cylc/flow/parsec/config.py
  cylc/flow/parsec/exceptions.py
  cylc/flow/parsec/fileparse.py
  cylc/flow/parsec/include.py
  cylc/flow/tests/parsec/test_fileparse.py
  cylc/flow/tests/parsec/test_include.py
  cylc/flow/tests/parsec/test_parsec.py
  tests/validate/61-include-missing-quote.t
Labels: small

#3386 Re-phrase README summary statement
  README.md
Labels: doc, small

#3375 Fix global config for functional tests
  bin/cylc-get-site-config
  cylc/flow/etc/conda-environment.yaml
  cylc/flow/etc/flow-tests.rc.eg
  cylc/flow/etc/flow.rc.eg
  cylc/flow/resources.py
  etc/bin/run-functional-tests.sh
  tests/cylc-get-site-config/01-defaults.t
  tests/lib/bash/test_header
Labels: bug
