Repository cylc/cylc-flow, pull requests merged in 2019-06, with the labels that each got.

#3147 7.8.x Correctly store stop_point for restart
  CHANGES.md
  bin/cylc-check-versions
  bin/cylc-diff
  bin/cylc-get-suite-config
  bin/cylc-list
  bin/cylc-submit
  bin/cylc-validate
  doc/src/running-suites.rst
  lib/cylc/config.py
  lib/cylc/cylc_xdot.py
  lib/cylc/log_diagnosis.py
  lib/cylc/option_parsers.py
  lib/cylc/rundb.py
  lib/cylc/scheduler.py
  lib/cylc/scheduler_cli.py
  lib/cylc/state_summary_mgr.py
  lib/cylc/suite_db_mgr.py
  lib/cylc/task_pool.py
  lib/cylc/tests/test_scheduler.py
  lib/cylc/xtrigger_mgr.py
  tests/cylc-take-checkpoints/00-basic.t
  tests/database/00-simple/select-suite-params.out
  tests/pre-initial/12-warm-restart.t
  tests/restart/15-state-to-db.t
  tests/restart/15-state-to-db/state/state
  tests/restart/19-checkpoint.t
  tests/restart/24-upgrade-db-611/cylc-suite-db.dump
  tests/restart/29-no-upgrade-db-611/cylc-suite-db.dump
  tests/restart/31-upgrade-db-7-6-0/cylc-suite-db.dump
  tests/restart/31-upgrade-db-7-6-0/db.dump
  tests/restart/36-auto-restart-incompatible.t
  tests/restart/44-stop-point.t
  tests/restart/45-stop-task.t
  tests/restart/46-stop-clock-time.t
  tests/restart/47-no-auto-stop.t
  tests/restart/48-enable-auto-stop.t
  tests/restart/49-enable-auto-stop-2.t
  tests/restart/50-ignore-stop-point.t
  tests/restart/51-ignore-final-point.t
Labels: bug

#3186 cylc.gcapture: don't split command
  CHANGES.md
  lib/cylc/gui/gcapture.py
Labels: bug

#3190 Fix PR markdown links of 7.8.3 changelog entry
  CHANGES.md
Labels: small

#3072 Xtrigger minor improvements
  cylc/flow/scheduler.py
  cylc/flow/task_pool.py
  cylc/flow/tests/test_xtrigger_mgr.py
  cylc/flow/xtrigger_mgr.py
Labels: small

#3171 Simplify if expression in prerequisite.py
  cylc/flow/prerequisite.py
Labels: small

#3003 Fix inheritance with quotes using shlex
  cylc/flow/parsec/validate.py
  cylc/flow/tests/parsec/test_validate.py
  cylc/flow/tests/test_config.py
Labels: bug, small

#3193 run/restart: re-add cut off user notice line
  cylc/flow/scheduler.py
Labels: bug

#3197 Fix minor bug in cat-log command.
  bin/cylc-cat-log
  tests/cylc-cat-log/00-local.t
  tests/cylc-cat-log/00-local/suite.rc
  tests/cylc-cat-log/03-bad-suite.t
Labels: bug
