Repository cylc/cylc-flow, pull requests merged in 2019-01, with the labels that each got.

#2895 Fix issues on deployment of 7.8.0
  bin/cylc-jobscript
  bin/cylc-test-battery
  lib/cylc/cfgspec/globalcfg.py
  lib/cylc/hostuserutil.py
  lib/cylc/tests/test_hostuserutil.py
  lib/isodatetime/run_tests
  tests/api-suite-info/05-get-latest-state-1.t
  tests/cylc-get-config/00-simple.t
  tests/cylc-get-site-config/04-homeless.t
  tests/cylc-poll/16-execution-time-limit.t
  tests/cylc-review/00-basic.t
  tests/cylc-review/01-title.t
  tests/cylc-review/02-no-job-out.t
  tests/cylc-review/03-no-statuses.t
  tests/cylc-review/04-time-sort.t
  tests/cylc-review/05-cycles-job-fails.t
  tests/cylc-review/06-host-port.t
  tests/cylc-review/07-cycles-page.t
  tests/cylc-review/08-suites-page.t
  tests/cylc-review/09-jobs-fuzzy-time.t
  tests/cylc-review/10-jobs-task-status.t
  tests/cylc-review/11-view-unicode.t
  tests/cylc-review/12-cycle-counts.t
  tests/cylc-review/13-jobs-path-in-tar.t
  tests/cylc.host_appointer/00-host-appointer.t
  tests/events/47-long-output.t
  tests/lib/bash/test_header
  tests/profile-battery/00-compatability.t
  tests/restart/21-task-elapsed.t
  tests/restart/37-auto-restart-delay.t
  tests/suite-host-self-id/00-address.t
  tests/validate/04-builtin-suites.t
Labels: bug

#2918 Move images to a package, and load with pkg_resources
  lib/cylc/cylc_xdot.py
  lib/cylc/gui/images/icon.png
  lib/cylc/gui/images/icon.svg
  lib/cylc/gui/images/icons/group.png
  lib/cylc/gui/images/icons/tab-dot.png
  lib/cylc/gui/images/icons/tab-graph.png
  lib/cylc/gui/images/icons/tab-tree.png
  lib/cylc/gui/images/icons/transpose.png
  lib/cylc/gui/images/icons/ungroup.png
  lib/cylc/gui/images/logo.png
  lib/cylc/gui/util.py
Labels: small

#2913 parsec library: refresh (standardise) 4/5 year old info files
  lib/parsec/README
  lib/parsec/README.md
  lib/parsec/ToDo.txt
Labels: small

#2906 register: fix run directory == source directory
  lib/cylc/suite_srv_files_mgr.py
  lib/cylc/tests/test_suite_srv_files_mgr.py
  tests/registration/00-simple.t
Labels: bug

#2919 loggingutil: fix infinite loop on IOError
  lib/cylc/loggingutil.py
  lib/cylc/scheduler.py
  lib/cylc/tests/test_loggingutil.py
  lib/cylc/tests/test_scheduler.py
Labels: bug

#2922 Typos in documentation
  doc/src/cylc-user-guide/README
  doc/src/cylc-user-guide/cug.tex
  doc/src/cylc-user-guide/job-host-2.tex
  doc/src/cylc-user-guide/siterc.tex
  doc/src/cylc-user-guide/suiterc.tex
  doc/src/suite-design-guide/portable-suites.tex
Labels: doc, small

#2924 Fix cylc review documentation.
  doc/src/cylc-user-guide/cug.tex
Labels: bug, doc

#2926 Replace flaky tests/events/02-multi.t
  tests/events/02-multi.t
  tests/events/02-multi/bin/remove-bar.sh
  tests/events/02-multi/bin/trigger-bar.sh
  tests/events/02-multi/reference.log
  tests/events/02-multi/suite.rc
Labels: small

#2932 Fix subprocpool pipe polling
  lib/cylc/option_parsers.py
  lib/cylc/subprocpool.py
  lib/cylc/task_job_mgr.py
  tests/job-submission/19-chatty.t
  tests/job-submission/19-chatty/bin/talkingnonsense
  tests/job-submission/19-chatty/suite.rc
Labels: bug
