Repository cylc/cylc-flow, pull requests merged in 2019-08, with the labels that each got.

#3263 rename pkg_resources module to avoid namespace conflict
  bin/cylc-extract-resources
  bin/cylc-help
  cylc/flow/resources.py
  cylc/flow/suite_srv_files_mgr.py
  cylc/flow/task_remote_cmd.py
  cylc/flow/tests/test_resources.py
  cylc/flow/tests/test_suite_srv_files_mgr.py
Labels: bug

#3257 Avoid %% escape in xtrigger func args (7.8.x).
  CHANGES.md
  doc/src/external-triggers.rst
  lib/cylc/tests/test_xtrigger_mgr.py
  lib/cylc/xtrigger_mgr.py
Labels: bug

#3258 Avoid %% escape in xtrigger func args (master).
  CHANGES.md
  cylc/flow/tests/test_xtrigger_mgr.py
  cylc/flow/xtrigger_mgr.py
Labels: bug

#3259 Replace O(N) lookup with O(1) for task outputs (7.8.x)
  CHANGES.md
  etc/dev-suites/outputs/suite.rc
  etc/profile-experiments/outputs.json
  lib/cylc/config.py
  lib/cylc/taskdef.py
Labels: efficiency

#3269 Extract job.sh at suite start-up.
  cylc/flow/resources.py
  cylc/flow/scheduler_cli.py
  cylc/flow/suite_srv_files_mgr.py
  cylc/flow/tests/test_suite_srv_files_mgr.py
Labels: bug

#3276 Record all broadcast values in xtrigger return signature
  CHANGES.md
  cylc/flow/xtrigger_mgr.py
  flakytests/xtriggers/01-suite_state.t
Labels: bug

#3279 Turn colour off in jobscript generation command.
  bin/cylc-jobscript
Labels: bug

#3280 Record all broadcast values in xtrigger return [backport]
  CHANGES.md
  lib/cylc/xtrigger_mgr.py
  tests/xtriggers/01-suite_state.t
Labels: bug

#3290 Fix cmp_ok arg order in a test.
  tests/database/00-simple.t
Labels: bug

#3291 Fix use of poll in a test.
  tests/restart/25-hold-suite.t
Labels: bug

#3285 Xtrigger sequence fix
  CHANGES.md
  lib/cylc/config.py
  lib/cylc/task_pool.py
  lib/cylc/task_state.py
  lib/cylc/taskdef.py
  lib/cylc/tests/test_config.py
  lib/cylc/xtrigger_mgr.py
  tests/cylc-review/00-basic.t
  tests/cylc-review/01-title.t
  tests/database/00-simple.t
  tests/database/01-broadcast.t
  tests/database/02-retry.t
  tests/runahead/06-release-update.t
  tests/validate/69-bare-clock-xtrigger.t
  tests/validate/70-no-clock-int-cycle.t
  tests/xtriggers/03-sequence.t
Labels: bug

#3296 insert: globbing capability docstring correction (Cylc-8)
  bin/cylc-insert
  cylc/flow/option_parsers.py
Labels: bug, doc, small

#3295 insert: globbing capability docstring correction (Cylc-7)
  bin/cylc-insert
Labels: bug, doc, small

#3311 Remove obsolete command category "hook".
  bin/cylc
  bin/cylc-help
Labels: doc

#3317 Remove unused imports
  cylc/flow/scheduler.py
  cylc/flow/state_summary_mgr.py
  cylc/flow/tests/test_rundb.py
  cylc/flow/tests/test_task_state.py
Labels: small

#3318 Use different variable names in nested loops
  cylc/flow/rundb.py
Labels: small

#3323 docs: Python versions required for xtriggers (Cylc-7)
  doc/src/external-triggers.rst
Labels: doc

#3322 docs: format of xtrigger results dictionary (Cylc-7)
  doc/src/external-triggers.rst
Labels: doc

#3324 Fix a cylc ZMQ unit test.
  cylc/flow/tests/test_zmq.py
Labels: bug

#3326 Remove broken run dir housekeeping config
  doc/src/appendices/site-user-config-ref.rst
  lib/cylc/cfgspec/globalcfg.py
Labels: bug

#3287 xtrigger sequence fix - master
  CHANGES.md
  cylc/flow/config.py
  cylc/flow/scheduler.py
  cylc/flow/task_pool.py
  cylc/flow/task_state.py
  cylc/flow/taskdef.py
  cylc/flow/tests/test_config.py
  cylc/flow/tests/test_xtrigger_mgr.py
  cylc/flow/xtrigger_mgr.py
  tests/validate/69-bare-clock-xtrigger.t
  tests/validate/70-no-clock-int-cycle.t
  tests/xtriggers/03-sequence.t
Labels: bug
