Repository cylc/cylc-flow, pull requests merged in 2019-02, with the labels that each got.

#2937 Set location of coverage file in Travis
  .travis.yml
Labels: small

#2941 host appointer: improve handling of unexpected out
  lib/cylc/host_appointer.py
Labels: small

#2944 Give logger a null handler on start up
  bin/cylc-cycle-point
  bin/cylc-documentation
  bin/cylc-get-gui-config
  bin/cylc-get-site-config
  lib/cylc/option_parsers.py
  lib/parsec/__init__.py
Labels: bug

#2942 Fix broken links for cylc-7.8.1 change log entry
  CHANGES.md
Labels: small

#2939 Use higher contrast link colours.
  doc/src/conf.py
Labels: doc

#2954 docs: fix jinja2 variable setting example suites
  doc/src/suite-config.rst
  doc/src/tutorial.rst
  etc/examples/tutorial/oneoff/jinja2/suite.rc
Labels: doc

#2952 docs: amend makefile command; address warning
  Makefile
Labels: bug

#2951 docs: amend makefile command; address warning
  Makefile
  doc/src/appendices/site-user-config-ref.rst
Labels: bug

#2945 review: security patch to prevent code injection
  lib/cylc/cylc-review/template/cycles.html
  lib/cylc/cylc-review/template/job-entry.html
  lib/cylc/cylc-review/template/suites.html
  lib/cylc/cylc-review/template/taskjobs.html
  lib/cylc/cylc-review/template/view.html
  lib/cylc/review.py
Labels: bug
