Repository cylc/cylc-flow, pull requests merged in 2019-04, with the labels that each got.

#3035 Fix scheduler#shutdown when reference-log option is used
  lib/cylc/loggingutil.py
  lib/cylc/scheduler.py
  tests/shutdown/19-log-reference.t
Labels: bug, small

#3055 Simplify regexes
  bin/cylc-get-host-metrics
  bin/cylc-search
  lib/cylc/cfgvalidate.py
  lib/cylc/cycling/iso8601.py
  lib/cylc/graph_parser.py
  lib/cylc/param_expand.py
  lib/cylc/task_remote_mgr.py
  lib/cylc/time_parser.py
  lib/parsec/fileparse.py
  lib/parsec/include.py
  lib/parsec/validate.py
Labels: small

#3056 Fix suite freeze on non-existent xtrigger
  lib/cylc/config.py
  lib/cylc/scheduler.py
  lib/cylc/xtrigger_mgr.py
  tests/validate/04-builtin-suites.t
Labels: bug

#3060 Fix bug when an AttributeError is raised, and add unit tests for xtrigger
  .codacy.yml
  lib/cylc/config.py
  lib/cylc/tests/test_config.py
  lib/cylc/tests/test_subprocpool.py
Labels: bug?, small

#3059 Fix suite freeze on non-existent xtrigger - 7.8.x
  lib/cylc/config.py
  lib/cylc/scheduler.py
  lib/cylc/xtrigger_mgr.py
  tests/validate/04-builtin-suites.t
Labels: bug

#3070 Update docs for order of scripts sections
  doc/src/appendices/suiterc-config-ref.rst
Labels: doc

#3066 minor fix to docs about exit-script
  doc/src/appendices/suiterc-config-ref.rst
Labels: doc, small

#3021 Remove latex refs 7
  .travis/install.sh
  INSTALL.md
  bin/cylc-check-software
  doc/src/global-site-user-conf.rst
  doc/src/installation.rst
  etc/global.rc.eg
  usr/bin/cylc
Labels: small

#3015 zmq: use global client context
  lib/cylc/network/client.py
Labels: bug

#3061 Remove globalcfg add_bin_dir and use_ssh, codacy issue about unused code
  lib/cylc/cfgspec/globalcfg.py
Labels: small

#3084 Fix import issues in cylc get-directory
  bin/cylc-get-directory
Labels: small

#3090 Remove obsolete cat-state command.
  bin/cylc-cat-state
  bin/cylc-help
  etc/cylc-bash-completion
  lib/cylc/dump.py
  tests/cylc-cat-state/00-basic.t
  tests/cylc-cat-state/01-issue1358.t
  tests/cylc-cat-state/01-issue1358/suite.rc
  tests/cylc-cat-state/basic/reference.log
  tests/cylc-cat-state/basic/state-check.py
  tests/cylc-cat-state/basic/suite.rc
  tests/cylc-cat-state/test_header
Labels: small

#3086 Remove unused imports (mainly cylc.flags)
  bin/cylc-broadcast
  bin/cylc-checkpoint
  bin/cylc-diff
  bin/cylc-dump
  bin/cylc-edit
  bin/cylc-ext-trigger
  bin/cylc-get-suite-config
  bin/cylc-get-suite-version
  bin/cylc-graph
  bin/cylc-hold
  bin/cylc-insert
  bin/cylc-kill
  bin/cylc-list
  bin/cylc-nudge
  bin/cylc-poll
  bin/cylc-print
  bin/cylc-register
  bin/cylc-release
  bin/cylc-reload
  bin/cylc-remove
  bin/cylc-report-timings
  bin/cylc-reset
  bin/cylc-set-verbosity
  bin/cylc-show
  bin/cylc-spawn
  bin/cylc-stop
  bin/cylc-trigger
  bin/cylc-view
  bin/cylc-warranty
  lib/cylc/cfgspec/globalcfg.py
  lib/cylc/cycling/__init__.py
  lib/cylc/cycling/integer.py
  lib/cylc/cycling/iso8601.py
  lib/parsec/tests/test_include.py
Labels: small

#3091 Remove useless license commands.
  bin/cylc-conditions
  bin/cylc-help
  bin/cylc-warranty
  doc/src/tutorial.rst
  lib/cylc/scheduler.py
  tests/cli/01-help.t
Labels: small

#3085 Fix cylc-search for directories without suite.rc
  bin/cylc-search
Labels: bug, small

#3076 Remove globalcfg add_bin_dir and use_ssh, codacy issue about unused code
  lib/cylc/cfgspec/globalcfg.py
Labels: small

#3095 Run prove with --timer
  bin/cylc-test-battery
Labels: small

#3082 Docstrings and minor fixes server
  lib/cylc/network/server.py
Labels: small

#2938 review: fix waiting tasks
  lib/cylc/cylc-review/static/js/cylc-review.js
  lib/cylc/cylc-review/template/job-entry.html
  lib/cylc/cylc-review/template/pager.html
  lib/cylc/cylc-review/template/taskjobs.html
  lib/cylc/review.py
  lib/cylc/review_dao.py
  tests/cylc-review/00-basic.t
Labels: bug

#3100 Cylc kill fix
  lib/cylc/network/httpserver.py
  tests/job-kill/00-local.t
  tests/job-kill/00-local/reference.log
  tests/job-kill/00-local/suite.rc
Labels: bug

#3102 7.8.x: Travis CI build with Python 2.7
  .travis.yml
Labels: small

#3107 Anatomy of a job script.
  doc/src/graphics/png/orig/anatomy-of-a-job-script.png
  doc/src/task-implementation.rst
Labels: doc

#3108 Anatomy of a job script (Cylc-8)
  doc/src/graphics/png/orig/anatomy-of-a-job-script.png
  doc/src/task-implementation.rst
Labels: doc

#3104 Fix work loc assumption in a test.
  tests/cyclers/00-daily.t
Labels: bug

#3105 Fix work loc assumption in a test. (master version)
  tests/cyclers/00-daily.t
Labels: bug

#3053 Fix job kill hold-retry logic
  doc/src/running-suites.rst
  lib/cylc/scheduler.py
  lib/cylc/subprocctx.py
  lib/cylc/task_events_mgr.py
  lib/cylc/task_job_mgr.py
  lib/cylc/task_state.py
  lib/cylc/tests/test_task_state.py
  tests/cylc-cat-log/05-remote-tail.t
  tests/cylc-get-config/04-dummy-mode-output.t
  tests/cylc-message/02-multi.t
  tests/cylc-poll/15-job-st-file-no-batch.t
  tests/cylc-poll/16-execution-time-limit.t
  tests/cylc-poll/16-execution-time-limit/suite.rc
  tests/cylc-poll/17-pbs-cant-connect.t
  tests/cylc-show/03-clock-triggered-non-utc-mode.t
  tests/events/31-dont-stall-succeeded.t
  tests/restart/19-checkpoint/suite.rc
  tests/runahead/06-release-update.t
Labels: bug

#3110 patch metomi/isodatetime#127
  lib/isodatetime/data.py
  lib/isodatetime/parsers.py
  lib/isodatetime/tests/test_parser.py
Labels: non-cylc bug

#3124 Fix links in README and other files
  CHANGES.md
  INSTALL.md
  README.md
  bin/cylc-test-battery
  doc/src/suite-design-guide/sdg-introduction.rst
  lib/cylc/cfgspec/globalcfg.py
Labels: small

#3127 Fix text in changelog
  CHANGES.md
Labels: doc

#3129 Added SECURITY.md (master)
  SECURITY.md
Labels: security

#3128 Add SECURITY.md (7.8.x)
  CHANGES.md
  SECURITY.md
Labels: security

#3136 Add cylc-flow egg info to gitignore after module rename
  .gitignore
Labels: small
