Repository cylc/cylc-flow, pull requests merged in 2019-03, with the labels that each got.

#2988 Fix bad unary `+` syntax on a str
  lib/cylc/task_job_mgr.py
Labels: bug

#2986 Fix issue #2898: close app nicely on CTRL+C
  bin/cylc-gui
Labels: bug

#2981 Use calculated event_time instead of new current_time call
  lib/cylc/task_events_mgr.py
Labels: bug

#3008 Fix pycodestyle exclusion list (add from their default)
  tox.ini
Labels: small

#3010 task_job_mgr: except KeyError
  lib/cylc/task_job_mgr.py
Labels: bug?

#3009 task_job_mgr: except KeyError
  lib/cylc/task_job_mgr.py
Labels: bug?

#3013 Fix a few typos
  bin/cylc-check-software
  bin/cylc-ext-trigger
  bin/cylc-nudge
  bin/cylc-search
  bin/cylc-test-battery
  doc/src/appendices/suiterc-config-ref.rst
  doc/src/custom/cylc_lang.py
  doc/src/external-triggers.rst
  doc/src/running-suites.rst
  doc/src/tutorial.rst
  etc/cylc-bash-completion
  etc/examples/cycling/Monthly/suite.rc
  etc/examples/inherit/multi/one/suite.rc
  etc/examples/satellite/task-retries/suite.rc
  etc/global.rc.eg
  lib/parsec/validate.py
  tests/cylc-cat-log/06-log-rotation.t
  tests/cylc-get-config/00-simple/suite.rc
  tests/cylc-insert/00-insert/suite.rc
  tests/cylc-insert/04-insert-family/suite.rc
  tests/cylc-insert/05-insert-compat/suite.rc
  tests/cylc-insert/08-insert-family-compat/suite.rc
  tests/cylc-poll/03-poll-all/suite.rc
  tests/cylc-poll/16-execution-time-limit/suite.rc
  tests/cylc.host_appointer/00-host-appointer.t
  tests/ext-trigger/00-satellite/suite.rc
  tests/lib/bash/test_header
  tests/offset/03-final-next-chain.t
  tests/queues/02-queueorder.t
  tests/triggering/17-suicide-multi.t
  tests/validate/23-fail-old-syntax-7.t
  tests/validate/28-fail-max-active-cycle-points-zero.t
  tests/validate/31-fail-not-integer.t
  tests/validate/39-fail-suicide-left.t
  tests/validate/50-hyphen-fam.t
  tests/validate/51-zero-interval.t
Labels: doc

#3006 Remove cylc.profiling package and cylc-profile-battery
  bin/cylc-help
  bin/cylc-profile-battery
  doc/src/installation.rst
  etc/cylc-bash-completion
  etc/dev-suites/busy/suite.rc
  etc/dev-suites/busy_param/suite.rc
  etc/dev-suites/chains/suite.rc
  etc/dev-suites/complex/suite.rc
  etc/dev-suites/dave/suite.rc
  etc/dev-suites/diamond/suite.rc
  etc/dev-suites/family-triggers/suite.rc
  etc/dev-suites/hello-world/suite.rc
  etc/dev-suites/integer/one/suite.rc
  etc/dev-suites/iso8601/one/suite.rc
  etc/dev-suites/mshin/suite.rc
  etc/examples/xtrigger/kafka/consumer/lib/python/cylc_kafka_consumer.py
  etc/examples/xtrigger/kafka/consumer/suite.rc
  etc/examples/xtrigger/kafka/producer/bin/cylc_kafka_producer.py
  etc/examples/xtrigger/kafka/producer/suite.rc
  etc/examples/xtrigger/suite_state/downstream/suite.rc
  etc/examples/xtrigger/suite_state/upstream/suite.rc
  etc/examples/xtrigger/xrandom/suite.rc
  etc/profile-experiments/busy-validate.json
  etc/profile-experiments/busy.json
  etc/profile-experiments/complex-validate.json
  etc/profile-experiments/complex.json
  etc/profile-experiments/diamond-validate.json
  etc/profile-experiments/diamond.json
  etc/profile-experiments/example
  etc/profile-experiments/experiment.json
  etc/profile-experiments/family-trigger-validate.json
  etc/profile-experiments/hello-world-validate.json
  etc/profile-experiments/hello-world.json
  etc/profile-experiments/lazy-validate.json
  etc/profile-experiments/lazy.json
  etc/profile-experiments/profile-simulation/suite.rc
  etc/profile-experiments/test.json
  lib/cylc/profiling/__init__.py
  lib/cylc/profiling/analysis.py
  lib/cylc/profiling/git.py
  lib/cylc/profiling/profile.py
  tests/profile-battery/00-compatability.t
  tests/profile-battery/test_header
  tests/validate/04-builtin-suites.t
Labels: bug?, small

#3025 Fix dev-suites reference in docs (now in examples)
  doc/src/external-triggers.rst
Labels: doc, small

#3024 Remove remaining Cylc Review files
  ACKNOWLEDGEMENT.md
  bin/cylc-help
  doc/src/installation.rst
  doc/src/tutorial.rst
  lib/cylc/review_dao.py
  lib/cylc/task_state.py
  tests/lib/bash/test_header
Labels: doc, small

#3022 Removed LaTeX support from check-software.
  bin/cylc-check-software
Labels: small

#2968 Fix submit failed after reload
  lib/cylc/task_events_mgr.py
  lib/cylc/task_job_mgr.py
  lib/cylc/task_pool.py
  lib/cylc/task_proxy.py
  tests/reload/21-submit-fail.t
  tests/reload/21-submit-fail/bin/mycylcrun
  tests/reload/21-submit-fail/reference.log
  tests/reload/21-submit-fail/suite.rc
Labels: bug

#3029 Remove dev-suites from tests
  tests/validate/04-builtin-suites.t
Labels: small

#3031 Convert range to list so that we can use reduce
  lib/cylc/conditional_simplifier.py
  lib/cylc/tests/test_conditional_simplifier.py
Labels: bug, small

#3030 Trivial typo in parsec README
  lib/parsec/README.md
Labels: doc

#3033 Minor improvements for docstrings
  lib/cylc/batch_sys_handlers/loadleveler.py
  lib/cylc/batch_sys_handlers/lsf.py
  lib/cylc/batch_sys_handlers/moab.py
  lib/cylc/batch_sys_handlers/pbs.py
  lib/cylc/batch_sys_handlers/sge.py
  lib/cylc/cfgspec/suite.py
  lib/cylc/cfgvalidate.py
  lib/cylc/network/__init__.py
  lib/cylc/network/scan.py
  lib/parsec/fileparse.py
  lib/parsec/validate.py
Labels: doc, small

#3034 Remove unused imports
  bin/cylc-check-versions
  lib/parsec/fileparse.py
  lib/parsec/tests/test_util.py
  tests/cylc-cat-state/basic/state-check.py
Labels: small

#3044 Remove GTK labels from task states
  lib/cylc/task_state_prop.py
  lib/cylc/tests/test_task_state_prop.py
Labels: small

#3040 Add check for zero to xrandom
  lib/cylc/xtriggers/xrandom.py
Labels: bug

#3042 Add check for zero to xrandom (7.8.x backport)
  lib/cylc/xtriggers/xrandom.py
Labels: bug

#3018 Subprocpool: use SpooledTemporaryFile instead of TemporaryFile
  lib/cylc/subprocpool.py
  lib/cylc/task_remote_mgr.py
  lib/cylc/tests/test_subprocpool.py
Labels: non-cylc bug

#3028 Subprocpool: use SpooledTemporaryFile instead of TemporaryFile [7.8.x]
  lib/cylc/subprocpool.py
  lib/cylc/task_remote_mgr.py
  lib/cylc/tests/test_subprocpool.py
Labels: non-cylc bug

#3032 Fix syntax for array access in cylc check-software
  bin/cylc-check-software
Labels: bug
