Repository cylc/cylc-flow, pull requests merged in 2019-05, with the labels that each got.

#3140 Fix cylc-flow rename in README badges, setup.py, and a few more places
  .travis.yml
  CONTRIBUTING.md
  README.md
  doc/src/appendices/known-issues.rst
  doc/src/suite-design-guide/roadmap.rst
  lib/cylc/scheduler.py
  setup.py
  tests/authentication/11-suite2-stop-suite1.t
  tests/broadcast/08-space.t
  tests/cylc-get-site-config/04-homeless.t
  tests/cylc-trigger/06-reset-ready.t
  tests/events/45-task-event-handler-multi-warning.t
  tests/hold-release/20-reset-waiting-output.t
  tests/intercycle/02-integer-abs.t
  tests/intercycle/03-datetime-abs.t
  tests/intercycle/04-datetime-abs-2.t
  tests/intercycle/05-datetime-abs-3.t
  tests/job-file-trap/00-sigusr1.t
  tests/job-file-trap/02-pipefail.t
  tests/reload/14-waiting.t
  tests/reload/15-state-summary.t
  tests/reload/21-submit-fail.t
  tests/restart/13-bad-job-host.t
  tests/restart/32-reload-runahead-no-stop-point.t
  tests/restart/33-simulation.t
  tests/restart/42-auto-restart-ping-pong.t
  tests/special/08-clock-triggered-0.t
  tests/startup/00-state-summary.t
  tests/triggering/19-and-suicide.t
  tests/triggering/19-and-suicide/suite.rc
  tests/validate/50-hyphen-fam.t
  tests/validate/51-zero-interval.t
  tests/validate/55-hyphen-finish.t
Labels: doc

#3144 Fix links to cylc-flow in comments and other files
  .travis.yml
  CONTRIBUTING.md
  doc/src/appendices/known-issues.rst
  doc/src/suite-design-guide/roadmap.rst
  lib/cylc/scheduler.py
  tests/authentication/11-suite2-stop-suite1.t
  tests/broadcast/08-space.t
  tests/cylc-get-site-config/04-homeless.t
  tests/cylc-review/06-host-port.t
  tests/cylc-trigger/06-reset-ready.t
  tests/events/45-task-event-handler-multi-warning.t
  tests/hold-release/20-reset-waiting-output.t
  tests/intercycle/02-integer-abs.t
  tests/intercycle/03-datetime-abs.t
  tests/intercycle/04-datetime-abs-2.t
  tests/intercycle/05-datetime-abs-3.t
  tests/job-file-trap/00-sigusr1.t
  tests/job-file-trap/02-pipefail.t
  tests/reload/14-waiting.t
  tests/reload/15-state-summary.t
  tests/restart/13-bad-job-host.t
  tests/restart/32-reload-runahead-no-stop-point.t
  tests/restart/33-simulation.t
  tests/restart/42-auto-restart-ping-pong.t
  tests/special/08-clock-triggered-0.t
  tests/startup/00-state-summary.t
  tests/triggering/19-and-suicide.t
  tests/triggering/19-and-suicide/suite.rc
  tests/validate/50-hyphen-fam.t
  tests/validate/51-zero-interval.t
  tests/validate/55-hyphen-finish.t
Labels: doc

#3117 task/suite name validity: consistency & explicitness
  doc/src/appendices/suiterc-config-ref.rst
  doc/src/suite-config.rst
  doc/src/suite-name-reg.rst
  doc/src/tutorial.rst
Labels: bug

#3148 Fix some doc heading levels
  doc/src/custom/make-commands.sh
  doc/src/installation.rst
  doc/src/suite-config.rst
Labels: bug, doc

#3077 zmq: support single port configuration
  lib/cylc/network/client.py
  lib/cylc/network/server.py
  lib/cylc/tests/test_zmq.py
Labels: bug

#3083 Extend ZMQClient and update docstrings
  lib/cylc/network/client.py
  tests/shutdown/10-no-port-file.t
  tests/shutdown/18-client-on-dead-suite.t
Labels: small

#3153 async_map: fix bug
  lib/cylc/network/scan.py
Labels: bug

#3158 Fix \ in doco when wrapped in ``..``
  doc/src/appendices/suiterc-config-ref.rst
Labels: bug, doc

#3164 message: fix pclient undefined error
  bin/cylc-message
  cylc/flow/task_message.py
Labels: bug

#3166 Update changelog to include current alpha releases
  CHANGES.md
Labels: doc

#3172 Fix security email link
  SECURITY.md
Labels: doc

#3176 Fix a few typos
  cylc/flow/exceptions.py
  cylc/flow/task_state.py
Labels: doc

#3175 Remove unnecessary duplicate variable declaration
  cylc/flow/cycling/iso8601.py
Labels: small

#3174 Fix NameError on invalid cylc command
  CHANGES.md
  cylc/flow/job_file.py
  cylc/flow/tests/test_job_file.py
Labels: bug

#3183 debug cylc gui start
  CHANGES.md
  lib/cylc/gui/app_gcylc.py
Labels: bug
