Repository cylc/cylc-flow, pull requests merged in 2019-11, with the labels that each got.

#3430 Cover missing branch in duration_as (doctest)
  cylc/flow/jinja/filters/duration_as.py
Labels: small

#3437 Cylc Review: stop line numbers detaching from lines
  lib/cylc/cylc-review/template/view.html
Labels: small

#3435 fix param inherit family bug
  lib/cylc/param_expand.py
Labels: bug

#3359 Workflow service network layer auth & encryption
  bin/cylc-check-software
  cylc/flow/network/authentication.py
  cylc/flow/network/client.py
  cylc/flow/network/server.py
  cylc/flow/suite_files.py
  cylc/flow/tests/network/test_server.py
  cylc/flow/tests/test_zmq.py
  setup.cfg
  setup.py
Labels: security

#3439 parsec: add help for coercers (data types)
  cylc/flow/parsec/validate.py
  cylc/flow/subprocctx.py
  cylc/flow/tests/parsec/test_validate.py
Labels: doc
