Repository cylc/cylc-flow, pull requests merged in 2020-06, with the labels that each got.

#3635 remote_init: prevent init skipping for polling configurations
  cylc/flow/task_message.py
  cylc/flow/task_remote_mgr.py
Labels: bug

#3637 iso8601 cycler: lru_caching
  cylc/flow/cycling/iso8601.py
Labels: efficiency

#3636 profiler: use psutil
  cylc/flow/profiler.py
Labels: bug

#3649 remove unwanted debug from test
  tests/cylc-get-site-config/05-host-bool-override.t
Labels: small

#3500 UIS Delta subscriptions & GraphQL null stripping back-end
  cylc/flow/data_messages.proto
  cylc/flow/data_messages_pb2.py
  cylc/flow/data_store_mgr.py
  cylc/flow/job_pool.py
  cylc/flow/network/__init__.py
  cylc/flow/network/graphql.py
  cylc/flow/network/resolvers.py
  cylc/flow/network/schema.py
  cylc/flow/network/server.py
  cylc/flow/network/subscriber.py
  cylc/flow/tests/network/test_publisher.py
  cylc/flow/tests/network/test_resolvers.py
  cylc/flow/tests/network/test_schema.py
  cylc/flow/tests/network/test_server.py
  cylc/flow/tests/network/test_subscriber.py
  cylc/flow/tests/test_data_store_mgr.py
  cylc/flow/tests/test_job_pool.py
Labels: efficiency

#3608 Generate client keys on remote platforms
  cylc/flow/network/authentication.py
  cylc/flow/network/client.py
  cylc/flow/scheduler.py
  cylc/flow/scheduler_cli.py
  cylc/flow/suite_files.py
  cylc/flow/task_job_mgr.py
  cylc/flow/task_remote_cmd.py
  cylc/flow/task_remote_mgr.py
  cylc/flow/tests/network/key_setup.py
  cylc/flow/tests/network/test_client.py
  cylc/flow/tests/network/test_server.py
  cylc/flow/tests/network/test_zmq.py
  tests/cylc-scan/02-sigstop.t
Labels: security

#3650 profiler: dump data file for analysis
  cylc/flow/profiler.py
  cylc/flow/scheduler.py
Labels: small
