Repository cylc/cylc-flow, pull requests merged in 2020-07, with the labels that each got.

#3661 Remove scheduler keys on shutdown
  cylc/flow/network/authentication.py
  cylc/flow/scheduler.py
  cylc/flow/scheduler_cli.py
  tests/authentication/03-check-keys-local.t
  tests/authentication/04-check-keys-remote.t
Labels: security

#3680 cli: highlight comments in usage strings
  cylc/flow/option_parsers.py
  cylc/flow/scheduler_cli.py
Labels: small

#3701 scheduler: remote-init after server start
  cylc/flow/scheduler.py
Labels: bug

#3702 Revert "CYLC_CONF_PATH: modify interpretation"
  cylc/flow/cfgspec/globalcfg.py
  cylc/flow/parsec/fileparse.py
  tests/cylc-get-site-config/06-cylc-conf-path.t
  tests/functional/cylc-get-site-config/06-cylc-conf-path.t
Labels: bug

#3632 Fix global UTC mode bug
  CHANGES.md
  cylc/flow/cfgspec/globalcfg.py
  cylc/flow/cfgspec/suite.py
  cylc/flow/config.py
Labels: bug, small

#3705 add protobuf field number warning
  cylc/flow/data_messages.proto
Labels: small

#3708 fix tui task parent grouping
  cylc/flow/tui/data.py
  cylc/flow/tui/util.py
  tests/unit/tui/test_util.py
Labels: small

#3707 Reduce data-store family nodes to first parent ancestors
  cylc/flow/data_store_mgr.py
  cylc/flow/network/graphql.py
  tests/functional/graphql/02-root-queries.t
Labels: small

#3722 Replace non-breaking spaces
  cylc/flow/main_loop/__init__.py
  etc/bin/run-functional-tests
  tests/flakyfunctional/README.md
  tests/functional/README.md
  tests/functional/cylc-run/02-format.t
  tests/functional/rnd/00-run-funtional-tests.t
  tests/integration/README.md
  tests/unit/README.md
  tests/unit/parsec/test_types.py
Labels: small

#3719 Fix ICP offset var type.
  cylc/flow/graphnode.py
Labels: small
