Repository cylc/cylc-flow, pull requests merged in 2020-11, with the labels that each got.

#3905 conf: remove explicit group meta entry
  cylc/flow/cfgspec/suite.py
  tests/flakyfunctional/cylc-show/00-simple.t
  tests/functional/validate/60-group.t
  tests/functional/validate/60-group/flow.cylc
Labels: doc

#3909 GH Actions: Upgrade deprecated add-path command
  .github/workflows/test.yml
Labels: small

#3823 Hide waiting tasks from n=0.
  cylc/flow/scheduler.py
  cylc/flow/task_pool.py
  cylc/flow/task_state.py
  tests/flakyfunctional/cylc-take-checkpoints/00-basic.t
  tests/flakyfunctional/cylc-take-checkpoints/00-basic/flow.cylc
  tests/flakyfunctional/cylc-take-checkpoints/00-basic/reference.log
  tests/flakyfunctional/cylc-take-checkpoints/test_header
  tests/flakyfunctional/events/40-stall-despite-clock-trig.t
  tests/flakyfunctional/events/40-stall-despite-clock-trig/flow.cylc
  tests/flakyfunctional/restart/21-task-elapsed.t
  tests/functional/events/26-suite-stalled-dump-prereq.t
  tests/functional/events/26-suite-stalled-dump-prereq/flow.cylc
  tests/functional/events/27-suite-stalled-dump-prereq-fam.t
  tests/functional/events/27-suite-stalled-dump-prereq-fam/flow.cylc
  tests/functional/hold-release/02-hold-on-spawn.t
  tests/functional/restart/22-hold/flow.cylc
  tests/functional/runahead/03-check-default-future.t
  tests/functional/runahead/05-check-default-future-2.t
  tests/functional/runahead/06-release-update.t
  tests/functional/runahead/default-future/flow.cylc
  tests/functional/runahead/no_final/flow.cylc
  tests/functional/shutdown/09-now2.t
Labels: sod-follow-up

#3882 Fix polled task:start bug
  cylc/flow/task_events_mgr.py
  tests/functional/remote/03-polled-task-started.t
  tests/functional/remote/03-polled-task-started/flow.cylc
  tests/functional/remote/03-polled-task-started/reference.log
Labels: bug, small

#3863 Store task prerequisites in their own DB table
  CHANGES.md
  cylc/flow/prerequisite.py
  cylc/flow/rundb.py
  cylc/flow/scheduler.py
  cylc/flow/suite_db_mgr.py
  cylc/flow/task_pool.py
  tests/flakyfunctional/database/00-simple/schema.out
  tests/flakyfunctional/restart/19-checkpoint.t
  tests/functional/job-submission/01-job-nn-localhost/db.sqlite3
  tests/functional/restart/53-task-prerequisites.t
  tests/functional/restart/53-task-prerequisites/flow.cylc
  tests/functional/restart/54-incompatible-db.t
  tests/functional/restart/54-incompatible-db/db.sqlite3
  tests/functional/restart/54-incompatible-db/flow.cylc
  tests/functional/retries/03-upgrade.t
  tests/functional/retries/03-upgrade/.service/db
  tests/functional/retries/03-upgrade/flow.cylc
  tests/unit/test_rundb.py
Labels: sod-follow-up

#3924 fix null-stripping of repeated composite fields
  cylc/flow/network/graphql.py
  tests/unit/network/test_graphql.py
Labels: bug

#3926 conf: cylc->scheduler
  cylc/flow/main_loop/__init__.py
  cylc/flow/scheduler.py
  cylc/flow/scheduler_cli.py
  cylc/flow/suite_events.py
  etc/bin/start-group-demo.sh
  tests/functional/remote/03-polled-task-started/flow.cylc
  tests/functional/restart/53-task-prerequisites/flow.cylc
  tests/unit/conftest.py
  tests/unit/test_config.py
Labels: config change, small

#3928 cli: fix --host reinvocation
  cylc/flow/scheduler_cli.py
Labels: bug

#3811 n-distance data-store graph window generation/pruning
  CHANGES.md
  cylc/flow/config.py
  cylc/flow/data_store_mgr.py
  cylc/flow/network/resolvers.py
  cylc/flow/network/schema.py
  cylc/flow/scheduler.py
  cylc/flow/task_pool.py
  cylc/flow/task_proxy.py
  cylc/flow/taskdef.py
  cylc/flow/tui/util.py
  tests/functional/graph-equivalence/multiline_and_refs/c-ref
  tests/functional/graph-equivalence/multiline_and_refs/c-ref-2
  tests/functional/graphql/01-workflow.t
  tests/functional/graphql/02-root-queries.t
  tests/functional/runahead/06-release-update.t
  tests/integration/test_data_store_mgr.py
Labels: efficiency

#3914 Finish off mail config changes
  cylc/flow/cfgspec/globalcfg.py
  cylc/flow/cfgspec/suite.py
  cylc/flow/parsec/upgrade.py
  cylc/flow/scheduler.py
  cylc/flow/task_events_mgr.py
  tests/functional/cylc-get-config/00-simple/section2.stdout
  tests/functional/deprecations/01-cylc8-basic/flow.cylc
  tests/functional/deprecations/01-cylc8-basic/validation.stderr
  tests/functional/events/09-task-event-mail.t
  tests/functional/events/09-task-event-mail/flow.cylc
  tests/functional/events/18-suite-event-mail.t
  tests/functional/events/18-suite-event-mail/flow.cylc
  tests/functional/events/29-task-event-mail-1.t
  tests/functional/events/29-task-event-mail-1/flow.cylc
  tests/functional/events/30-task-event-mail-2.t
  tests/functional/events/30-task-event-mail-2/flow.cylc
  tests/unit/parsec/test_upgrade.py
Labels: config change

#3942 Remove "disable automatic shutdown"
  cylc/flow/cfgspec/suite.py
  cylc/flow/etc/syntax/cylc.lang
  cylc/flow/etc/syntax/cylc.xml
  cylc/flow/scheduler.py
  cylc/flow/scheduler_cli.py
  cylc/flow/suite_db_mgr.py
  tests/flakyfunctional/events/31-dont-stall-succeeded.t
  tests/flakyfunctional/events/31-dont-stall-succeeded/flow.cylc
  tests/flakyfunctional/restart/47-no-auto-stop.t
  tests/functional/deprecations/01-cylc8-basic/flow.cylc
  tests/functional/deprecations/01-cylc8-basic/validation.stderr
  tests/functional/restart/48-enable-auto-stop.t
  tests/functional/restart/49-enable-auto-stop-2.t
  tests/functional/shutdown/05-auto.t
  tests/functional/shutdown/05-auto/flow.cylc
  tests/integration/test_examples.py
Labels: config change

#3943 Global config changes: process pool, logging
  cylc/flow/cfgspec/globalcfg.py
  cylc/flow/loggingutil.py
  cylc/flow/pathutil.py
  cylc/flow/subprocpool.py
  etc/bin/run-functional-tests
  tests/flakyfunctional/events/44-timeout.t
  tests/flakyfunctional/job-submission/18-check-chunking.t
  tests/flakyfunctional/job-submission/19-chatty.t
  tests/functional/events/47-long-output.t
  tests/functional/job-submission/16-timeout.t
  tests/functional/lib/bash/test_header
  tests/functional/logging/03-roll.t
  tests/unit/test_pathutil.py
Labels: config change

#3945 remote: clarify platform/host commands
  cylc/flow/host_select.py
  cylc/flow/remote.py
  cylc/flow/scheduler_cli.py
  cylc/flow/scripts/cat_log.py
  cylc/flow/scripts/check_versions.py
  cylc/flow/task_job_mgr.py
  cylc/flow/task_remote_mgr.py
Labels: small

#3949 Fix remote init failures
  cylc/flow/task_remote_cmd.py
  tests/unit/test_task_remote_cmd.py
Labels: bug

#3967 removed [cylc]exclude at start-up and [cylc]include at start-up
  cylc/flow/cfgspec/suite.py
  cylc/flow/etc/syntax/cylc.lang
  cylc/flow/etc/syntax/cylc.xml
  cylc/flow/scheduler.py
  tests/functional/cylc-get-config/00-simple/section1.stdout
  tests/functional/special/02-exclude.t
  tests/functional/special/02-exclude/flow.cylc
  tests/functional/special/02-exclude/reference.log
  tests/functional/special/03-include.t
  tests/functional/special/03-include/flow.cylc
  tests/functional/special/03-include/reference.log
  tests/functional/validate/08-whitespace/flow.cylc
Labels: config change
