Repository cylc/cylc-flow, pull requests merged in 2020-10, with the labels that each got.

#3845 flow-cfg-update.authentication
  cylc/flow/cfgspec/globalcfg.py
  cylc/flow/cfgspec/suite.py
  cylc/flow/network/authorisation.py
  cylc/flow/network/server.py
  tests/functional/deprecations/01-cylc8-basic.t
  tests/functional/deprecations/01-cylc8-basic/flow.cylc
Labels: small

#3844 workflow config update: remove force/require run mode
  cylc/flow/cfgspec/suite.py
  cylc/flow/config.py
  cylc/flow/etc/syntax/cylc.lang
  cylc/flow/etc/syntax/cylc.xml
  cylc/flow/scheduler.py
  tests/flakyfunctional/execution-time-limit/04-poll.t
  tests/functional/broadcast/08-space.t
  tests/functional/deprecations/01-cylc8-basic.t
  tests/functional/deprecations/01-cylc8-basic/flow.cylc
  tests/functional/hold-release/18-hold-cycle-globs.t
  tests/functional/hold-release/19-no-reset-prereq-on-waiting.t
  tests/functional/lib/bash/test_header
  tests/functional/modes/01-dummy.t
  tests/functional/modes/01-dummy/flow.cylc
Labels: platforms-follow-up, small

#3851 docs: fix link to external triggers
  doc/src/suite-config.rst
Labels: doc

#3858 Fix minor issues found while reviewing task states PR's
  cylc/flow/network/scan.py
  cylc/flow/parsec/validate.py
  cylc/flow/platforms.py
  cylc/flow/remote.py
  cylc/flow/scheduler.py
  cylc/flow/suite_files.py
  cylc/flow/task_pool.py
  cylc/flow/task_remote_cmd.py
  cylc/flow/task_remote_mgr.py
  cylc/flow/task_state.py
  cylc/flow/time_parser.py
  cylc/flow/xtriggers/suite_state.py
  cylc/flow/xtriggers/xrandom.py
Labels: small

#3859 Use the ID key when querying for broadcast checkpoints
  CHANGES.md
  cylc/flow/rundb.py
  tests/functional/broadcast/14-broadcast-checkpoint.t
  tests/functional/broadcast/14-broadcast-checkpoint/flow.cylc
Labels: bug

#3848 Move `max active cycle points` behaviour into `runahead limit`
  CHANGES.md
  cylc/flow/cfgspec/suite.py
  cylc/flow/config.py
  cylc/flow/etc/syntax/cylc.lang
  cylc/flow/etc/syntax/cylc.xml
  cylc/flow/task_pool.py
  tests/flakyfunctional/integer-cycling/00-satellite/flow.cylc
  tests/functional/cyclers/integer1/flow.cylc
  tests/functional/cyclers/integer_exclusions_advanced/flow.cylc
  tests/functional/cylc-get-config/00-simple/section1.stdout
  tests/functional/cylc-show/05-complex/flow.cylc
  tests/functional/deprecations/01-cylc8-basic.t
  tests/functional/deprecations/01-cylc8-basic/flow.cylc
  tests/functional/ext-trigger/00-satellite/flow.cylc
  tests/functional/periodicals/Daily/flow.cylc
  tests/functional/periodicals/Monthly-reorder/flow.cylc
  tests/functional/periodicals/Monthly/flow.cylc
  tests/functional/periodicals/Yearly/flow.cylc
  tests/functional/reload/10-runahead.t
  tests/functional/reload/22-remove-task-cycling.t
  tests/functional/reload/runahead/flow.cylc
  tests/functional/restart/32-reload-runahead-no-stop-point/flow.cylc
  tests/functional/runahead/00-runahead.t
  tests/functional/runahead/01-check-default-simple.t
  tests/functional/runahead/02-check-default-complex.t
  tests/functional/runahead/03-check-default-future.t
  tests/functional/runahead/05-check-default-future-2.t
  tests/functional/runahead/07-time-limit.t
  tests/functional/runahead/default-complex/flow.cylc
  tests/functional/runahead/default-future/flow.cylc
  tests/functional/runahead/default-simple/flow.cylc
  tests/functional/runahead/no_final/flow.cylc
  tests/functional/runahead/release-update/flow.cylc
  tests/functional/runahead/runahead/flow.cylc
  tests/functional/runahead/time-limit/flow.cylc
  tests/functional/validate/28-fail-max-active-cycle-points-zero.t
  tests/functional/validate/28-fail-max-active-cycle-points-zero/flow.cylc
  tests/functional/validate/36-fail-double-runahead/flow.cylc
  tests/functional/validate/60-group/flow.cylc
  tests/unit/conftest.py
  tests/unit/test_config.py
  tests/unit/test_config_upgrader.py
Labels: sod-follow-up

#3870 update readme
  README.md
Labels: small

#3876 add copyright notices to files where it was missing.
  cylc/flow/context_node.py
  cylc/flow/host_select.py
  cylc/flow/scripts/cylc_extract_resources.py
  cylc/flow/scripts/cylc_help.py
  cylc/flow/scripts/cylc_psutil.py
  cylc/flow/tui/data.py
  tests/functional/jinja2/08-local-lib-python/Jinja2Filters/qualify.py
  tests/functional/jinja2/08-local-lib-python/lib/python/local_lookup.py
  tests/functional/jinja2/filters/Jinja2Filters/hello.py
  tests/functional/jinja2/filters/Jinja2Filters/truly.py
  tests/functional/rnd/02-lib-python-in-job/lib/python/pub/beer.py
  tests/functional/xtriggers/02-persistence/faker_fail.py
  tests/functional/xtriggers/02-persistence/faker_succ.py
  tests/integration/test_client.py
  tests/unit/main_loop/auto_restart.py
  tests/unit/main_loop/log_data_store.py
  tests/unit/main_loop/log_main_loop.py
  tests/unit/main_loop/log_memory.py
  tests/unit/main_loop/main_loop.py
  tests/unit/option_parsers.py
  tests/unit/parsec/test_config_node.py
  tests/unit/parsec/test_dict_tree.py
  tests/unit/parsec/test_types.py
  tests/unit/test_context_node.py
  tests/unit/test_host_select_remote.py
  tests/unit/tui/test_data.py
  tests/unit/tui/test_overlay.py
  tests/unit/tui/test_util.py
Labels: could-be-better

#3846 move [cylc][events]mail (.*) -> [cylc][mail]
  cylc/flow/cfgspec/globalcfg.py
  cylc/flow/cfgspec/suite.py
  cylc/flow/etc/syntax/cylc.lang
  cylc/flow/etc/syntax/cylc.xml
  cylc/flow/scheduler.py
  cylc/flow/suite_events.py
  cylc/flow/task_events_mgr.py
  tests/functional/cylc-get-config/00-simple/section2.stdout
  tests/functional/deprecations/01-cylc8-basic.t
  tests/functional/deprecations/01-cylc8-basic/flow.cylc
  tests/functional/deprecations/01-cylc8-basic/validation.stderr
  tests/functional/events/09-task-event-mail.t
  tests/functional/events/09-task-event-mail/flow.cylc
  tests/functional/events/18-suite-event-mail.t
  tests/functional/events/18-suite-event-mail/flow.cylc
  tests/functional/events/29-task-event-mail-1/flow.cylc
  tests/functional/events/30-task-event-mail-2.t
  tests/functional/events/30-task-event-mail-2/flow.cylc
  tests/unit/test_suite_events.py
Labels: small

#3877 Fix deprecation upgrade warning message
  cylc/flow/cfgspec/suite.py
Labels: small

#3878 Glbl cfg update.mail
  cylc/flow/cfgspec/suite.py
Labels: doc, small

#3852 Disallow nested run directories
  CHANGES.md
  cylc/flow/network/scan.py
  cylc/flow/suite_files.py
  tests/unit/test_suite_files.py
Labels: bug?

#3885 doc: update reference labels
  cylc/flow/cfgspec/suite.py
  cylc/flow/parsec/validate.py
Labels: doc, small

#3888 cat-log: fix probable rebase error
  cylc/flow/scripts/cylc_cat_log.py
Labels: bug

#3883 Config change.stop after cycle point
  CHANGES.md
  cylc/flow/cfgspec/suite.py
  cylc/flow/scheduler.py
  cylc/flow/scheduler_cli.py
  tests/flakyfunctional/restart/21-task-elapsed.t
  tests/functional/cylc-get-config/00-simple/section1.stdout
  tests/functional/restart/08-stop-after-cycle-point.t
  tests/functional/restart/08-stop-after-cycle-point/flow.cylc
  tests/unit/test_scheduler.py
Labels: small
