Repository cylc/cylc-flow, pull requests merged in 2020-08, with the labels that each got.

#3732 xtriggers: validate labels (master)
  CHANGES.md
  cylc/flow/config.py
  cylc/flow/unicode_rules.py
  tests/functional/validate/73-xtrigger-names.t
Labels: bug

#3734 xtriggers: validate labels (7.8.x)
  CHANGES.md
  doc/src/external-triggers.rst
  lib/cylc/config.py
  lib/cylc/unicode_rules.py
  tests/validate/73-xtrigger-names.t
Labels: bug

#3771 convert to new new style classes
  cylc/flow/batch_sys_handlers/background.py
  cylc/flow/batch_sys_handlers/moab.py
  cylc/flow/batch_sys_handlers/pbs.py
  cylc/flow/batch_sys_handlers/sge.py
  cylc/flow/broadcast_mgr.py
  cylc/flow/c3mro.py
  cylc/flow/command_polling.py
  cylc/flow/conditional_simplifier.py
  cylc/flow/config.py
  cylc/flow/cycling/iso8601.py
  cylc/flow/cycling/loader.py
  cylc/flow/dbstatecheck.py
  cylc/flow/graph_parser.py
  cylc/flow/graphnode.py
  cylc/flow/hostuserutil.py
  cylc/flow/job_file.py
  cylc/flow/param_expand.py
  cylc/flow/parsec/config.py
  cylc/flow/parsec/upgrade.py
  cylc/flow/parsec/validate.py
  cylc/flow/prerequisite.py
  cylc/flow/profiler.py
  cylc/flow/rundb.py
  cylc/flow/scheduler.py
  cylc/flow/scripts/cylc_report_timings.py
  cylc/flow/state_summary_mgr.py
  cylc/flow/subprocctx.py
  cylc/flow/subprocpool.py
  cylc/flow/suite_db_mgr.py
  cylc/flow/task_action_timer.py
  cylc/flow/task_id.py
  cylc/flow/task_job_mgr.py
  cylc/flow/task_outputs.py
  cylc/flow/task_pool.py
  cylc/flow/task_proxy.py
  cylc/flow/task_remote_mgr.py
  cylc/flow/task_state.py
  cylc/flow/task_trigger.py
  cylc/flow/taskdef.py
  cylc/flow/time_parser.py
  cylc/flow/xtrigger_mgr.py
  tests/functional/job-submission/06-garbage/lib/bad.py
  tests/functional/lib/python/diffr.py
  tests/unit/network/test_scan.py
  tests/unit/test_config.py
Labels: small

#3759 Bugfix: cylc-gui - tasks momentarily out of sequence
  CONTRIBUTING.md
  lib/cylc/gui/view_tree.py
Labels: bug

#3775 gh-actions: Set time limits for test jobs
  .github/workflows/test.yml
Labels: small

#3774 Remove interactive prompt support
  CHANGES.md
  cylc/flow/cfgspec/globalcfg.py
  cylc/flow/option_parsers.py
  cylc/flow/scripts/cylc_dump.py
  cylc/flow/scripts/cylc_hold.py
  cylc/flow/scripts/cylc_kill.py
  cylc/flow/scripts/cylc_poll.py
  cylc/flow/scripts/cylc_release.py
  cylc/flow/scripts/cylc_reload.py
  cylc/flow/scripts/cylc_remove.py
  cylc/flow/scripts/cylc_scan.py
  cylc/flow/scripts/cylc_set_verbosity.py
  cylc/flow/scripts/cylc_show.py
  cylc/flow/scripts/cylc_spawn.py
  cylc/flow/scripts/cylc_stop.py
  cylc/flow/scripts/cylc_subscribe.py
  cylc/flow/scripts/cylc_trigger.py
  cylc/flow/terminal.py
  tests/functional/directives/01-at/suite.rc
  tests/functional/directives/loadleveler/suite.rc
  tests/functional/directives/pbs/suite.rc
  tests/functional/directives/slurm/suite.rc
  tests/functional/graph-equivalence/00-oneline.t
  tests/functional/graph-equivalence/01-twolines.t
  tests/functional/graph-equivalence/02-splitline.t
  tests/functional/graph-equivalence/03-multiline_and1.t
  tests/functional/graph-equivalence/04-multiline_and2.t
  tests/functional/reload/00-simple/suite.rc
  tests/functional/reload/01-startup/suite.rc
  tests/functional/reload/02-content/suite.rc
  tests/functional/reload/03-queues/suite.rc
  tests/functional/reload/04-inheritance/suite.rc
  tests/functional/reload/05-graphing-simple/suite.rc
  tests/functional/reload/06-graphing-fam/suite.rc
  tests/functional/reload/07-final-cycle/suite.rc
  tests/functional/reload/08-cycle/suite.rc
  tests/functional/reload/11-retrying/suite.rc
  tests/functional/reload/garbage/suite.rc
  tests/functional/reload/runahead/suite.rc
Labels: small

#3579 Test Cylc with different bash versions
  .github/workflows/bash.yml
  dockerfiles/bash/Dockerfile
  dockerfiles/bash/build-bash
  dockerfiles/bash/build-bash-versions
Labels: speculative

#3727 cyclers: fix ingest_time
  cylc/flow/cycling/iso8601.py
Labels: bug

#3614 Fix 3462 - cylc restart after time zone change bug
  CHANGES.md
  cylc/flow/cfgspec/suite.py
  cylc/flow/config.py
  cylc/flow/scheduler.py
  cylc/flow/suite_db_mgr.py
  tests/flakyfunctional/database/00-simple.t
  tests/functional/reload/23-cycle-point-time-zone.t
  tests/functional/restart/52-cycle-point-time-zone.t
  tests/unit/test_config.py
Labels: bug

#3756 Fix sequence bounds check for parent tasks.
  cylc/flow/taskdef.py
  tests/functional/spawn-on-demand/08-lost-parents.t
  tests/functional/spawn-on-demand/08-lost-parents/flow.cylc
  tests/functional/spawn-on-demand/08-lost-parents/reference.log
Labels: bug, sod-follow-up

#3777 auto-document cylc modules
  cylc/flow/batch_sys_handlers/__init__.py
  cylc/flow/batch_sys_handlers/at.py
  cylc/flow/batch_sys_handlers/background.py
  cylc/flow/batch_sys_handlers/loadleveler.py
  cylc/flow/batch_sys_handlers/lsf.py
  cylc/flow/batch_sys_handlers/moab.py
  cylc/flow/batch_sys_handlers/pbs.py
  cylc/flow/batch_sys_handlers/sge.py
  cylc/flow/batch_sys_handlers/slurm.py
  cylc/flow/cfgspec/suite.py
  cylc/flow/jinja/filters/duration_as.py
  cylc/flow/jinja/filters/pad.py
  cylc/flow/jinja/filters/strftime.py
  etc/bin/run-functional-tests
  tests/flakyfunctional/cyclers/19-async_integer.t
Labels: doc

#3786 Rename _rc -> _config
  cylc/flow/scheduler.py
  tests/functional/startup/01-log-flow-config.t
Labels: small

#3788 Validate task messages
  CHANGES.md
  cylc/flow/__init__.py
  cylc/flow/config.py
  cylc/flow/scripts/cylc_message.py
  cylc/flow/scripts/cylc_set_verbosity.py
  cylc/flow/task_events_mgr.py
  cylc/flow/unicode_rules.py
  tests/unit/test_suite_files.py
  tests/unit/test_unicode_rules.py
Labels: bug, small

#3789 Tidy cfgspec/parsec slightly
  cylc/flow/cfgspec/globalcfg.py
  cylc/flow/cfgspec/suite.py
  cylc/flow/parsec/OrderedDict.py
Labels: small

#3724 async scan
  CHANGES.md
  bin/cylc-graph-diff
  cylc/flow/async_util.py
  cylc/flow/cfgspec/suite.py
  cylc/flow/etc/cylc-bash-completion
  cylc/flow/network/__init__.py
  cylc/flow/network/client.py
  cylc/flow/network/scan.py
  cylc/flow/option_parsers.py
  cylc/flow/print_tree.py
  cylc/flow/scripts/cylc_print.py
  cylc/flow/scripts/cylc_scan.py
  cylc/flow/suite_files.py
  setup.cfg
  setup.py
  tests/functional/cylc-scan/01-scan.t
  tests/functional/cylc-scan/02-sigstop.t
  tests/functional/cylc-scan/02-sigstop/flow.cylc
  tests/functional/cylc-scan/04-outputs.t
  tests/functional/registration/00-simple.t
  tests/functional/registration/01-no-skip1.t
  tests/integration/test_async_util.py
  tests/integration/test_scan.py
  tests/integration/test_scan_api.py
  tests/integration/test_suite_files.py
  tests/unit/network/test_scan.py
  tests/unit/network/test_scan_nt.py
  tests/unit/test_async_util.py
Labels: efficiency
