Repository cylc/cylc-flow, pull requests merged in 2021-05, with the labels that each got.

#4087 rsync format
  cylc/flow/remote.py
  cylc/flow/task_remote_mgr.py
  cylc/flow/workflow_files.py
  tests/functional/cylc-reinstall/01-file-transfer.t
Labels: small

#4212 Made a template vars clash variable and make Cylc handle it elegently
  cylc/flow/parsec/exceptions.py
  cylc/flow/parsec/fileparse.py
  cylc/flow/scheduler.py
  tests/unit/parsec/test_fileparse_templating_clash.py
Labels: bug, small

#4221 subprocpool: handle PermissionError on killpg
  cylc/flow/subprocpool.py
Labels: bug?

#4223 Log "processing n queued commands" before they've completed instead of after
  cylc/flow/scheduler.py
Labels: could-be-better, small

#4222 Close public database correctly
  CHANGES.md
  cylc/flow/rundb.py
  cylc/flow/workflow_db_mgr.py
  tests/integration/conftest.py
  tests/integration/test_resolvers.py
  tests/integration/utils/flow_tools.py
Labels: bug

#4229 this tests appears to have been inoperative for some time
  tests/functional/job-submission/19-platform_select.t
  tests/functional/job-submission/19-platform_select/flow.cylc
Labels: small

#4227 Fix ICP bug.
  CHANGES.md
  cylc/flow/config.py
  tests/unit/conftest.py
  tests/unit/test_config.py
  tests/unit/test_task_trigger.py
Labels: bug
