Repository cylc/cylc-flow, pull requests merged in 2021-12, with the labels that each got.

#4541 Pin to Python 3.9.
  .github/workflows/1_create_release_pr.yml
  .github/workflows/2_auto_publish_release.yml
Labels: small, infrastructure

#4506 Remove the suite.rc flow.cylc symlink
  CHANGES.md
  cylc/flow/workflow_files.py
  tests/functional/cylc-install/00-simple.t
  tests/functional/cylc-install/02-failures.t
  tests/functional/cylc-reinstall/00-simple.t
  tests/functional/cylc-reinstall/01-file-transfer.t
  tests/functional/cylc-reinstall/02-failures.t
  tests/functional/deprecations/03-suiterc.t
  tests/functional/optional-outputs/03-c7backcompat.t
  tests/unit/test_workflow_files.py
Labels: small

#4521 `<datetime>-<start/restart/reload>.cylc` contain processed, sparse config.
  CHANGES.md
  cylc/flow/parsec/config.py
  cylc/flow/parsec/util.py
  cylc/flow/scheduler.py
  tests/functional/startup/01-log-flow-config.t
Labels: small

#4536 made cylc wrapper script available using cylc extract-resources
  CHANGES.md
  cylc/flow/etc/cylc
  cylc/flow/resources.py
  cylc/flow/scheduler.py
  cylc/flow/scripts/get_resources.py
  cylc/flow/task_remote_cmd.py
  setup.cfg
  tests/functional/cli/01-help.t
  tests/unit/test_resources.py
Labels: small

#4544 Tidy + reinstate deleted workflow_files unit test
  cylc/flow/workflow_files.py
  tests/unit/test_workflow_files.py
Labels: small

#4543 Make `--stopcp=reload` use `[scheduling]stop after cycle point` instead of the final cycle point
  CHANGES.md
  cylc/flow/scheduler.py
  cylc/flow/scheduler_cli.py
  tests/functional/cylc-play/06-warnif-scp-after-fcp.t
  tests/functional/restart/08-stop-after-cycle-point.t
  tests/functional/restart/08-stop-after-cycle-point/flow.cylc
  tests/functional/restart/44-stop-point.t
  tests/unit/test_scheduler.py
Labels: could-be-better

#4540 Handle PBS 19.2.1+ job names.
  CHANGES.md
  cylc/flow/job_runner_handlers/pbs.py
Labels: bug

#4548 Change VCS info file format to JSON
  CHANGES.md
  cylc/flow/install_plugins/log_vc_info.py
  tests/functional/post-install/00-log-vc-info.t
  tests/unit/post_install/test_log_vc_info.py
Labels: small

#4549 Workflow name validation: prevent reserved dir names in workflow name
  cylc/flow/workflow_files.py
  tests/functional/cylc-install/02-failures.t
  tests/unit/conftest.py
  tests/unit/test_workflow_files.py
Labels: small, could-be-better

#4547 Install scan depth
  CHANGES.md
  cylc/flow/cfgspec/globalcfg.py
  cylc/flow/network/scan.py
  cylc/flow/workflow_files.py
  tests/conftest.py
  tests/functional/cylc-install/07-no-recursive-installations.t
  tests/functional/cylc-play/07-provided-vars.t
  tests/integration/test_scan.py
  tests/unit/conftest.py
  tests/unit/scripts/test_scan.py
  tests/unit/test_workflow_files.py
Labels: config change

#4550 remove the color/no-colour option from cylc cyclepoint
  cylc/flow/scripts/cycle_point.py
Labels: small

#4553 Fix job submit time delta.
  CHANGES.md
  cylc/flow/task_events_mgr.py
  cylc/flow/task_proxy.py
  tests/functional/graphql/03-is-held-arg.t
  tests/functional/lib/python/diffr.py
Labels: bug
