Repository cylc/cylc-flow, pull requests merged in 2021-06, with the labels that each got.

#4103 Post-SoD refactor: remove pflag, runahead pool
  CHANGES.md
  cylc/flow/broadcast_mgr.py
  cylc/flow/data_messages.proto
  cylc/flow/data_messages_pb2.py
  cylc/flow/data_store_mgr.py
  cylc/flow/network/schema.py
  cylc/flow/scheduler.py
  cylc/flow/scripts/dump.py
  cylc/flow/task_events_mgr.py
  cylc/flow/task_pool.py
  cylc/flow/task_proxy.py
  cylc/flow/task_queues/__init__.py
  cylc/flow/task_queues/independent.py
  cylc/flow/task_state.py
  cylc/flow/tui/__init__.py
  cylc/flow/tui/data.py
  cylc/flow/tui/overlay.py
  cylc/flow/tui/util.py
  cylc/flow/xtrigger_mgr.py
  tests/flakyfunctional/database/01-broadcast/flow.cylc
  tests/flakyfunctional/hold-release/14-hold-kill/flow.cylc
  tests/functional/graphql/01-workflow.t
  tests/functional/reload/03-queues/flow.cylc
  tests/functional/reload/10-runahead.t
  tests/functional/reload/runahead/flow.cylc
  tests/functional/restart/53-task-prerequisites.t
  tests/integration/test_examples.py
  tests/integration/test_resolvers.py
  tests/unit/test_task_events_mgr.py
  tests/unit/test_task_events_mgr_2.py
  tests/unit/test_xtrigger_mgr.py
  tests/unit/tui/test_util.py
Labels: sod-follow-up

#4235 Fix TUI help splash screen
  cylc/flow/tui/overlay.py
Labels: bug?, question

#4240 Refactor cycling_type unit test fixture
  tests/unit/conftest.py
  tests/unit/test_config.py
  tests/unit/test_task_trigger.py
Labels: small

#4249 Fix mistake in workflow_files
  .github/workflows/test_fast.yml
  cylc/flow/workflow_files.py
Labels: bug, small

#4245 logging: log graphql requests at debug level
  cylc/flow/network/authorisation.py
Labels: small

#4244 pause: workflow cannot be stalled if it is paused
  cylc/flow/scheduler.py
Labels: bug

#4253 Use object local to GraphQL subscription for id
  cylc/flow/network/resolvers.py
  cylc/flow/network/schema.py
Labels: bug

#4233 Problem: replacement of "suite" with "workflow" breaks review.
  lib/cylc/review.py
  lib/cylc/review_dao.py
Labels: bug

#4248 Fix param expansion in inherited environment.
  CHANGES.md
  cylc/flow/config.py
  cylc/flow/param_expand.py
  tests/functional/param_expand/03-env-tmpl.t
  tests/functional/param_expand/03-env-tmpl/flow.cylc
  tests/functional/param_expand/03-env-tmpl/reference.log
  tests/functional/param_expand/03-env-tmpl/t1-0099-that.ref
  tests/functional/param_expand/03-env-tmpl/t1-0099-this.ref
  tests/functional/param_expand/03-env-tmpl/t1-0101-that.ref
  tests/functional/param_expand/03-env-tmpl/t1-0101-this.ref
  tests/functional/param_expand/03-env-tmpl/t2-0099-that.ref
  tests/functional/param_expand/03-env-tmpl/t2-0099-this.ref
  tests/functional/param_expand/03-env-tmpl/t2-0101-that.ref
  tests/functional/param_expand/03-env-tmpl/t2-0101-this.ref
Labels: bug

#4275 config: make --sparse the defalt
  cylc/flow/cfgspec/globalcfg.py
  cylc/flow/scripts/config.py
  tests/functional/cylc-cat-log/02-remote-custom-runtime-viewer-pbs.t
  tests/functional/cylc-clean/01-remote.t
  tests/functional/cylc-get-config/00-simple.t
  tests/functional/cylc-get-config/00-simple/flow.cylc
  tests/functional/cylc-get-site-config/00-basic.t
  tests/functional/cylc-get-site-config/01-defaults.t
  tests/functional/cylc-get-site-config/02-jinja2.t
  tests/functional/inheritance/00-namespace-list.t
  tests/functional/lib/bash/test_header
  tests/functional/param_expand/01-basic.t
  tests/functional/remote/01-file-install.t
  tests/functional/remote/04-symlink-dirs.t
  tests/functional/rnd/01-editors.t
  tests/functional/workflow-host-self-id/00-address.t
  tests/functional/workflow-state/00-polling.t
  tests/functional/workflow-state/01-polling.t
  tests/functional/workflow-state/polling/flow.cylc
  tests/functional/workflow-state/upstream/flow.cylc
Labels: small

#4272 Constrain window by final cycle point
  CHANGES.md
  cylc/flow/data_store_mgr.py
  tests/functional/graphql/01-workflow.t
  tests/functional/graphql/01-workflow/flow.cylc
  tests/functional/runahead/06-release-update.t
Labels: bug, small

#4238 Allow cylc hold to hold future tasks that haven't spawned yet
  CHANGES.md
  cylc/flow/config.py
  cylc/flow/data_store_mgr.py
  cylc/flow/rundb.py
  cylc/flow/scheduler.py
  cylc/flow/scripts/hold.py
  cylc/flow/scripts/release.py
  cylc/flow/task_pool.py
  cylc/flow/task_proxy.py
  cylc/flow/task_queues/__init__.py
  cylc/flow/task_queues/independent.py
  cylc/flow/workflow_db_mgr.py
  tests/flakyfunctional/database/00-simple/schema.out
  tests/functional/hold-release/17-hold-after-point/flow.cylc
  tests/functional/restart/22-hold.t
  tests/functional/restart/22-hold/flow.cylc
  tests/integration/conftest.py
  tests/integration/test_examples.py
  tests/integration/test_scheduler.py
  tests/integration/test_task_pool.py
  tests/unit/test_indep_task_queues.py
  tests/unit/test_task_pool.py
  tests/unit/test_task_proxy.py
Labels: sod-follow-up

#4281 update syntax highlighting to reflect latest changes in configs
  cylc/flow/etc/syntax/cylc.lang
  cylc/flow/etc/syntax/cylc.xml
Labels: small

#4280 Fix failure to show workflow status
  lib/cylc/review_dao.py
Labels: review, small

#4283 remove updated delta with pruned
  cylc/flow/data_store_mgr.py
Labels: small
