Repository cylc/cylc-flow, pull requests merged in 2021-09, with the labels that each got.

#4383 GH Actions: Add test workflows badges to release PRs
  .github/workflows/1_create_release_pr.yml
Labels: small, infrastructure

#4386 Fix mutation error when stopping workflow in UI
  cylc/flow/exceptions.py
  cylc/flow/network/resolvers.py
  cylc/flow/network/schema.py
  cylc/flow/scheduler.py
  cylc/flow/scripts/stop.py
  tests/unit/conftest.py
Labels: bug

#4395 ensure workflow tries to kill orphan tasks before shutting down
  CHANGES.md
  cylc/flow/task_pool.py
  tests/functional/shutdown/21-stop-kill.t
  tests/functional/shutdown/22-stop-now.t
Labels: bug

#4411 Add colour to GH Actions pytest log
  .github/workflows/test_fast.yml
Labels: small, infrastructure

#4404 graph line continuation on boolean
  CHANGES.md
  cylc/flow/graph_parser.py
  tests/unit/test_graph_parser.py
Labels: small, could-be-better

#4423 Restrict installation logging to workflow srcdir
  CHANGES.md
  cylc/flow/install_plugins/log_vc_info.py
  tests/functional/cylc-install/05-check-logs-git.t
  tests/functional/cylc-install/06-check-logs-svn.t
  tests/unit/post_install/test_log_vc_info.py
Labels: small

#4430 Update filenames in the `log` directory [small, but can be pushed to rc1 if it doens't make b3]
  CHANGES.md
  cylc/flow/scheduler.py
  cylc/flow/workflow_files.py
  tests/functional/startup/01-log-flow-config.t
Labels: small

#4437 prevent slow polling producing incorrect submit-fail
  lib/cylc/batch_sys_manager.py
Labels: bug
