Repository cylc/cylc-flow, pull requests merged in 2021-11, with the labels that each got.

#4490 change back compat reference for docs
  cylc/flow/cfgspec/workflow.py
Labels: small

#4489 Reduce flakiness of remote func tests on GH Actions
  etc/conf/global.cylc
  tests/functional/remote/06-poll.t
Labels: small, infrastructure

#4479 subscription async-gen yield coordination & delta clash fix
  cylc/flow/network/graphql.py
  cylc/flow/network/resolvers.py
  cylc/flow/network/schema.py
Labels: bug, efficiency

#4491 Remove yield delay on graphql subscription delta processing
  cylc/flow/network/resolvers.py
Labels: bug, efficiency

#4485 Preparing job status
  cylc/flow/data_store_mgr.py
  cylc/flow/task_events_mgr.py
  cylc/flow/task_job_mgr.py
  cylc/flow/tui/__init__.py
  tests/functional/remote/05-remote-init.t
  tests/functional/remote/05-remote-init/flow.cylc
  tests/integration/test_data_store_mgr.py
Labels: bug

#4473 Docs.review spec docs
  cylc/flow/cfgspec/README
  cylc/flow/cfgspec/globalcfg.py
  cylc/flow/cfgspec/workflow.py
  cylc/flow/main_loop/__init__.py
  cylc/flow/main_loop/reset_bad_hosts.py
  cylc/flow/network/schema.py
  cylc/flow/scripts/broadcast.py
  cylc/flow/scripts/ext_trigger.py
  cylc/flow/scripts/hold.py
  cylc/flow/scripts/poll.py
  cylc/flow/scripts/release.py
  cylc/flow/scripts/reload.py
  cylc/flow/scripts/remove.py
  cylc/flow/scripts/set_outputs.py
  cylc/flow/scripts/stop.py
  cylc/flow/task_job_mgr.py
Labels: doc

#4495 Fix shell style errors
  cylc/flow/etc/job.sh
  tests/flakyfunctional/job-submission/19-chatty.t
  tests/functional/remote/01-file-install.t
Labels: small

#4498 fix broken Cylc doc issue
  cylc/flow/cfgspec/globalcfg.py
Labels: bug, doc

#4470 graphql: use a common interface for added / updated deltas
  cylc/flow/network/schema.py
Labels: small

#4499 Change formating and info on no workflow mutation error
  cylc/flow/network/resolvers.py
Labels: small

#4497 Forbid case where both `suite.rc` and `flow.cylc` files are found in src/run dir
  cylc/flow/scripts/reinstall.py
  cylc/flow/workflow_files.py
  tests/functional/cylc-install/02-failures.t
  tests/functional/cylc-reinstall/02-failures.t
  tests/unit/test_workflow_files.py
Labels: bug?, small

#4504 actions: manylinux - bump the timeout
  .github/workflows/test_manylinux.yml
Labels: small

#4509 Fix changelog
  CHANGES.md
Labels: small

#4471 Separate Parsec ItemNotFoundError into two
  CHANGES.md
  cylc/flow/parsec/config.py
  cylc/flow/parsec/exceptions.py
  tests/functional/cylc-get-config/08-item-not-found.t
  tests/unit/parsec/test_config.py
Labels: small, could-be-better

#4518 actually load contact info before sending a task message.
  lib/cylc/network/httpclient.py
Labels: bug, small

#4537 Turn off broken flake8-bugbear rule B018 (for now)
  tox.ini
Labels: small, infrastructure

#4538 Revert flake8-bugbear B018 ignore
  .github/PULL_REQUEST_TEMPLATE.md
  tox.ini
Labels: small, infrastructure
