Repository cylc/cylc-flow, pull requests merged in 2021-02, with the labels that each got.

#4050 Fix Remote Tidy
  cylc/flow/platforms.py
  cylc/flow/task_remote_cmd.py
  cylc/flow/task_remote_mgr.py
  tests/functional/cylc-ping/04-check-keys-remote.t
  tests/unit/test_platforms.py
Labels: bug

#4023 Cli setting of rose opts
  CHANGES.md
  cylc/flow/scripts/install.py
  tests/functional/cylc-clean/00-basic.t
  tests/functional/cylc-install/03-file-transfer.t
Labels: rose-suite-run

#4059 Fix remote init bug
  cylc/flow/platforms.py
  cylc/flow/scheduler.py
  cylc/flow/scripts/remote_init.py
  cylc/flow/task_remote_mgr.py
  tests/unit/test_task_remote_mgr.py
Labels: bug, small

#4063 run: fix un-installed flows
  cylc/flow/scheduler.py
  tests/functional/cylc-run/04-no-install.t
Labels: bug

#4061 mypy
  .github/workflows/test_fast.yml
  cylc/flow/c3mro.py
  cylc/flow/context_node.py
  cylc/flow/data_messages.proto
  cylc/flow/data_messages_pb2.py
  cylc/flow/job_runner_mgr.py
  cylc/flow/network/graphql.py
  cylc/flow/network/schema.py
  cylc/flow/network/subscriber.py
  cylc/flow/parsec/validate.py
  cylc/flow/scheduler.py
  cylc/flow/scripts/cylc.py
  cylc/flow/scripts/restart.py
  cylc/flow/scripts/run.py
  cylc/flow/subprocpool.py
  cylc/flow/suite_files.py
  cylc/flow/unicode_rules.py
  cylc/flow/xtrigger_mgr.py
  mypy.ini
  setup.py
Labels: small

#4067 Removed Cylc-Rose functional tests from this repository.
  tests/functional/rose-conf/00-jinja2.t
  tests/functional/rose-conf/00-jinja2/flow.cylc
  tests/functional/rose-conf/00-jinja2/processed.conf.control
  tests/functional/rose-conf/00-jinja2/rose-suite.conf
  tests/functional/rose-conf/01-empy.t
  tests/functional/rose-conf/01-empy/flow.cylc
  tests/functional/rose-conf/01-empy/processed.conf.control
  tests/functional/rose-conf/01-empy/rose-suite.conf
  tests/functional/rose-conf/02-env.t
  tests/functional/rose-conf/02-env/flow.cylc
  tests/functional/rose-conf/02-env/rose-suite.conf
  tests/functional/rose-conf/03-fileinstall.t
  tests/functional/rose-conf/03-fileinstall/flow.cylc
  tests/functional/rose-conf/03-fileinstall/rose-suite.conf
  tests/functional/rose-conf/04-opts-set-from-env.t
  tests/functional/rose-conf/04-opts-set-from-env/flow.cylc
  tests/functional/rose-conf/04-opts-set-from-env/opt/rose-suite-Cymraeg.conf
  tests/functional/rose-conf/04-opts-set-from-env/opt/rose-suite-Gaelige.conf
  tests/functional/rose-conf/04-opts-set-from-env/processed.conf.control
  tests/functional/rose-conf/04-opts-set-from-env/rose-suite.conf
  tests/functional/rose-conf/05-opts-set-from-rose-suite.conf.t
  tests/functional/rose-conf/05-opts-set-from-rose-suite.conf/flow.cylc
  tests/functional/rose-conf/05-opts-set-from-rose-suite.conf/opt/rose-suite-Cymraeg.conf
  tests/functional/rose-conf/05-opts-set-from-rose-suite.conf/opt/rose-suite-Gaelige.conf
  tests/functional/rose-conf/05-opts-set-from-rose-suite.conf/processed.conf.control
  tests/functional/rose-conf/05-opts-set-from-rose-suite.conf/rose-suite.conf
  tests/functional/rose-conf/06-jinja2.thorough.t
  tests/functional/rose-conf/06-jinja2.thorough/flow.cylc
  tests/functional/rose-conf/06-jinja2.thorough/processed.conf.control
  tests/functional/rose-conf/06-jinja2.thorough/rose-suite.conf
  tests/functional/rose-conf/07-cli-override.t
  tests/functional/rose-conf/07-cli-override/flow.cylc
  tests/functional/rose-conf/07-cli-override/rose-suite.conf
  tests/functional/rose-conf/08-template-engine-conflict.t
  tests/functional/rose-conf/08-template-engine-conflict/flow.cylc
  tests/functional/rose-conf/08-template-engine-conflict/rose-suite.conf
  tests/functional/rose-conf/fileinstall_data/lion.py
  tests/functional/rose-conf/fileinstall_data/randoms1.data
  tests/functional/rose-conf/fileinstall_data/randoms3.data
  tests/functional/rose-conf/test_header
Labels: could-be-better

#4065 Fix and tidy functional tests
  tests/functional/lib/bash/test_header
  tests/functional/platforms/02-host-to-platform-upgrade.t
  tests/functional/platforms/02-host-to-platform-upgrade/flow.cylc
  tests/functional/remote/03-polled-task-started.t
  tests/functional/remote/03-polled-task-started/flow.cylc
Labels: small

#4072 Fix install error on sod test
  tests/functional/spawn-on-demand/08-lost-parents.t
Labels: small

#4066 cfg: document recurrence graph addition in config
  cylc/flow/cfgspec/suite.py
Labels: doc, small

#4075 Added an explanation on the reference docs for Cylc7 legacy host/remo…
  cylc/flow/cfgspec/suite.py
Labels: doc

#4079 actions: set fetch-depth: 2 to make codecov happy
  .github/workflows/test_fast.yml
  .github/workflows/test_functional.yml
Labels: small

#4071 Cylc Reinstall
  CHANGES.md
  cylc/flow/etc/cylc-bash-completion
  cylc/flow/scheduler.py
  cylc/flow/scripts/reinstall.py
  cylc/flow/suite_files.py
  setup.cfg
  tests/functional/cylc-install/00-simple.t
  tests/functional/cylc-install/01-symlinks.t
  tests/functional/cylc-install/02-failures.t
  tests/functional/cylc-install/03-file-transfer.t
  tests/functional/cylc-reinstall/00-simple.t
  tests/functional/cylc-reinstall/01-file-transfer.t
  tests/functional/cylc-reinstall/02-failures.t
  tests/functional/cylc-reinstall/test_header
  tests/functional/lib/bash/test_header
  tests/unit/test_suite_files.py
Labels: rose-suite-run

#4089 Tidy tests
  etc/bin/run-functional-tests
  tests/functional/cylc-ping/05-check-keys-sharedfs.t
Labels: small

#4096 Remove whiches
  tests/functional/cli/01-help.t
  tests/functional/job-submission/18-clean-env.t
Labels: small

#4100 GH Actions: Increase functional test timeout
  .github/workflows/test_functional.yml
Labels: small
