Repository cylc/cylc-flow, pull requests merged in 2021-04, with the labels that each got.

#4159 conf: document run host rankings
  cylc/flow/cfgspec/globalcfg.py
Labels: doc

#4169 Fixed platforms subsequent cycles on localhost.
  CHANGES.md
  cylc/flow/platforms.py
  tests/functional/platforms/02-host-to-platform-upgrade.t
  tests/functional/platforms/02-host-to-platform-upgrade/flow.cylc
  tests/functional/platforms/02-host-to-platform-upgrade/reference.log
Labels: bug, platforms-follow-up

#4168 Improve error handling if exception occurs during shutdown
  CHANGES.md
  cylc/flow/exceptions.py
  cylc/flow/platforms.py
  cylc/flow/scheduler.py
  tests/integration/conftest.py
  tests/integration/test_scheduler.py
  tests/integration/utils/flow_tools.py
  tests/unit/test_exceptions.py
Labels: bug

#4161 Fix workflow source name determination.
  cylc/flow/suite_files.py
Labels: bug, small

#4188 Fix cylc install help examples
  CHANGES.md
  cylc/flow/scripts/install.py
Labels: bug, doc, small

#4190 Remove center deprecated tag in README
  README.md
Labels: small

#4192 8.0b1 -> 8.0b2.dev
  CHANGES.md
  cylc/flow/__init__.py
Labels: small

#4182 catch unclosed multi-line strings
  cylc/flow/parsec/exceptions.py
  cylc/flow/parsec/fileparse.py
  tests/unit/parsec/test_fileparse.py
Labels: small

#4177 Remove configurable run/work dir from global config
  CHANGES.md
  cylc/flow/cfgspec/globalcfg.py
  cylc/flow/cfgspec/suite.py
  cylc/flow/dbstatecheck.py
  cylc/flow/etc/job.sh
  cylc/flow/etc/syntax/cylc.lang
  cylc/flow/etc/syntax/cylc.xml
  cylc/flow/job_file.py
  cylc/flow/pathutil.py
  cylc/flow/scripts/cat_log.py
  cylc/flow/scripts/diff.py
  cylc/flow/scripts/suite_state.py
  cylc/flow/task_events_mgr.py
  cylc/flow/task_job_mgr.py
  cylc/flow/task_remote_mgr.py
  cylc/flow/xtriggers/suite_state.py
  tests/flakyfunctional/cyclers/19-async_integer.t
  tests/functional/cylc-get-site-config/04-homeless.t
  tests/functional/suite-state/04-template.t
  tests/functional/suite-state/template/flow.cylc
  tests/functional/suite-state/template/reference.log
  tests/integration/conftest.py
  tests/integration/utils/__init__.py
  tests/integration/utils/test_utils.py
  tests/unit/conftest.py
  tests/unit/test_job_file.py
  tests/unit/test_pathutil.py
  tests/unit/test_suite_files.py
Labels: config change

#4198 Terminology: suite to workflow follow-up
  cylc/flow/etc/job.sh
  cylc/flow/scripts/install.py
  cylc/flow/scripts/reinstall.py
Labels: small

#4199 config: validate [runtime] task names
  CHANGES.md
  cylc/flow/config.py
  cylc/flow/scripts/validate.py
  cylc/flow/task_id.py
  cylc/flow/unicode_rules.py
  tests/integration/test_config.py
Labels: bug, small

#4200 Pluralise rose_template_vars
  cylc/flow/scripts/install.py
  cylc/flow/scripts/reinstall.py
Labels: small
