Repository cylc/cylc-flow, pull requests merged in 2021-03, with the labels that each got.

#4101 Cylc reinstall `--clear-rose-install-options`
  cylc/flow/scripts/reinstall.py
Labels: small

#4095 Replace string literals of localhost with function returning config
  cylc/flow/pathutil.py
  cylc/flow/platforms.py
  cylc/flow/suite_files.py
  cylc/flow/task_job_mgr.py
  cylc/flow/task_remote_mgr.py
  tests/unit/test_platforms_get_platform.py
Labels: small

#4105 conf: cylc executable => cylc path
  cylc/flow/cfgspec/globalcfg.py
  cylc/flow/job_file.py
  cylc/flow/remote.py
  tests/functional/job-submission/18-clean-env.t
  tests/functional/jobscript/00-torture.t
  tests/unit/test_job_file.py
Labels: doc

#4111 tests: prepare for ssh task comms
  .github/workflows/test_functional.yml
  etc/bin/swarm
  etc/conf/global.cylc
  etc/conf/ssh_config
  tests/functional/README.md
  tests/functional/cylc-message/01-newline.t
  tests/functional/cylc-message/01-newline/flow.cylc
  tests/functional/cylc-message/02-multi.t
  tests/functional/cylc-message/02-multi/flow.cylc
  tests/functional/lib/bash/test_header
  tests/functional/remote/01-file-install.t
  tests/functional/remote/02-install-target.t
Labels: doc

#4125 doc: improve main-loop docs
  cylc/flow/main_loop/auto_restart.py
Labels: doc, small

#4130 tui: apply natural sorting to tasks and cycles
  cylc/flow/tui/util.py
Labels: small

#4138 Make remote init return messages more informative
  cylc/flow/platforms.py
  cylc/flow/scheduler_cli.py
  cylc/flow/task_remote_cmd.py
  tests/unit/test_task_remote_cmd.py
Labels: small

#4134 Allow Cylc Review to access Cylc 8 Workflow data.
  CHANGES.md
  lib/cylc/review.py
  lib/cylc/review_dao.py
Labels: small

#4132 Configurable source dirs
  CHANGES.md
  cylc/flow/cfgspec/globalcfg.py
  cylc/flow/job_runner_handlers/slurm.py
  cylc/flow/network/scan.py
  cylc/flow/pathutil.py
  cylc/flow/scripts/cat_log.py
  cylc/flow/scripts/install.py
  cylc/flow/scripts/reinstall.py
  cylc/flow/scripts/suite_state.py
  cylc/flow/suite_files.py
  cylc/flow/xtriggers/suite_state.py
  tests/functional/cylc-install/00-simple.t
  tests/functional/cylc-install/02-failures.t
  tests/functional/cylc-install/03-file-transfer.t
  tests/functional/cylc-reinstall/00-simple.t
  tests/functional/cylc-reinstall/01-file-transfer.t
  tests/unit/test_pathutil.py
  tests/unit/test_suite_files.py
Labels: config change

#4139 Remove queued/held delta filter
  cylc/flow/data_store_mgr.py
Labels: bug

#4144 Cli dead ends
  cylc/flow/etc/cylc-bash-completion
  cylc/flow/etc/syntax/cylc.lang
  cylc/flow/etc/syntax/cylc.xml
  cylc/flow/scripts/cylc.py
  tests/functional/cli/01-help.t
  tests/functional/cylc-get-config/00-simple.t
  tests/functional/cylc-get-config/00-simple/flow.cylc
  tests/functional/cylc-get-config/01-no-final.t
  tests/functional/cylc-get-config/02-cycling.t
  tests/functional/cylc-get-config/03-icp.t
  tests/functional/cylc-get-config/05-param-vars.t
  tests/functional/cylc-get-config/06-compat.t
  tests/functional/cylc-get-site-config/00-basic.t
  tests/functional/env-filter/00-filter.t
  tests/functional/inheritance/00-namespace-list.t
  tests/functional/param_expand/01-basic.t
  tests/functional/repeated-items/00-one.t
  tests/functional/suite-state/00-polling.t
  tests/functional/suite-state/01-polling.t
Labels: small

#4146 platform upgrader inheritance bug
  cylc/flow/cfgspec/suite.py
  cylc/flow/task_job_mgr.py
  tests/functional/deprecations/01-cylc8-basic/validation.stderr
  tests/functional/platforms/02-host-to-platform-upgrade.t
  tests/functional/platforms/02-host-to-platform-upgrade/flow.cylc
  tests/functional/platforms/02-host-to-platform-upgrade/reference.log
Labels: bug

#4029 Edit documentation links/badges in README
  INSTALL.md
  README.md
Labels: small

#4152 Docstring changes
  cylc/flow/cfgspec/suite.py
  cylc/flow/platforms.py
  tests/unit/test_platforms_get_platform.py
Labels: doc, small
