Repository cylc/cylc-flow, pull requests merged in 2021-01, with the labels that each got.

#4016 cfgspec: fix doc issues
  cylc/flow/cfgspec/globalcfg.py
  cylc/flow/cfgspec/suite.py
Labels: doc

#4022 GH Actions: Prevent update_copyright workflow running on forks
  .github/workflows/update_copyright.yml
Labels: small

#4027 Fix database platforms bug
  cylc/flow/task_job_mgr.py
  tests/functional/platforms/03-platform-db.t
  tests/functional/platforms/03-platform-db/flow.cylc
Labels: bug

#4028 actions: run tests on macos
  .github/workflows/test_fast.yml
  .github/workflows/test_functional.yml
  etc/conf/macos-patch
Labels: small

#4026 Fix OrderedDictWithDefault comparison mistake
  cylc/flow/platforms.py
  tests/unit/test_platforms.py
Labels: platforms-follow-up

#4011 Fix trailing slash in reg (workflow name) bug
  CHANGES.md
  cylc/flow/scheduler_cli.py
  cylc/flow/scripts/broadcast.py
  cylc/flow/scripts/ext_trigger.py
  cylc/flow/scripts/hold.py
  cylc/flow/scripts/kill.py
  cylc/flow/scripts/poll.py
  cylc/flow/scripts/release.py
  cylc/flow/scripts/reload.py
  cylc/flow/scripts/remove.py
  cylc/flow/scripts/set_outputs.py
  cylc/flow/scripts/set_verbosity.py
  cylc/flow/scripts/stop.py
  cylc/flow/scripts/trigger.py
  cylc/flow/task_message.py
Labels: bug, small

#3938 Event driven data-store deltas
  cylc/flow/broadcast_mgr.py
  cylc/flow/data_messages.proto
  cylc/flow/data_messages_pb2.py
  cylc/flow/data_store_mgr.py
  cylc/flow/job_pool.py
  cylc/flow/network/resolvers.py
  cylc/flow/network/schema.py
  cylc/flow/rundb.py
  cylc/flow/scheduler.py
  cylc/flow/scripts/dump.py
  cylc/flow/scripts/show.py
  cylc/flow/task_events_mgr.py
  cylc/flow/task_job_mgr.py
  cylc/flow/task_outputs.py
  cylc/flow/task_pool.py
  cylc/flow/task_proxy.py
  cylc/flow/xtrigger_mgr.py
  tests/flakyfunctional/cylc-show/00-simple.t
  tests/functional/cylc-show/01-clock-triggered.t
  tests/functional/cylc-show/03-clock-triggered-non-utc-mode.t
  tests/functional/cylc-subscribe/01-subscribe.t
  tests/functional/graphql/01-workflow.t
  tests/functional/graphql/03-is-held-arg/flow.cylc
  tests/functional/runahead/06-release-update.t
  tests/functional/xtriggers/03-sequence.t
  tests/integration/test_data_store_mgr.py
  tests/integration/test_job_pool.py
  tests/unit/test_data_store_mgr.py
  tests/unit/test_xtrigger_mgr.py
Labels: efficiency, sod-follow-up

#4038 Fix some functional tests that don't run on GH Actions
  tests/functional/restart/41-auto-restart-local-jobs.t
  tests/functional/restart/42-auto-restart-ping-pong.t
  tests/functional/restart/43-auto-restart-force-override-normal.t
Labels: small

#4041 Platforms.fix generic items match
  cylc/flow/platforms.py
  tests/unit/test_platforms.py
Labels: platforms-follow-up, small

#4031 Fix remote init by platform
  cylc/flow/task_job_mgr.py
  tests/functional/remote/01-file-install.t
  tests/functional/remote/05-remote-init.t
  tests/functional/remote/05-remote-init/flow.cylc
Labels: bug

#4048 tui: update help for MacOS
  cylc/flow/tui/overlay.py
Labels: doc, small

#4046 Shutdown: remove contact file after closing DB connection
  CHANGES.md
  cylc/flow/scheduler.py
  tests/flakyfunctional/shutdown/00-rm-db.t
Labels: bug?, small
