Repository cylc/cylc-flow, pull requests merged in 2021-07, with the labels that each got.

#4290 suggested updates to the workflow config docs
  cylc/flow/cfgspec/globalcfg.py
  cylc/flow/cfgspec/workflow.py
Labels: doc

#4292 scan: workflow_params
  cylc/flow/network/scan.py
  tests/integration/test_scan.py
Labels: small

#4304 mypy: allow redefinition
  cylc/flow/c3mro.py
  mypy.ini
Labels: question, small

#4303 Added check for templating language setting
  cylc/flow/parsec/fileparse.py
Labels: could-be-better, rose-suite-run, small

#4293 cylc-rose: `cylc list` compatibility
  cylc/flow/scripts/config.py
  cylc/flow/scripts/graph.py
  cylc/flow/scripts/install.py
  cylc/flow/scripts/list.py
  cylc/flow/scripts/validate.py
  cylc/flow/templatevars.py
  tests/unit/test_templatevars.py
Labels: rose-suite-run

#4295 Fix global.cylc extension in comment
  cylc/flow/job_runner_handlers/pbs.py
Labels: small

#4286 scan: show uninstalled workflows
  CHANGES.md
  cylc/flow/async_util.py
  cylc/flow/network/scan.py
  cylc/flow/scripts/scan.py
  tests/conftest.py
  tests/integration/test_scan.py
  tests/unit/conftest.py
Labels: small

#4250 Symlink dirs cli
  CHANGES.md
  cylc/flow/cfgspec/globalcfg.py
  cylc/flow/cfgspec/workflow.py
  cylc/flow/pathutil.py
  cylc/flow/scripts/install.py
  cylc/flow/workflow_files.py
  tests/functional/cylc-clean/00-basic.t
  tests/functional/cylc-clean/01-remote.t
  tests/functional/cylc-clean/02-targeted.t
  tests/functional/cylc-get-site-config/04-homeless.t
  tests/functional/cylc-install/01-symlinks.t
  tests/functional/remote/04-symlink-dirs.t
  tests/unit/conftest.py
  tests/unit/test_pathutil.py
  tests/unit/test_workflow_files.py
Labels: rose-suite-run

#4312 Log failure where attempting to use Cylc 8 on installed Cylc 7 workflow.
  cylc/flow/exceptions.py
  cylc/flow/network/__init__.py
  tests/unit/network/test__init__.py
Labels: could-be-better, small

#4184 Intelligent Host Select.
  cylc/flow/cfgspec/globalcfg.py
  cylc/flow/exceptions.py
  cylc/flow/main_loop/reset_bad_hosts.py
  cylc/flow/platforms.py
  cylc/flow/remote.py
  cylc/flow/scheduler.py
  cylc/flow/scripts/cat_log.py
  cylc/flow/scripts/check_versions.py
  cylc/flow/subprocctx.py
  cylc/flow/subprocpool.py
  cylc/flow/task_events_mgr.py
  cylc/flow/task_job_mgr.py
  cylc/flow/task_remote_mgr.py
  cylc/flow/workflow_events.py
  cylc/flow/workflow_files.py
  cylc/flow/xtrigger_mgr.py
  setup.cfg
  tests/functional/events/34-task-abort/flow.cylc
  tests/functional/intelligent-host-selection/00-mixedhost.t
  tests/functional/intelligent-host-selection/00-mixedhost/flow.cylc
  tests/functional/intelligent-host-selection/01-periodic-clear-badhosts.t
  tests/functional/intelligent-host-selection/01-periodic-clear-badhosts/flow.cylc
  tests/functional/intelligent-host-selection/02-badhosts.t
  tests/functional/intelligent-host-selection/02-badhosts/flow.cylc
  tests/functional/intelligent-host-selection/03-polling.t
  tests/functional/intelligent-host-selection/03-polling/flow.cylc
  tests/functional/intelligent-host-selection/04-kill.t
  tests/functional/intelligent-host-selection/04-kill/flow.cylc
  tests/functional/intelligent-host-selection/test_header
  tests/functional/job-submission/06-garbage/flow.cylc
  tests/functional/lib/bash/test_header
  tests/integration/test_scan.py
  tests/unit/test_platforms_get_host.py
  tests/unit/test_remote.py
  tests/unit/test_subprocpool.py
  tests/unit/test_task_events_mgr.py
  tests/unit/test_task_events_mgr_2.py
  tests/unit/test_task_remote_mgr.py
  tests/unit/test_workflow_files.py
Labels: intelligent-host-selection, platforms-follow-up

#4325 mailmap: associate dangling bot commit with github-actions[bot] account
  .mailmap
  CONTRIBUTING.md
Labels: small
