Repository cylc/cylc-flow, pull requests merged in 2021-08, with the labels that each got.

#4330 conda: remove unused deps
  conda-environment.yml
Labels: small

#4340 conda: match conda deps to pypi ones
  conda-environment.yml
Labels: small

#4308 job_runner_mgr: make paths in directives relative to ~
  cylc/flow/job_runner_handlers/loadleveler.py
  cylc/flow/job_runner_handlers/lsf.py
  cylc/flow/job_runner_handlers/moab.py
  cylc/flow/job_runner_handlers/pbs.py
  cylc/flow/job_runner_handlers/sge.py
  cylc/flow/job_runner_handlers/slurm.py
  cylc/flow/job_runner_mgr.py
  tests/unit/job_runner_handlers/test_loadleveler.py
  tests/unit/job_runner_handlers/test_lsf.py
  tests/unit/job_runner_handlers/test_moab.py
  tests/unit/job_runner_handlers/test_pbs.py
  tests/unit/job_runner_handlers/test_slurm.py
  tests/unit/job_runner_handlers/test_slurm_packjob.py
Labels: bug

#4352 make review-timings work with Cylc 8
  cylc/flow/scripts/report_timings.py
Labels: bug, small

#4346 scan: use natural sort order with --sort opt
  CHANGES.md
  cylc/flow/scripts/scan.py
  cylc/flow/util.py
Labels: small

#4348 Fix coverage
  .coveragerc
  .github/workflows/bash.yml
  .github/workflows/test_fast.yml
  .github/workflows/test_functional.yml
Labels: small

#4355 Remove workflow owner
  CHANGES.md
  cylc/flow/option_parsers.py
Labels: small

#4302 have scheduler warn if stopcp > finalcp
  cylc/flow/scheduler.py
  tests/functional/cylc-play/06-warnif-scp-after-fcp.t
Labels: small, could-be-better

#4347 Do not skip bad site config; raise instead
  cylc/flow/cfgspec/globalcfg.py
Labels: small, could-be-better

#4360 allow failure to set templating engine _anywhere_ to pass quietly.
  cylc/flow/parsec/fileparse.py
Labels: bug

#4362 remove runN if symlink target is gone
  CHANGES.md
  cylc/flow/workflow_files.py
  tests/unit/test_workflow_files.py
Labels: could-be-better

#4364 Attempt to fix unit test flakiness on Python 3.7
  .github/workflows/bash.yml
  .github/workflows/test_functional.yml
  tests/unit/test_workflow_files.py
Labels: small

#4353 Remove log messages for template variables unchanged by plugin
  cylc/flow/parsec/fileparse.py
  cylc/flow/templatevars.py
  tests/unit/parsec/test_fileparse.py
  tests/unit/test_templatevars.py
Labels: bug

#4370 test for symlinks to being chased
  tests/functional/cylc-install/04-symlinks-not-resolved.t
Labels: could-be-better

#4371 Tidy globalcfg
  cylc/flow/cfgspec/globalcfg.py
Labels: small, doc

#4350 Commented out line in cylc report-timings causing flaky behaviour.
  bin/cylc-report-timings
Labels: bug?, small

#4377 Fix test
  tests/functional/cylc-install/02-failures.t
Labels: small

#4381 Add `versionchanged` admonitions to certain config items
  cylc/flow/cfgspec/globalcfg.py
  cylc/flow/cfgspec/workflow.py
Labels: small, doc

#4384 Remove Task Mail section
  cylc/flow/cfgspec/globalcfg.py
  cylc/flow/task_events_mgr.py
Labels: small, could-be-better, config change

#4379 Codecov: carry forward previous reports
  .codecov.yml
  .github/workflows/test_fast.yml
  .github/workflows/test_functional.yml
Labels: small, infrastructure

#4331 Jupyter server
  cylc/flow/network/schema.py
  cylc/flow/scheduler.py
  cylc/flow/scripts/cylc.py
Labels: small

#4382 Improvements to documentation of platforms
  cylc/flow/cfgspec/globalcfg.py
  cylc/flow/cfgspec/workflow.py
Labels: small, doc, could-be-better
