Repository cylc/cylc-flow, pull requests merged in 2021-10, with the labels that each got.

#4441 `parse_reg()`: Avoid unnecessary reg clash messages
  cylc/flow/workflow_files.py
  tests/unit/test_workflow_files.py
Labels: small, could-be-better

#4447 actions: bump manylinux to the oldest ubuntu available
  .github/workflows/test_manylinux.yml
  setup.py
Labels: infrastructure

#4449 Fix broken tests
  .coveragerc
Labels: bug?

#4444 Cylc review show any *.cylc file with synatax highlighting
  lib/cylc/review.py
Labels: small, could-be-better

#4405 Bandit
  .bandit
  .github/workflows/test_fast.yml
  cylc/flow/dbstatecheck.py
  cylc/flow/install_plugins/log_vc_info.py
  cylc/flow/job_file.py
  cylc/flow/job_runner_handlers/background.py
  cylc/flow/parsec/validate.py
  cylc/flow/platforms.py
  cylc/flow/prerequisite.py
  cylc/flow/remote.py
  cylc/flow/rundb.py
  cylc/flow/scheduler.py
  cylc/flow/scripts/cat_log.py
  cylc/flow/scripts/graph.py
  cylc/flow/scripts/view.py
  cylc/flow/task_events_mgr.py
  cylc/flow/task_remote_mgr.py
  cylc/flow/workflow_db_mgr.py
  cylc/flow/workflow_events.py
  cylc/flow/workflow_files.py
  setup.py
Labels: small, security

#4452 Remove "directory created" debug messages on workflow restart
  cylc/flow/pathutil.py
Labels: small, could-be-better

#4482 Task "preparing" state bug fixes
  cylc/flow/data_store_mgr.py
  cylc/flow/task_job_mgr.py
  cylc/flow/tui/__init__.py
  cylc/flow/tui/app.py
Labels: bug, small
