Repository cylc/cylc-flow, pull requests merged in 2022-01, with the labels that each got.

#4571 Fix start type log formatting
  cylc/flow/scheduler.py
Labels: small

#4425 Remove Conda Activate from Wrapper Scipt
  .github/workflows/test_conda-build.yml
  cylc/flow/etc/cylc
  cylc/flow/scripts/cat_log.py
Labels: could-be-better

#4572 Add link to migration guide in implicit tasks warning
  cylc/flow/config.py
  tests/functional/validate/37-special-implicit-task.t
Labels: small

#4573 Update usage text
  bin/cylc-broadcast
  bin/cylc-cat-state
  bin/cylc-diff
  bin/cylc-get-directory
  bin/cylc-gscan
  bin/cylc-gui
  bin/cylc-insert
  bin/cylc-jobs-kill
  bin/cylc-jobs-poll
  bin/cylc-jobs-submit
  bin/cylc-print
  bin/cylc-report-timings
  bin/cylc-scan
  bin/cylc-suite-state
Labels: small

#4574 Take suggestions from flake8 simplify
  cylc/flow/config.py
  cylc/flow/network/graphql.py
  cylc/flow/parsec/util.py
  cylc/flow/scripts/cycle_point.py
  tests/unit/network/test_graphql.py
Labels: small, could-be-better

#4556 Fix remote psutil invocation.
  CHANGES.md
  cylc/flow/workflow_files.py
Labels: bug

#4558 added metadata section to platforms and platform groups config
  CHANGES.md
  cylc/flow/cfgspec/globalcfg.py
Labels: small

#4570 Fix host selection bug for deprecated `[runtime][<task>][remote]host` syntax
  CHANGES.md
  cylc/flow/platforms.py
  cylc/flow/task_job_mgr.py
  tests/functional/intelligent-host-selection/07-cylc7-badhost.t
Labels: bug, intelligent-host-selection

#4591 Fix test failing due to expected task failures not using UID.
  tests/functional/directives/slurm/flow.cylc
Labels: question

#4596 Use new mode option in pytest-asyncio 0.17
  pytest.ini
  setup.cfg
  tests/integration/graphql/test_root.py
  tests/integration/test_async_util.py
  tests/integration/test_client.py
  tests/integration/test_data_store_mgr.py
  tests/integration/test_examples.py
  tests/integration/test_graphql.py
  tests/integration/test_id_cli.py
  tests/integration/test_publisher.py
  tests/integration/test_resolvers.py
  tests/integration/test_scan.py
  tests/integration/test_scan_api.py
  tests/integration/test_scheduler.py
  tests/integration/test_server.py
  tests/integration/test_task_pool.py
  tests/integration/test_workflow_files.py
  tests/integration/utils/test_utils.py
  tests/unit/network/test_scan_nt.py
  tests/unit/scripts/test_clean.py
  tests/unit/test_async_util.py
  tests/unit/test_id_cli.py
  tests/unit/test_workflow_files.py
Labels: small, infrastructure

#4600 Limit when tutorial workflow test runs for PRs
  .github/workflows/test_tutorial_workflow.yml
Labels: small, infrastructure

#4589 tutorial: fix flaky tests
  cylc/flow/etc/tutorial/cylc-forecasting-workflow/.validate
  cylc/flow/etc/tutorial/runtime-introduction/.validate
Labels: small

#4605 graph: fix cylc graph output
  cylc/flow/scripts/graph.py
Labels: bug

#4602 cli: update dead end commands
  cylc/flow/scripts/cylc.py
Labels: small, doc

#4590 Fix ordering of good hosts
  cylc/flow/platforms.py
  cylc/flow/scheduler.py
  cylc/flow/task_job_mgr.py
Labels: bug

#4607 graph: make workflow_id a required argument
  cylc/flow/scripts/graph.py
Labels: small

#4568 Tweak terminal colour handling.
  CHANGES.md
  cylc/flow/option_parsers.py
  cylc/flow/scripts/cylc.py
  cylc/flow/scripts/play.py
  cylc/flow/terminal.py
  tests/functional/cli/05-colour.t
  tests/unit/test_option_parsers.py
Labels: bug

#4606 cli: add option for viewing the license file
  cylc/flow/scheduler_cli.py
  cylc/flow/scripts/cylc.py
  tests/functional/rnd/04-conditions.t
Labels: small

#4592 validate: move seqence bounds validation into the config
  cylc/flow/config.py
  cylc/flow/scripts/validate.py
Labels: small

#4597 uid: make task match warning explicit
  cylc/flow/task_pool.py
  tests/integration/test_task_pool.py
Labels: small

#4610 Don't track coverage for `cylc/flow/etc/`
  .coveragerc
Labels: small, infrastructure

#4595 add async request to ssh client
  conda-environment.yml
  cylc/flow/network/ssh_client.py
  setup.cfg
Labels: bug

#4614 GH Actions: allow debug of tutorial workflow tests in event of timeout
  .github/workflows/test_tutorial_workflow.yml
Labels: small, infrastructure

#4580 added cylc get-resources --tutorials
  cylc/flow/resources.py
  cylc/flow/scheduler.py
  cylc/flow/scripts/get_resources.py
  cylc/flow/task_remote_cmd.py
  pytest.ini
  tests/unit/test_resources.py
Labels: tutorial-workflows

#4576 Cylc config add `--platform-names`
  CHANGES.md
  cylc/flow/cfgspec/globalcfg.py
  cylc/flow/scripts/config.py
  tests/functional/cylc-config/00-simple.t
  tests/functional/cylc-config/00-simple/flow.cylc
  tests/functional/cylc-config/00-simple/section1.stdout
  tests/functional/cylc-config/00-simple/section2.stdout
  tests/functional/cylc-config/01-no-final.t
  tests/functional/cylc-config/01-no-final/flow.cylc
  tests/functional/cylc-config/02-cycling.t
  tests/functional/cylc-config/02-cycling/flow.cylc
  tests/functional/cylc-config/03-icp.t
  tests/functional/cylc-config/05-param-vars.t
  tests/functional/cylc-config/05-param-vars/flow.cylc
  tests/functional/cylc-config/06-compat.t
  tests/functional/cylc-config/07-failif-item-in-platforms-and-groups.t
  tests/functional/cylc-config/08-item-not-found.t
  tests/functional/cylc-config/09-platforms.t
  tests/functional/cylc-config/test_header
  tests/unit/cfgspec/test_globalcfg.py
  tests/unit/scripts/test_config.py
Labels: small

#4624 get-resources: add api-key option
  cylc/flow/resources.py
Labels: small, tutorial-workflows

#4622 trigger: don't warn if task not already in the pool
  cylc/flow/id_match.py
  cylc/flow/task_pool.py
Labels: small, could be better
