Repository cylc/cylc-flow, pull requests merged in 2022-09, with the labels that each got.

#5110 Fix repeated stall when reloading a stalled workflow
  CHANGES.md
  cylc/flow/cycling/__init__.py
  cylc/flow/scheduler.py
  cylc/flow/task_pool.py
  cylc/flow/task_state.py
  tests/functional/reload/26-stalled.t
Labels: bug

#5119 Fix deprecation warning format.
  CHANGES.md
  cylc/flow/cfgspec/workflow.py
  cylc/flow/parsec/upgrade.py
  tests/functional/deprecations/00-pre-cylc8.t
  tests/functional/deprecations/01-cylc8-basic/validation.stderr
  tests/unit/parsec/test_upgrade.py
  tests/unit/scripts/test_lint.py
Labels: bug?, could be better

#5111 Fix assorted cylc review bugs
  lib/cylc/review.py
  lib/cylc/review_dao.py
Labels: bug

#5114 Revert order of scheduler `configure()` & `log_start()`
  CHANGES.md
  cylc/flow/loggingutil.py
  cylc/flow/scheduler.py
  tests/functional/logging/05-validation-detach.t
Labels: bug

#5098 Ensure queued deltas are published before shutdown
  CHANGES.md
  cylc/flow/network/publisher.py
  cylc/flow/network/replier.py
  cylc/flow/network/server.py
  cylc/flow/scheduler.py
  tests/integration/test_server.py
  tests/integration/test_zmq.py
  tests/unit/network/test_publisher.py
Labels: bug

#5115 Remove HOME Env Variable from get_remote_workflow_run_dir
  CHANGES.md
  cylc/flow/remote.py
  cylc/flow/subprocpool.py
  cylc/flow/task_events_mgr.py
  tests/functional/events/17-task-event-job-logs-retrieve-command.t
Labels: bug, small

#5123 completion: make completion compatible with Cylc 8
  etc/cylc-bash-completion
Labels: bug

#5130 changelog: strip pre 8.0.0 releases
  CHANGES.md
  README.md
Labels: small, doc

#5131 `workflow_state` xtrigger: infer run number
  CHANGES.md
  cylc/flow/xtriggers/workflow_state.py
  tests/unit/xtriggers/__init__.py
  tests/unit/xtriggers/test_workflow_state.py
Labels: small

#5134 Bump dev version
  cylc/flow/__init__.py
Labels: small

#5104 Fix post-reload trigger.
  CHANGES.md
  cylc/flow/task_job_mgr.py
  cylc/flow/task_pool.py
  tests/functional/reload/27-stall-retrigger.t
  tests/functional/reload/27-stall-retrigger/bin/stall-handler.sh
  tests/functional/reload/27-stall-retrigger/reference.log
  tests/functional/reload/27-stall-retrigger/suite.rc
Labels: bug

#5142 8.0.x -> master
  CHANGES.md
  cylc/flow/task_job_mgr.py
  cylc/flow/task_pool.py
  cylc/flow/xtriggers/workflow_state.py
  tests/functional/reload/27-stall-retrigger.t
  tests/functional/reload/27-stall-retrigger/bin/stall-handler.sh
  tests/functional/reload/27-stall-retrigger/reference.log
  tests/functional/reload/27-stall-retrigger/suite.rc
  tests/unit/xtriggers/__init__.py
  tests/unit/xtriggers/test_workflow_state.py
Labels: sync

#5155 Fix Jinja2 support if HOME undefined.
  cylc/flow/parsec/jinja2support.py
  tests/functional/cylc-get-site-config/04-homeless.t
Labels: bug

#5141 Run GH Actions tests on push to `8.*.x` branches
  .github/workflows/bash.yml
  .github/workflows/test_fast.yml
  .github/workflows/test_functional.yml
  .github/workflows/test_tutorial_workflow.yml
Labels: small, infrastructure

#5156 8.0.x patch
  cylc/flow/data_store_mgr.py
Labels: small

#5139 `log_vc_info`: Redirect diff straight to file to avoid blocking pipe
  CHANGES.md
  cylc/flow/install_plugins/log_vc_info.py
  tests/unit/post_install/test_log_vc_info.py
Labels: bug

#5136 Auto bump dev version on release
  .github/workflows/2_auto_publish_release.yml
Labels: small, infrastructure

#5137 remote-install: add "ana/" to the default install list
  CHANGES.md
  cylc/flow/cfgspec/workflow.py
  cylc/flow/remote.py
  tests/functional/remote/01-file-install.t
  tests/unit/test_remote.py
Labels: bug

#5023 Db store force triggered
  CHANGES.md
  cylc/flow/rundb.py
  cylc/flow/task_job_mgr.py
  cylc/flow/task_pool.py
  cylc/flow/workflow_db_mgr.py
  tests/flakyfunctional/database/00-simple/schema.out
  tests/functional/flow-triggers/11-wait-merge.t
  tests/functional/job-submission/01-job-nn-localhost/db.sqlite3
  tests/functional/restart/57-ghost-job/db.sqlite3
  tests/functional/restart/58-waiting-manual-triggered.t
  tests/functional/restart/58-waiting-manual-triggered/flow.cylc
Labels: bug

#5160 Cherry picked GH Actions updates for 8.0.x
  .github/workflows/2_auto_publish_release.yml
  .github/workflows/bash.yml
  .github/workflows/test_fast.yml
  .github/workflows/test_functional.yml
  .github/workflows/test_tutorial_workflow.yml
Labels: small, infrastructure

#5161 Simplify `WorkflowRuntimeServer` stop logic
  cylc/flow/network/__init__.py
  cylc/flow/network/client.py
  cylc/flow/network/publisher.py
  cylc/flow/network/replier.py
  cylc/flow/network/server.py
  cylc/flow/network/subscriber.py
  cylc/flow/scheduler.py
  tests/integration/test_server.py
Labels: small

#5168 Don't log duplicate config sections.
  cylc/flow/parsec/fileparse.py
Labels: small

#5140 Cylc review update
  CHANGES.md
  lib/cylc/review.py
  lib/cylc/review_dao.py
  lib/cylc/tests/test_review.py
Labels: bug

#5081 Log tidy
  CHANGES.md
  cylc/flow/exceptions.py
  cylc/flow/id_cli.py
  cylc/flow/network/resolvers.py
  cylc/flow/option_parsers.py
  cylc/flow/scheduler.py
  cylc/flow/scripts/message.py
  cylc/flow/task_events_mgr.py
  cylc/flow/task_job_mgr.py
  cylc/flow/task_message.py
  cylc/flow/task_pool.py
  tests/flakyfunctional/cylc-poll/16-execution-time-limit.t
  tests/functional/cylc-message/02-multi.t
  tests/functional/reload/25-xtriggers.t
  tests/functional/remote/06-poll.t
Labels: could be better

#4901 protobuf major version update (4.21.*)
  conda-environment.yml
  cylc/flow/data_messages_pb2.py
  setup.cfg
Labels: dependencies
