Repository cylc/cylc-flow, pull requests merged in 2022-08, with the labels that each got.

#5029 Added blank line to have linter rules render properly
  cylc/flow/scripts/lint.py
Labels: small, doc

#5032 queues: set default limit
  cylc/flow/cfgspec/workflow.py
  tests/functional/cylc-config/00-simple/section1.stdout
Labels: small

#5007 Add `BroadcastCyclePoint` type to schema
  CHANGES.md
  cylc/flow/network/schema.py
  cylc/flow/scripts/broadcast.py
  cylc/flow/workflow_status.py
  tests/functional/graphql/01-workflow.t
Labels: small

#5033 cylc clean: remove top level dir when no run dirs left
  CHANGES.md
  cylc/flow/scripts/clean.py
  cylc/flow/workflow_files.py
  tests/functional/cylc-clean/03-multi.t
  tests/unit/test_workflow_files.py
Labels: could be better

#5037 Fix restart number bug
  CHANGES.md
  cylc/flow/workflow_db_mgr.py
  tests/integration/test_workflow_db_mgr.py
  tests/integration/utils/flow_tools.py
Labels: bug, small

#5040 reload: preserve retry xtriggers on reload
  cylc/flow/task_proxy.py
  tests/functional/reload/25-xtriggers.t
Labels: bug

#5031 Fix chained offset bug
  CHANGES.md
  cylc/flow/cycling/__init__.py
  cylc/flow/cycling/iso8601.py
  cylc/flow/time_parser.py
  tests/unit/test_config.py
Labels: bug

#5046 Shorten error msg
  cylc/flow/pathutil.py
  tests/unit/test_pathutil.py
Labels: could be better

#5045 reload: preserve xtriggers on reload
  cylc/flow/task_proxy.py
  tests/functional/reload/25-xtriggers.t
Labels: bug

#5050 8.1.0: Merged Fix chained offset bug
  .github/workflows/1_create_release_pr.yml
  .github/workflows/bash.yml
  .github/workflows/test_conda-build.yml
  .github/workflows/test_fast.yml
  .github/workflows/test_functional.yml
  .github/workflows/test_tutorial_workflow.yml
  CHANGES.md
  cylc/flow/cycling/__init__.py
  cylc/flow/cycling/iso8601.py
  cylc/flow/time_parser.py
  tests/unit/test_config.py
Labels: bug, infrastructure

#5058 small flake8 fixes
  cylc/flow/network/__init__.py
  cylc/flow/parsec/fileparse.py
  cylc/flow/tui/app.py
  cylc/flow/workflow_files.py
  cylc/flow/xtriggers/echo.py
Labels: small

#5060 fix flake8
  cylc/flow/network/__init__.py
  cylc/flow/parsec/fileparse.py
  cylc/flow/tui/app.py
  cylc/flow/workflow_files.py
  cylc/flow/xtriggers/echo.py
Labels: small

#5049 Fix auto restart bugs
  CHANGES.md
  cylc/flow/loggingutil.py
  cylc/flow/main_loop/auto_restart.py
  cylc/flow/scheduler.py
  cylc/flow/task_remote_mgr.py
  cylc/flow/workflow_files.py
  tests/conftest.py
  tests/functional/lib/bash/test_header
  tests/functional/restart/34-auto-restart-basic.t
  tests/functional/restart/41-auto-restart-local-jobs.t
  tests/integration/main_loop/__init__.py
  tests/integration/main_loop/test_auto_restart.py
  tests/integration/test_scheduler.py
  tests/unit/main_loop/test_auto_restart.py
Labels: bug

#4998 scan: update workflow_params to use public db
  cylc/flow/network/scan.py
Labels: small

#5016 add owner@host for SUCCEEDED and FAILED tasks
  CHANGES.md
  lib/cylc/task_pool.py
Labels: bug, small

#5004 Remove autodoc from `cylc/flow/install_plugins/__init__.py`
  cylc/flow/install_plugins/__init__.py
Labels: small

#5062 Wait for preparing tasks to submit before auto restart
  CHANGES.md
  cylc/flow/scheduler.py
  tests/unit/test_scheduler.py
Labels: bug

#5055 Lint.hardcode style index numbers
  CHANGES.md
  cylc/flow/scripts/lint.py
  tests/unit/scripts/test_lint.py
Labels: could be better

#5071 Bump dev version
  cylc/flow/__init__.py
Labels: small

#5056 Add workflow field to `ClientError`, `ClientTimeout`
  cylc/flow/exceptions.py
  cylc/flow/network/__init__.py
  cylc/flow/network/client.py
Labels: small

#5075 tui: add poll mutation
  cylc/flow/tui/data.py
Labels: small

#5083 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: small, infrastructure

#5067 Datastore fix for removed taskdef.
  CHANGES.md
  cylc/flow/data_store_mgr.py
  tests/functional/restart/58-removed-task.t
  tests/functional/restart/58-removed-task/flow.cylc
Labels: bug

#5087 Fix `FileNotFoundError` when scanning path that doesn't exist
  cylc/flow/network/scan.py
  tests/functional/cylc-clean/00-basic.t
  tests/integration/test_async_util.py
  tests/integration/test_scan.py
  tests/unit/test_async_util.py
Labels: bug

#5025 add platform on reload for SUCCEEDED and FAILED tasks
  CHANGES.md
  cylc/flow/task_pool.py
Labels: bug

#5096 8.0.x.patch
  CHANGES.md
  cylc/flow/data_store_mgr.py
  cylc/flow/task_pool.py
  cylc/flow/workflow_files.py
  tests/functional/cylc-install/03-file-transfer.t
  tests/functional/restart/58-removed-task.t
  tests/functional/restart/58-removed-task/flow.cylc
Labels: small

#5091 Fix tutorial workflows
  CHANGES.md
  cylc/flow/etc/tutorial/cylc-forecasting-workflow/bin/get-observations
  cylc/flow/etc/tutorial/cylc-forecasting-workflow/bin/get-rainfall
  cylc/flow/etc/tutorial/cylc-forecasting-workflow/lib/template/map.html
  setup.cfg
Labels: bug, tutorial-workflows, dependencies

#5106 Fix.rose arguments
  cylc/flow/option_parsers.py
Labels: bug

#5109 Slightly different warning for preparing tasks on reload
  cylc/flow/task_pool.py
Labels: small, could be better

#5097 review: fix search error on Apache under WSGI
  lib/cylc/cylc-review/static/js/search.js
Labels: bug

#5088 terms: settle on "task" and "job" but not "task job"
  INSTALL.md
  cylc/flow/cfgspec/globalcfg.py
  cylc/flow/cfgspec/workflow.py
  cylc/flow/etc/job.sh
  cylc/flow/hostuserutil.py
  cylc/flow/job_file.py
  cylc/flow/job_runner_handlers/at.py
  cylc/flow/job_runner_handlers/background.py
  cylc/flow/job_runner_handlers/loadleveler.py
  cylc/flow/job_runner_handlers/lsf.py
  cylc/flow/job_runner_handlers/moab.py
  cylc/flow/job_runner_handlers/pbs.py
  cylc/flow/job_runner_handlers/sge.py
  cylc/flow/job_runner_handlers/slurm.py
  cylc/flow/job_runner_mgr.py
  cylc/flow/network/schema.py
  cylc/flow/scripts/cat_log.py
  cylc/flow/scripts/jobs_submit.py
  cylc/flow/scripts/message.py
  cylc/flow/scripts/pause.py
  cylc/flow/scripts/poll.py
  cylc/flow/task_events_mgr.py
  cylc/flow/task_job_logs.py
  cylc/flow/task_job_mgr.py
  cylc/flow/task_message.py
  cylc/flow/task_pool.py
  cylc/flow/task_remote_mgr.py
  tests/functional/restart/41-auto-restart-local-jobs.t
  tests/functional/shutdown/09-now2.t
  tests/functional/shutdown/22-stop-now.t
  tests/integration/test_scheduler.py
  tests/unit/test_job_file.py
Labels: small, doc
