Repository cylc/cylc-flow, pull requests merged in 2022-04, with the labels that each got.

#4794 Fix integration test.
  tests/integration/test_scheduler.py
Labels: bug

#4769 Escape quotes in remote command args.
  CHANGES.md
  cylc/flow/scheduler_cli.py
  tests/unit/test_scheduler_cli.py
Labels: bug, small

#4795 doc: fix reference
  cylc/flow/cfgspec/workflow.py
Labels: doc

#4771 scan: exclude Cylc 7 workflows from scan results
  CHANGES.md
  cylc/flow/network/scan.py
  tests/integration/test_scan.py
  tests/unit/network/test_scan.py
Labels: bug

#4776 stop: fix tracebacks
  cylc/flow/scripts/stop.py
Labels: could be better

#4554 Update isodatetime
  CHANGES.md
  conda-environment.yml
  cylc/flow/cycling/iso8601.py
  cylc/flow/scheduler.py
  cylc/flow/task_proxy.py
  cylc/flow/time_parser.py
  setup.cfg
  tests/functional/cyclers/51-recurrence_fmt_1.t
  tests/functional/cyclers/51-recurrence_fmt_1/flow.cylc
  tests/functional/cyclers/51-recurrence_fmt_1/reference.log
  tests/functional/lib/bash/test_header
  tests/unit/test_config.py
  tests/unit/test_time_parser.py
Labels: non-cylc bug

#4819 tui: fix traceback/exit for stopped workflows
  cylc/flow/tui/app.py
Labels: bug, small

#4812 `cylc get-resources` failures handled
  cylc/flow/resources.py
  tests/functional/cylc-get-resources/00-error.t
  tests/functional/cylc-get-resources/test_header
Labels: doc

#4824 schema: fix formatting in docstring
  cylc/flow/network/schema.py
Labels: small, doc

#4800 Undo logging debug
  cylc/flow/task_events_mgr.py
Labels: small

#4820 Change UserInputError to InputError
  cylc/flow/config.py
  cylc/flow/exceptions.py
  cylc/flow/id_cli.py
  cylc/flow/main_loop/__init__.py
  cylc/flow/pathutil.py
  cylc/flow/resources.py
  cylc/flow/scheduler.py
  cylc/flow/scripts/broadcast.py
  cylc/flow/scripts/cat_log.py
  cylc/flow/scripts/clean.py
  cylc/flow/scripts/config.py
  cylc/flow/scripts/graph.py
  cylc/flow/scripts/hold.py
  cylc/flow/scripts/install.py
  cylc/flow/scripts/message.py
  cylc/flow/scripts/release.py
  cylc/flow/scripts/scan.py
  cylc/flow/scripts/set_verbosity.py
  cylc/flow/scripts/show.py
  cylc/flow/scripts/stop.py
  cylc/flow/scripts/trigger.py
  cylc/flow/scripts/workflow_state.py
  cylc/flow/templatevars.py
  cylc/flow/workflow_files.py
  tests/functional/cli/03-set-verbosity.t
  tests/functional/cylc-cat-log/00-local.t
  tests/functional/cylc-cat-log/03-bad-workflow.t
  tests/functional/cylc-graph-diff/00-simple.t
  tests/functional/cylc-install/02-failures.t
  tests/functional/cylc-reinstall/02-failures.t
  tests/unit/scripts/test_config.py
  tests/unit/scripts/test_hold.py
  tests/unit/scripts/test_release.py
  tests/unit/scripts/test_stop.py
  tests/unit/scripts/test_trigger.py
  tests/unit/test_config.py
  tests/unit/test_id_cli.py
  tests/unit/test_pathutil.py
  tests/unit/test_scheduler.py
  tests/unit/test_workflow_files.py
Labels: small, could be better

#4826 Better event handler failure and retry messages.
  cylc/flow/task_events_mgr.py
  tests/flakyfunctional/events/44-timeout.t
  tests/functional/events/10-task-event-job-logs-retrieve.t
Labels: small, could be better

#4830 Better scan workflow detection.
  CHANGES.md
  cylc/flow/network/scan.py
  tests/integration/test_scan.py
Labels: bug

#4816 Disallow direct validation (etc.) of source FILE
  cylc/flow/id_cli.py
  cylc/flow/workflow_files.py
  tests/functional/cylc-cat-log/03-bad-workflow.t
  tests/functional/cylc-graph-diff/00-simple.t
  tests/functional/cylc-install/07-no-recursive-installations.t
  tests/functional/cylc-reinstall/02-failures.t
  tests/functional/graphing/06-family-or.t
  tests/functional/validate/35-pass-special-tasks-non-word-names.t
  tests/functional/validate/37-special-implicit-task.t
  tests/unit/test_id_cli.py
  tests/unit/test_workflow_files.py
Labels: bug

#4743 Stop a specific flow with non-active n=0 tasks present
  CHANGES.md
  cylc/flow/task_pool.py
  tests/functional/spawn-on-demand/15-stop-flow-3.t
  tests/functional/spawn-on-demand/15-stop-flow-3/flow.cylc
  tests/functional/spawn-on-demand/15-stop-flow-3/reference.log
Labels: bug

#4791 fix graphql node state and remove ghosts filters
  CHANGES.md
  cylc/flow/network/resolvers.py
  cylc/flow/network/schema.py
  tests/integration/test_resolvers.py
Labels: bug

#4832 Update `cylc install` usage text
  cylc/flow/scripts/install.py
Labels: small, question, could be better

#4834 Improve `cylc install` usage text & error message
  cylc/flow/scripts/install.py
  cylc/flow/workflow_files.py
  tests/functional/cylc-install/02-failures.t
Labels: small, doc, could be better

#4829 config: suppress config deprecation warnings in compat mode
  CHANGES.md
  cylc/flow/cfgspec/workflow.py
  cylc/flow/config.py
  cylc/flow/time_parser.py
  cylc/flow/workflow_files.py
  tests/functional/deprecations/03-suiterc.t
  tests/unit/test_config.py
Labels: could be better
