Repository cylc/cylc-flow, pull requests merged in 2022-07, with the labels that each got.

#4274 Node (Network) Coordinated Subscriptions (part 1/3) - Centralise REP and PUB into single runtime server
  cylc/flow/data_store_mgr.py
  cylc/flow/network/__init__.py
  cylc/flow/network/publisher.py
  cylc/flow/network/replier.py
  cylc/flow/network/server.py
  cylc/flow/scheduler.py
  tests/integration/test_examples.py
  tests/integration/test_publisher.py
  tests/integration/test_replier.py
  tests/integration/test_scan.py
  tests/integration/test_server.py
  tests/integration/test_workflow_files.py
  tests/integration/test_zmq.py
  tests/unit/network/test_publisher.py
Labels: efficiency

#4890 Check symlink target.
  CHANGES.md
  cylc/flow/pathutil.py
  cylc/flow/task_remote_cmd.py
  cylc/flow/workflow_files.py
  tests/functional/remote/08-symlink-dir-target-exist.t
  tests/functional/remote/basic/flow.cylc
  tests/unit/test_pathutil.py
  tests/unit/test_workflow_files.py
Labels: bug

#4952 Back compat deprecation warnings - an addendum
  cylc/flow/config.py
  tests/unit/test_config.py
Labels: small

#4967 Back-compat mode tweak.
  cylc/flow/task_pool.py
  tests/functional/optional-outputs/07-finish-fail-c7-backcompat.t
  tests/functional/optional-outputs/08-finish-fail-c7-c8.t
  tests/functional/optional-outputs/finish-fail-c7/suite.rc
Labels: bug

#4961 Test reinstall deletion
  tests/functional/cylc-reinstall/03-external-files.t
  tests/unit/test_workflow_files.py
Labels: small

#4970 Back-compat: fix self-suicide: a:fail => !a
  CHANGES.md
  cylc/flow/task_pool.py
  cylc/flow/taskdef.py
  tests/functional/spawn-on-demand/16-c7backcompat-self-suicide.t
  tests/functional/spawn-on-demand/16-c7backcompat-self-suicide/reference.log
  tests/functional/spawn-on-demand/16-c7backcompat-self-suicide/suite.rc
  tests/functional/spawn-on-demand/17-c7backcompat-self-suicide-cycling.t
  tests/functional/spawn-on-demand/17-c7backcompat-self-suicide-cycling/reference.log
  tests/functional/spawn-on-demand/17-c7backcompat-self-suicide-cycling/suite.rc
Labels: bug

#4939 play: use full workflow ID when re-invoking
  cylc/flow/scheduler_cli.py
  tests/functional/restart/44-reinvoke.t
  tests/unit/test_scheduler_cli.py
Labels: small

#4973 Tidy main command help.
  cylc/flow/scripts/cylc.py
  cylc/flow/scripts/trigger.py
Labels: could be better

#4933 schema: small docs changes
  cylc/flow/network/schema.py
  cylc/flow/scripts/broadcast.py
Labels: small, doc

#4956 added simple docs for default queues.
  cylc/flow/cfgspec/workflow.py
Labels: doc

#4978 Fix failure to clean on remote host with leftover contact file
  .github/workflows/test_functional.yml
  CHANGES.md
  cylc/flow/main_loop/health_check.py
  cylc/flow/network/scan.py
  cylc/flow/scheduler.py
  cylc/flow/task_remote_mgr.py
  cylc/flow/workflow_files.py
  tests/functional/cylc-clean/05-old-remote-contact.t
  tests/integration/test_scan.py
  tests/unit/test_workflow_files.py
Labels: bug, small

#4964 cylc reinstall --dry-run
  CHANGES.md
  cylc/flow/cfgspec/globalcfg.py
  cylc/flow/option_parsers.py
  cylc/flow/scripts/check_versions.py
  cylc/flow/scripts/clean.py
  cylc/flow/scripts/cycle_point.py
  cylc/flow/scripts/cylc.py
  cylc/flow/scripts/diff.py
  cylc/flow/scripts/dump.py
  cylc/flow/scripts/ext_trigger.py
  cylc/flow/scripts/get_resources.py
  cylc/flow/scripts/get_workflow_contact.py
  cylc/flow/scripts/install.py
  cylc/flow/scripts/jobs_kill.py
  cylc/flow/scripts/jobs_poll.py
  cylc/flow/scripts/jobs_submit.py
  cylc/flow/scripts/list.py
  cylc/flow/scripts/reinstall.py
  cylc/flow/scripts/reload.py
  cylc/flow/scripts/remote_init.py
  cylc/flow/scripts/remote_tidy.py
  cylc/flow/scripts/report_timings.py
  cylc/flow/scripts/scan.py
  cylc/flow/scripts/set_outputs.py
  cylc/flow/scripts/stop.py
  cylc/flow/scripts/trigger.py
  cylc/flow/scripts/validate.py
  cylc/flow/terminal.py
  cylc/flow/workflow_files.py
  tests/conftest.py
  tests/functional/cylc-reinstall/00-simple.t
  tests/integration/test_reinstall.py
Labels: could be better

#4948 Fix lack of errors/warnings for deprecated `[runtime][<task>][remote]retrieve job logs *` settings
  CHANGES.md
  cylc/flow/cfgspec/workflow.py
  cylc/flow/config.py
  cylc/flow/platforms.py
  cylc/flow/task_job_mgr.py
  tests/functional/events/11-cycle-task-event-job-logs-retrieve/flow.cylc
  tests/functional/events/32-task-event-job-logs-retrieve-2.t
  tests/functional/events/32-task-event-job-logs-retrieve-2/flow.cylc
  tests/functional/events/33-task-event-job-logs-retrieve-3.t
  tests/functional/events/33-task-event-job-logs-retrieve-3/flow.cylc
  tests/functional/intelligent-host-selection/02-badhosts.t
  tests/functional/intelligent-host-selection/02-badhosts/flow.cylc
  tests/unit/test_platforms.py
  tests/unit/test_platforms_get_platform.py
Labels: bug, small

#4984 reload: fix submission errors for jobs awaiting preparation
  CHANGES.md
  cylc/flow/scheduler.py
  cylc/flow/task_job_mgr.py
  cylc/flow/task_pool.py
  cylc/flow/task_proxy.py
  tests/integration/test_queues.py
  tests/integration/test_scheduler.py
Labels: bug

#4996 fix flake8 bug which crept into master
  cylc/flow/scheduler.py
Labels: small

#5000 fix flake8
  cylc/flow/cfgspec/globalcfg.py
Labels: small

#4999 Add remaining workflow config item descriptions.
  cylc/flow/cfgspec/globalcfg.py
  cylc/flow/cfgspec/workflow.py
Labels: small, doc

#5003 Document the 'abort' config items.
  cylc/flow/cfgspec/globalcfg.py
Labels: doc

#5008 Fix spawning of absolute-triggered tasks.
  CHANGES.md
  cylc/flow/task_pool.py
  cylc/flow/taskdef.py
  tests/integration/test_task_pool.py
Labels: bug

#5011 no preparing data-store jobs, decrement submit-num on restart
  CHANGES.md
  cylc/flow/data_store_mgr.py
  cylc/flow/task_events_mgr.py
  cylc/flow/task_pool.py
  tests/functional/lib/bash/test_header
  tests/functional/lib/python/diffr.py
  tests/functional/restart/57-ghost-job.t
  tests/functional/restart/57-ghost-job/db.sqlite3
  tests/functional/restart/57-ghost-job/flow.cylc
  tests/integration/conftest.py
Labels: bug, small

#5018 cli: minor docs changes for 8.0.0 release
  cylc/flow/scripts/cat_log.py
  cylc/flow/scripts/check_versions.py
  cylc/flow/scripts/ext_trigger.py
  cylc/flow/scripts/message.py
  cylc/flow/scripts/reload.py
  cylc/flow/scripts/set_outputs.py
  cylc/flow/scripts/stop.py
  cylc/flow/scripts/validate.py
Labels: small, doc

#5021 Update changelog & readme pre-8.0.0
  CHANGES.md
  README.md
Labels: small

#5027 Bump to dev version
  CHANGES.md
  INSTALL.md
  README.md
  cylc/flow/__init__.py
  cylc/flow/config.py
  cylc/flow/scripts/lint.py
  cylc/flow/time_parser.py
  cylc/flow/workflow_files.py
  setup.cfg
  tests/functional/cylc-install/02-failures.t
  tests/functional/cylc-reinstall/02-failures.t
  tests/unit/test_workflow_files.py
Labels: small
