Repository cylc/cylc-flow, pull requests merged in 2022-05, with the labels that each got.

#4841 Include exception message when a failure to load main loop plugin occurs
  cylc/flow/exceptions.py
  cylc/flow/main_loop/__init__.py
Labels: small, could be better

#4804 Close File Installation Log
  cylc/flow/scheduler_cli.py
Labels: bug, small

#4828 scan CLI: handle bad contact files.
  CHANGES.md
  cylc/flow/scripts/scan.py
  tests/unit/scripts/test_scan.py
Labels: bug

#4827 Move processing of stop cycle point to config.py
  cylc/flow/cfgspec/workflow.py
  cylc/flow/config.py
  cylc/flow/cycling/__init__.py
  cylc/flow/cycling/iso8601.py
  cylc/flow/scheduler.py
  cylc/flow/scheduler_cli.py
  cylc/flow/task_pool.py
  tests/functional/cylc-play/08-provided-vars.t
  tests/functional/cylc-play/09-invalid-cp-opt.t
  tests/functional/restart/08-stop-after-cycle-point.t
  tests/functional/restart/08-stop-after-cycle-point/flow.cylc
  tests/integration/test_task_pool.py
  tests/unit/conftest.py
  tests/unit/test_config.py
  tests/unit/test_scheduler.py
  tests/unit/test_task_proxy.py
Labels: bug

#4846 Improve `flow.cylc` reference docs
  cylc/flow/cfgspec/workflow.py
  cylc/flow/cycling/iso8601.py
  cylc/flow/time_parser.py
  tests/functional/validate/38-degenerate-point-format.t
Labels: doc

#4850 Stop a few more deprecation warnings in backward compatibility mode
  cylc/flow/cfgspec/workflow.py
Labels: small, could be better

#4856 contact: process check should handle dirty JSON
  cylc/flow/workflow_files.py
  tests/integration/test_workflow_files.py
Labels: bug, small

#4875 Emacs syntax highlighting: fix filename pattern matching
  CHANGES.md
  cylc/flow/etc/syntax/cylc-mode.el
  cylc/flow/etc/syntax/cylc.lang
  cylc/flow/etc/syntax/cylc.xml
Labels: bug

#4878 Jinja context bug
  cylc/flow/parsec/jinja2support.py
  tests/functional/jinja2/02-incomplete.t
  tests/functional/jinja2/03-bad.t
  tests/functional/jinja2/04-missing.t
  tests/functional/jinja2/12-error.t
  tests/functional/jinja2/12-error/flow.cylc
  tests/functional/jinja2/badsyntax/flow.cylc
  tests/functional/jinja2/cylc-include-badsyntax/flow-includeme.cylc
  tests/functional/jinja2/cylc-include-badsyntax/flow.cylc
  tests/functional/jinja2/include-badsyntax/flow.cylc
  tests/functional/jinja2/include-exception/flow.cylc
  tests/functional/jinja2/include-exception/foo.cylc
  tests/functional/jinja2/include-incomplete/flow.cylc
  tests/functional/jinja2/include-missing/flow.cylc
  tests/functional/validate/40-jinja2-template-syntax-error-main.t
  tests/functional/validate/41-jinja2-template-syntax-error-cylc-include.t
  tests/functional/validate/41-jinja2-template-syntax-error-cylc-include/flow.cylc
  tests/functional/validate/42-jinja2-template-syntax-error-jinja-include.t
  tests/functional/validate/42-jinja2-template-syntax-error-jinja-include/flow-includeme.cylc
  tests/functional/validate/42-jinja2-template-syntax-error-jinja-include/flow.cylc
  tests/functional/validate/44-jinja2-template-not-found.t
Labels: bug

#4874 cylc show: ignore past task prereqs
  CHANGES.md
  cylc/flow/scripts/show.py
  cylc/flow/workflow_db_mgr.py
  tests/flakyfunctional/cylc-show/00-simple.t
  tests/flakyfunctional/cylc-show/04-multi.t
  tests/flakyfunctional/cylc-show/04-multi/flow.cylc
  tests/flakyfunctional/cylc-show/04-multi/reference.log
  tests/functional/cylc-show/01-clock-triggered.t
  tests/functional/cylc-show/03-clock-triggered-non-utc-mode.t
  tests/functional/cylc-show/05-complex.t
  tests/functional/cylc-show/06-past-present-future.t
  tests/functional/cylc-show/06-past-present-future/flow.cylc
  tests/functional/graph-equivalence/multiline_and_refs/c-ref
  tests/functional/graph-equivalence/multiline_and_refs/c-ref-2
  tests/functional/graph-equivalence/splitline_refs/a-ref
  tests/functional/graph-equivalence/splitline_refs/b-ref
  tests/functional/graph-equivalence/splitline_refs/c-ref
Labels: bug

#4871 Don't log fake task state changes (datastore)
  cylc/flow/data_store_mgr.py
  cylc/flow/task_proxy.py
Labels: bug

#4872 Allow cylc clean to use runN
  CHANGES.md
  cylc/flow/workflow_files.py
  tests/functional/cylc-clean/04-runN.t
  tests/unit/test_workflow_files.py
Labels: bug, small

#4831 resolvers: add a couple of comments
  cylc/flow/network/resolvers.py
Labels: doc

#4881 Fix task matching bug
  CHANGES.md
  cylc/flow/id_match.py
  cylc/flow/task_proxy.py
  tests/unit/test_id_match.py
  tests/unit/test_task_proxy.py
Labels: bug

#4893 Bump to next dev version
  cylc/flow/__init__.py
Labels: small

#4894 Fix bug in remote tidy error handling
  lib/cylc/task_remote_mgr.py
Labels: bug, small

#4889 Don't prompt to clean no workflows.
  CHANGES.md
  cylc/flow/scripts/clean.py
Labels: bug

#4860 Raise an error if the user tries to set owner.
  CHANGES.md
  cylc/flow/cfgspec/workflow.py
  cylc/flow/config.py
  cylc/flow/parsec/config.py
  tests/unit/test_config.py
Labels: small

#4896 Allow platform default directives
  CHANGES.md
  cylc/flow/cfgspec/globalcfg.py
  cylc/flow/task_job_mgr.py
  tests/functional/platforms/09-default-directives.t
Labels: could be better, config change
