Repository cylc/cylc-flow, pull requests merged in 2023-01, with the labels that each got.

#5283 Manual PR: Update copyright year on 8.0.x
  README.md
  cylc/flow/scripts/__init__.py
Labels: small

#5271 play: upgrade DB *after* user upgrade confirmation
  cylc/flow/rundb.py
  cylc/flow/scheduler_cli.py
  cylc/flow/terminal.py
  cylc/flow/workflow_db_mgr.py
  cylc/flow/workflow_files.py
  tests/functional/cylc-clean/03-multi.t
  tests/functional/database/07-incompatible.t
  tests/unit/test_workflow_files.py
Labels: bug

#5279 show: ensure stable expression output
  cylc/flow/config.py
  cylc/flow/task_trigger.py
  tests/functional/triggering/16-fam-expansion.t
Labels: small

#5288 Method calculating task mean elapsed time returns an integer
  cylc/flow/data_store_mgr.py
  tests/unit/test_data_store_mgr.py
Labels: small

#5286 Fix clock trigger execution retry delay bug
  CHANGES.md
  cylc/flow/cycling/__init__.py
  cylc/flow/scheduler.py
  cylc/flow/task_job_mgr.py
  cylc/flow/task_proxy.py
  tests/functional/special/08-clock-trigger-retry.t
Labels: bug

#5294 auto-restart: improve robustness to DNS errors
  cylc/flow/scheduler.py
  tests/unit/test_scheduler.py
Labels: could be better

#5321 Optimize ID/tokens code
  cylc/flow/id.py
Labels: small, efficiency

#5319 data-store graph window efficiency/refactor
  cylc/flow/data_store_mgr.py
  cylc/flow/task_pool.py
  cylc/flow/task_proxy.py
Labels: efficiency

#5325 tokens: speed up duplication of Tokens objects
  CHANGES.md
  cylc/flow/id.py
  tests/integration/test_reinstall.py
Labels: small, efficiency

#5327 8.1.x
  CHANGES.md
  cylc/flow/cfgspec/workflow.py
  cylc/flow/config.py
  cylc/flow/data_store_mgr.py
  cylc/flow/id.py
  cylc/flow/network/scan.py
  cylc/flow/rundb.py
  cylc/flow/scheduler.py
  cylc/flow/scheduler_cli.py
  cylc/flow/scripts/cat_log.py
  cylc/flow/scripts/install.py
  cylc/flow/scripts/report_timings.py
  cylc/flow/scripts/validate_install_play.py
  cylc/flow/scripts/validate_reinstall.py
  cylc/flow/task_pool.py
  cylc/flow/task_proxy.py
  cylc/flow/templatevars.py
  cylc/flow/workflow_db_mgr.py
  cylc/flow/workflow_files.py
  tests/functional/cylc-combination-scripts/06-vip-named-run
  tests/functional/cylc-combination-scripts/06-vip-named-run.t
  tests/integration/conftest.py
  tests/integration/test_config.py
  tests/integration/test_reinstall.py
  tests/unit/test_config.py
  tests/unit/test_rundb.py
  tests/unit/test_scheduler_cli.py
  tests/unit/test_templatevars.py
  tests/unit/test_workflow_db_mgr.py
Labels: efficiency, sync

#5335 Fix linkcheck by excluding web.archive.org
  .github/workflows/test_fast.yml
  conda-environment.yml
  cylc/flow/hostuserutil.py
  setup.cfg
  tests/unit/test_links.py
Labels: small, testing

#5313 Fix Validation using old tvars fails for Cylc 7 workflows
  CHANGES.md
  cylc/flow/scheduler_cli.py
  cylc/flow/scripts/report_timings.py
  cylc/flow/scripts/validate_reinstall.py
  cylc/flow/templatevars.py
  tests/functional/database/07-incompatible.t
  tests/integration/test_config.py
  tests/unit/parsec/test_fileparse.py
  tests/unit/test_templatevars.py
  tests/unit/test_workflow_db_mgr.py
Labels: bug
