Repository cylc/cylc-flow, pull requests merged in 2023-12, with the labels that each got.

#5861 Exclude broken pytest-asyncio version
  setup.cfg
Labels: small, dependencies

#5858 tui: avoid deprecated import
  cylc/flow/tui/app.py
Labels: small

#5789 Test.sim mode changes on restart
  changes.d/5789.fix.md
  cylc/flow/rundb.py
  cylc/flow/scheduler.py
  tests/integration/test_mode_on_restart.py
Labels: bug?, POC

#5826 tests/i: add reflog fixture
  .github/workflows/test_fast.yml
  cylc/flow/task_pool.py
  pytest.ini
  setup.cfg
  tests/integration/conftest.py
  tests/integration/test_examples.py
  tests/integration/tui/screenshots/test_scheduler_logs.workflow-configuration-file.html
  tests/integration/tui/test_updater.py
  tests/integration/utils/flow_tools.py
Labels: small

#5885 added chain offset logic
  changes.d/5885.fix.md
  cylc/flow/cycling/iso8601.py
  tests/unit/test_config.py
Labels: bug

#5600 dump: restrict window to n=0
  changes.d/5600.break.md
  cylc/flow/scripts/dump.py
  tests/functional/runahead/06-release-update.t
  tests/integration/scripts/test_dump.py
Labels: bug, small

#5879 Feat.lint obsolete vars
  changes.d/5879.feat.md
  cylc/flow/scripts/lint.py
  tests/unit/scripts/test_lint.py
Labels: could be better
