Repository cylc/cylc-flow, pull requests merged in 2023-05, with the labels that each got.

#5502 Add Cheng Da to contributors
  CONTRIBUTING.md
Labels: small

#5503 Platforms code tidy
  CONTRIBUTING.md
  cylc/flow/platforms.py
Labels: small

#5504 8.1.x -> master
  .dockerignore
  CHANGES.md
  cylc/flow/data_store_mgr.py
  cylc/flow/prerequisite.py
  cylc/flow/task_pool.py
  cylc/flow/task_proxy.py
  cylc/flow/task_state.py
  cylc/flow/task_trigger.py
  cylc/flow/taskdef.py
  dockerfiles/cylc-dev/Dockerfile
  dockerfiles/cylc-remote/Dockerfile
  tests/functional/events/11-cycle-task-event-job-logs-retrieve.t
  tests/functional/events/11-cycle-task-event-job-logs-retrieve/flow.cylc
  tests/integration/test_scheduler.py
  tests/integration/test_task_pool.py
  tests/integration/utils/flow_tools.py
  tests/unit/test_task_state.py
  tests/unit/test_taskdef.py
Labels: sync

#5507 Fix flaky test
  tests/functional/platforms/11-platform-gone-on-restart.t
Labels: small, testing

#5496 prerequsite: remove target_point_strings attribute
  cylc/flow/prerequisite.py
  tests/unit/test_prerequisite.py
Labels: small, efficiency

#5506 Fix `eval_host()` localhost bug & plug testing gap
  CHANGES.md
  cylc/flow/task_remote_mgr.py
  tests/functional/job-submission/19-platform_select.t
  tests/functional/job-submission/19-platform_select/flow.cylc
  tests/unit/test_task_remote_mgr.py
Labels: bug

#5497 actions: test up to python 3.11
  .github/workflows/1_create_release_pr.yml
  .github/workflows/2_auto_publish_release.yml
  .github/workflows/build.yml
  .github/workflows/test_fast.yml
  .github/workflows/test_functional.yml
  .github/workflows/test_manylinux.yml
  cylc/flow/scheduler.py
  cylc/flow/scripts/cylc.py
  cylc/flow/scripts/lint.py
  cylc/flow/task_remote_mgr.py
  setup.cfg
  tests/integration/test_workflow_files.py
Labels: small

#5509 prerequisite: remove set_not_satisfied
  cylc/flow/prerequisite.py
  cylc/flow/task_state.py
  tests/integration/test_data_store_mgr.py
  tests/integration/test_task_pool.py
  tests/unit/test_prerequisite.py
Labels: small

#5521 Further fix for flaky test
  tests/functional/platforms/11-platform-gone-on-restart.t
Labels: small, testing

#5520 8.1.x
  CHANGES.md
  cylc/flow/scripts/cat_log.py
  cylc/flow/task_remote_mgr.py
  tests/functional/cylc-cat-log/00-local.t
  tests/functional/cylc-cat-log/00-local/flow.cylc
  tests/functional/cylc-cat-log/01-remote.t
  tests/functional/job-submission/19-platform_select.t
  tests/functional/job-submission/19-platform_select/flow.cylc
  tests/unit/test_task_remote_mgr.py
Labels: sync

#5522 8.1.x
  tests/functional/platforms/11-platform-gone-on-restart.t
Labels: sync

#5519 lint: read files one line at a time
  cylc/flow/scripts/lint.py
  tests/unit/scripts/test_lint.py
Labels: small

#5528 schema: enable selected mutations for the stopping workflow state
  CHANGES.md
  cylc/flow/network/schema.py
Labels: small

#5493 GH Actions: auto sync 8.1.x -> master
  .github/workflows/branch_sync.yml
Labels: infrastructure

#5532 GH Actions patch
  .github/workflows/branch_sync.yml
Labels: small, infrastructure

#5524 Turn log timestamps back on before running Cylc Play in VIP & VR
  CHANGES.md
  cylc/flow/loggingutil.py
  cylc/flow/scripts/clean.py
  cylc/flow/scripts/get_resources.py
  cylc/flow/scripts/validate.py
  cylc/flow/scripts/validate_install_play.py
  cylc/flow/scripts/validate_reinstall.py
  tests/unit/test_loggingutil.py
Labels: could be better

#5420 fix state summaries
  cylc/flow/data_messages.proto
  cylc/flow/data_messages_pb2.py
  cylc/flow/data_store_mgr.py
Labels: bug, small

#5548 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: small

#5536 Fix S011 lint
  cylc/flow/scripts/lint.py
  tests/unit/scripts/test_lint.py
Labels: small, could be better

#5550 Fix cylc lint S011 (commented-out Jinja2) bug
  cylc/flow/scripts/lint.py
  tests/unit/scripts/test_lint.py
Labels: bug, small

#5534 Logging: say command actioned instead of succeeded
  cylc/flow/scheduler.py
  tests/functional/cli/03-set-verbosity.t
  tests/functional/hold-release/00-workflow/flow.cylc
  tests/functional/hold-release/05-release.t
  tests/functional/pause-resume/00-workflow/flow.cylc
  tests/functional/pause-resume/12-pause-then-retry/flow.cylc
  tests/functional/reload/25-xtriggers.t
  tests/functional/spawn-on-demand/05-stop-flow/flow.cylc
  tests/functional/spawn-on-demand/06-stop-flow-2/flow.cylc
  tests/integration/test_resolvers.py
Labels: small, could be better

#5552 Use more sensible exception class for `detect_old_contact_file()`
  cylc/flow/clean.py
  cylc/flow/exceptions.py
  cylc/flow/network/client.py
  cylc/flow/scheduler.py
  cylc/flow/scheduler_cli.py
  cylc/flow/scripts/validate_reinstall.py
  cylc/flow/workflow_files.py
  tests/integration/test_workflow_files.py
  tests/unit/test_clean.py
Labels: small, could be better

#5560 job: redact the CYLC_TASK_DEPENDENCIES variable if too long
  CHANGES.md
  cylc/flow/job_file.py
  tests/unit/test_job_file.py
Labels: bug, small
