Repository cylc/cylc-flow, pull requests merged in 2023-11, with the labels that each got.

#5660 Data store avoid graph re-walk
  cylc/flow/data_messages.proto
  cylc/flow/data_messages_pb2.py
  cylc/flow/data_store_mgr.py
  cylc/flow/network/resolvers.py
  cylc/flow/network/schema.py
  cylc/flow/task_pool.py
  cylc/flow/task_proxy.py
  tests/functional/cylc-show/06-past-present-future/flow.cylc
  tests/functional/graphql/01-workflow.t
  tests/functional/graphql/03-is-held-arg.t
  tests/functional/n-window/01-past-present-future.t
  tests/functional/n-window/01-past-present-future/flow.cylc
  tests/functional/n-window/02-big-window.t
  tests/functional/n-window/02-big-window/flow.cylc
  tests/functional/n-window/test_header
  tests/integration/test_increment_graph_window.py
Labels: efficiency

#5805 Added changelog for #5660
  changes.d/5660.fix.md
Labels: small

#5777 Add missing test cases for `next()`/`previous()`
  tests/unit/cycling/test_iso8601.py
Labels: small

#5791 Fix.all xtriggers on an itask are the same
  changes.d/5791.fix.md
  cylc/flow/task_proxy.py
  cylc/flow/xtrigger_mgr.py
  tests/integration/test_xtrigger_mgr.py
  tests/unit/test_task_proxy.py
Labels: bug

#5790 replace pkg_resources with importlib_metadata and packaging
  .github/workflows/test_fast.yml
  conda-environment.yml
  cylc/flow/__init__.py
  cylc/flow/cfgspec/globalcfg.py
  cylc/flow/network/scan.py
  cylc/flow/parsec/fileparse.py
  cylc/flow/scheduler_cli.py
  cylc/flow/scripts/completion_server.py
  cylc/flow/scripts/cylc.py
  cylc/flow/scripts/install.py
  cylc/flow/scripts/reinstall.py
  cylc/flow/terminal.py
  cylc/flow/workflow_db_mgr.py
  setup.cfg
  tests/functional/cli/01-help.t
  tests/integration/test_install.py
  tests/unit/plugins/test_pre_configure.py
  tests/unit/scripts/test_completion_server.py
  tests/unit/scripts/test_cylc.py
Labels: efficiency, dependencies

#5801 Handle parentheses on RHS of trigger expression
  changes.d/5801.fix.md
  cylc/flow/graph_parser.py
  tests/unit/test_graph_parser.py
Labels: bug

#5794 Support Python 3.12
  .github/workflows/test_fast.yml
  .github/workflows/test_functional.yml
  changes.d/5794.break.md
  cylc/flow/cfgspec/globalcfg.py
  cylc/flow/cfgspec/workflow.py
  cylc/flow/id.py
  cylc/flow/scripts/report_timings.py
  setup.cfg
  tests/functional/events/09-task-event-mail.t
  tests/functional/events/18-workflow-event-mail.t
  tests/functional/events/29-task-event-mail-1.t
  tests/functional/events/30-task-event-mail-2.t
  tests/functional/lib/bash/test_header
  tests/unit/test_indep_task_queues.py
Labels: infrastructure, dependencies

#5772 Lint: Add a check for indentation being 4N spaces.
  changes.d/5772.feat.md
  cylc/flow/scripts/lint.py
  tests/unit/scripts/test_lint.py
Labels: small, doc

#5832 Fix `IndepQueueManager` test
  cylc/flow/task_queues/independent.py
  tests/unit/test_indep_task_queues.py
Labels: small

#5821 log_vc_info: handle long command output
  changes.d/5821.fix.md
  cylc/flow/install_plugins/log_vc_info.py
  cylc/flow/pipe_poller.py
  tests/unit/test_pipe_poller.py
Labels: bug

#5842 GH Actions: limit tutorial workflow to Python 3.11
  .github/workflows/test_tutorial_workflow.yml
Labels: small, infrastructure

#5843 Fix.bad toml example in lint docstring
  cylc/flow/scripts/lint.py
Labels: doc

#5731 Tui 1.0
  changes.d/5731.feat.md
  cylc/flow/data_store_mgr.py
  cylc/flow/option_parsers.py
  cylc/flow/scripts/tui.py
  cylc/flow/tui/__init__.py
  cylc/flow/tui/app.py
  cylc/flow/tui/data.py
  cylc/flow/tui/overlay.py
  cylc/flow/tui/tree.py
  cylc/flow/tui/updater.py
  cylc/flow/tui/util.py
  tests/conftest.py
  tests/integration/tui/__init__.py
  tests/integration/tui/conftest.py
  tests/integration/tui/screenshots/test_auto_expansion.later-time.html
  tests/integration/tui/screenshots/test_auto_expansion.on-load.html
  tests/integration/tui/screenshots/test_errors.list-error.html
  tests/integration/tui/screenshots/test_errors.open-error.html
  tests/integration/tui/screenshots/test_job_logs.01-job.out.html
  tests/integration/tui/screenshots/test_job_logs.02-job.out.html
  tests/integration/tui/screenshots/test_navigation.cursor-at-bottom-of-screen.html
  tests/integration/tui/screenshots/test_navigation.family-A-collapsed.html
  tests/integration/tui/screenshots/test_navigation.on-load.html
  tests/integration/tui/screenshots/test_navigation.workflow-expanded.html
  tests/integration/tui/screenshots/test_offline_mutation.clean-command-error.html
  tests/integration/tui/screenshots/test_offline_mutation.clean-mutation-selected.html
  tests/integration/tui/screenshots/test_offline_mutation.stop-all-mutation-selected.html
  tests/integration/tui/screenshots/test_online_mutation.command-failed-client-error.html
  tests/integration/tui/screenshots/test_online_mutation.command-failed-workflow-stopped.html
  tests/integration/tui/screenshots/test_online_mutation.command-failed.html
  tests/integration/tui/screenshots/test_online_mutation.hold-mutation-selected.html
  tests/integration/tui/screenshots/test_online_mutation.task-selected.html
  tests/integration/tui/screenshots/test_restart_reconnect.1-workflow-running.html
  tests/integration/tui/screenshots/test_restart_reconnect.2-workflow-stopped.html
  tests/integration/tui/screenshots/test_restart_reconnect.3-workflow-restarted.html
  tests/integration/tui/screenshots/test_scheduler_logs.log-file-selection.html
  tests/integration/tui/screenshots/test_scheduler_logs.scheduler-log-file.html
  tests/integration/tui/screenshots/test_scheduler_logs.workflow-configuration-file.html
  tests/integration/tui/screenshots/test_show.fail.html
  tests/integration/tui/screenshots/test_show.success.html
  tests/integration/tui/screenshots/test_subscribe_unsubscribe.subscribed.html
  tests/integration/tui/screenshots/test_subscribe_unsubscribe.unsubscribed.html
  tests/integration/tui/screenshots/test_task_logs.latest-job.err.html
  tests/integration/tui/screenshots/test_task_logs.latest-job.out.html
  tests/integration/tui/screenshots/test_tui_basics.test-raikura-enter.html
  tests/integration/tui/screenshots/test_tui_basics.test-raikura-help.html
  tests/integration/tui/screenshots/test_tui_basics.test-raikura.html
  tests/integration/tui/screenshots/test_workflow_states.filter-active.html
  tests/integration/tui/screenshots/test_workflow_states.filter-starts-with-t.html
  tests/integration/tui/screenshots/test_workflow_states.filter-stopped-or-paused.html
  tests/integration/tui/screenshots/test_workflow_states.filter-stopped.html
  tests/integration/tui/screenshots/test_workflow_states.unfiltered.html
  tests/integration/tui/test_app.py
  tests/integration/tui/test_logs.py
  tests/integration/tui/test_mutations.py
  tests/integration/tui/test_show.py
  tests/integration/tui/test_updater.py
  tests/unit/tui/test_data.py
  tests/unit/tui/test_overlay.py
  tests/unit/tui/test_util.py
Labels: efficiency, could be better

#5848 Improve changelog entries
  changes.d/5772.feat.md
  changes.d/5841.fix.md
Labels: small
