Repository cylc/cylc-flow, pull requests merged in 2023-04, with the labels that each got.

#5441 efficiency: pass tokens instances to get_broadcast
  cylc/flow/broadcast_mgr.py
  cylc/flow/data_store_mgr.py
  cylc/flow/id.py
  cylc/flow/task_events_mgr.py
  cylc/flow/task_job_mgr.py
  tests/unit/test_id.py
Labels: efficiency

#5381 tui: add vr
  cylc/flow/scripts/reinstall.py
  cylc/flow/scripts/validate_reinstall.py
  cylc/flow/tui/app.py
  cylc/flow/tui/data.py
  cylc/flow/tui/overlay.py
Labels: small

#5451 job runner handlers: docs++
  cylc/flow/job_runner_handlers/documentation.py
Labels: small, doc

#5455 Improve documentation for retrieve job logs command
  cylc/flow/cfgspec/globalcfg.py
Labels: doc

#5458 Stop Cylc Reinstall modifying global variables
  CHANGES.md
  cylc/flow/scripts/reinstall.py
  tests/integration/test_reinstall.py
Labels: bug, small

#5463 8.1.x
  cylc/flow/job_runner_handlers/documentation.py
  tests/functional/cylc-clean/06-nfs.t
Labels: sync

#5460 validate-reinstall: don't print reload message
  cylc/flow/scripts/reinstall.py
  cylc/flow/scripts/validate_reinstall.py
Labels: small, could be better

#5464 Fix flake8-comprehensions C419
  cylc/flow/option_parsers.py
  cylc/flow/platforms.py
  cylc/flow/scripts/lint.py
Labels: small

#5461 play: preserve colour formatting when detaching
  CHANGES.md
  cylc/flow/scheduler_cli.py
  tests/unit/test_scheduler_cli.py
Labels: small, could be better

#5468 (Cherry pick) Upload coverage to Codecov in separate job
  .github/workflows/test_fast.yml
  .github/workflows/test_functional.yml
Labels: infrastructure, sync

#5467 upgrade cylc message internal help with details of severity levels
  cylc/flow/scripts/message.py
Labels: doc

#5343 Fix localhost platform matching
  CHANGES.md
  cylc/flow/hostuserutil.py
  cylc/flow/task_job_mgr.py
  cylc/flow/task_remote_mgr.py
  tests/functional/platforms/10-do-not-host-check-platforms.t
  tests/unit/test_hostuserutil.py
Labels: bug

#5450 parsec: catch section/option conflict in validation
  CHANGES.md
  cylc/flow/config.py
  cylc/flow/parsec/upgrade.py
  cylc/flow/parsec/validate.py
  tests/functional/validate/76-section-section-transpose.t
  tests/integration/test_config.py
Labels: bug, small

#5479 Fix broken `cylc help license` command
  .github/workflows/build.yml
  .github/workflows/test_manylinux.yml
  CHANGES.md
  conda-environment.yml
  cylc/flow/scripts/cylc.py
  setup.cfg
Labels: bug, small

#5484 8.1.x
  .github/workflows/build.yml
  .github/workflows/test_manylinux.yml
  CHANGES.md
  conda-environment.yml
  cylc/flow/scripts/cylc.py
  setup.cfg
Labels: sync

#5488 cat-log: don't list directories which don't exist
  cylc/flow/scripts/cat_log.py
  tests/functional/cylc-cat-log/00-local.t
Labels: bug, small

#5483 task_job_mgr: move compute out of open call
  cylc/flow/task_job_mgr.py
Labels: small, efficiency

#5475 data-store graph walk restricted
  cylc/flow/data_store_mgr.py
Labels: efficiency

#5486 platforms: use cached global config
  cylc/flow/platforms.py
Labels: efficiency

#5371 syntax: small changes to vim highlighting
  cylc/flow/etc/syntax/cylc.vim
  etc/syntax/reference-files/flow.cylc
Labels: small

#5334 Apply prerequisite changes to spawned tasks, on reload & restart
  CHANGES.md
  cylc/flow/data_store_mgr.py
  cylc/flow/task_pool.py
  cylc/flow/task_proxy.py
  tests/integration/test_scheduler.py
  tests/integration/test_task_pool.py
  tests/integration/utils/flow_tools.py
Labels: bug

#5494 swarm: fix docker builds
  .dockerignore
  dockerfiles/cylc-dev/Dockerfile
  dockerfiles/cylc-remote/Dockerfile
  tests/functional/events/11-cycle-task-event-job-logs-retrieve.t
  tests/functional/events/11-cycle-task-event-job-logs-retrieve/flow.cylc
Labels: infrastructure

#5466 Avoid duplicate prerequisites from multiple recurrences.
  CHANGES.md
  cylc/flow/prerequisite.py
  cylc/flow/task_state.py
  cylc/flow/task_trigger.py
  tests/unit/test_task_state.py
Labels: bug
