Repository cylc/cylc-flow, pull requests merged in 2023-06, with the labels that each got.

#5563 fix changelog
  CHANGES.md
Labels: small

#5565 cat-log: handle filenames with spaces
  cylc/flow/scripts/cat_log.py
  tests/functional/cylc-cat-log/00-local.t
  tests/functional/cylc-cat-log/00-local/flow.cylc
Labels: bug, small

#5574 log_vc_info: catch info command errors and present them as warnings
  cylc/flow/__init__.py
  cylc/flow/install_plugins/log_vc_info.py
  cylc/flow/scripts/install.py
  cylc/flow/workflow_files.py
  tests/unit/post_install/test_log_vc_info.py
Labels: small, could be better

#5582 Allow pre configure plugin to access compat mode info in cylc install.
  CHANGES.md
  cylc/flow/scripts/install.py
  cylc/flow/scripts/validate_install_play.py
  cylc/flow/workflow_files.py
  tests/integration/test_install.py
Labels: bug, small

#5523 data_store: reduce the cost of creating prerequisite objects
  cylc/flow/data_store_mgr.py
  cylc/flow/id.py
  cylc/flow/prerequisite.py
Labels: small, efficiency

#5590 Fix missing line break in docs
  cylc/flow/scripts/lint.py
Labels: bug, small, doc

#5594 Simplify one functional test.
  tests/functional/job-submission/15-garbage-platform-command-2.t
  tests/functional/job-submission/15-garbage-platform-command-2/flow.cylc
  tests/functional/job-submission/15-garbage-platform-command-2/reference.log
Labels: small

#5597 Fix simulation mode TypeError
  cylc/flow/task_pool.py
Labels: bug, small

#5584 Stop Unit tests symlinking on workflow installation
  tests/unit/conftest.py
  tests/unit/test_install.py
Labels: testing

#5570 Fix runtime environment (scheduler, validation, etc.)
  cylc/flow/config.py
  tests/unit/test_config.py
Labels: bug, small

#5604 pool: fix infinite loop with --start-cycle-point
  CHANGES.md
  cylc/flow/cycling/iso8601.py
  cylc/flow/scheduler.py
  cylc/flow/task_pool.py
  tests/integration/test_task_pool.py
Labels: bug

#5372 Remove upper pin on setuptools
  conda-environment.yml
  setup.cfg
Labels: small, dependencies
