Repository cylc/cylc-flow, pull requests merged in 2023-07, with the labels that each got.

#5611 schema: add more documentation
  CHANGES.md
  cylc/flow/network/schema.py
Labels: doc

#5592 reload: wait for pending tasks to submit and pause the workflow
  CHANGES.md
  cylc/flow/scheduler.py
  cylc/flow/task_pool.py
  cylc/flow/workflow_status.py
  tests/conftest.py
  tests/functional/logging/01-basic.t
  tests/functional/reload/09-garbage.t
  tests/integration/test_reload.py
  tests/integration/test_resolvers.py
  tests/integration/test_scheduler.py
  tests/integration/test_task_pool.py
  tests/unit/test_workflow_status.py
Labels: bug

#5589 cd to workflow dir during file parsing.
  CHANGES.md
  cylc/flow/parsec/fileparse.py
  tests/unit/parsec/test_fileparse.py
Labels: small

#5617 ensure output from xtrigger scripts are logged
  cylc/flow/parsec/validate.py
  cylc/flow/subprocctx.py
  tests/integration/test_subprocctx.py
Labels: bug

#5625 blacklist setuptools v67
  CHANGES.md
  conda-environment.yml
  setup.cfg
Labels: bug, dependencies

#5614 pool: prevent no-flow tasks from spawning downstreams in compat mode
  CHANGES.md
  cylc/flow/task_pool.py
  tests/integration/test_task_pool.py
Labels: bug

#5624 misc
  cylc/flow/cfgspec/globalcfg.py
  cylc/flow/cfgspec/workflow.py
  cylc/flow/clean.py
  cylc/flow/config.py
  cylc/flow/install.py
  cylc/flow/network/__init__.py
  cylc/flow/network/authentication.py
  cylc/flow/network/client_factory.py
  cylc/flow/pathutil.py
  cylc/flow/scheduler.py
  cylc/flow/scripts/clean.py
  cylc/flow/scripts/graph.py
  cylc/flow/scripts/install.py
  cylc/flow/scripts/message.py
  cylc/flow/scripts/remote_init.py
  cylc/flow/scripts/scan.py
  cylc/flow/task_message.py
  cylc/flow/task_remote_cmd.py
  cylc/flow/tui/app.py
  cylc/flow/workflow_files.py
  tests/integration/conftest.py
  tests/integration/events/test_workflow_events.py
  tests/integration/graphql/test_root.py
  tests/integration/main_loop/test_auto_restart.py
  tests/integration/test_client.py
  tests/integration/test_config.py
  tests/integration/test_data_store_mgr.py
  tests/integration/test_examples.py
  tests/integration/test_graphql.py
  tests/integration/test_install.py
  tests/integration/test_publisher.py
  tests/integration/test_resolvers.py
  tests/integration/test_scan.py
  tests/integration/test_scan_api.py
  tests/integration/test_scheduler.py
  tests/integration/test_server.py
  tests/integration/test_task_events_mgr.py
  tests/integration/test_task_job_mgr.py
  tests/integration/test_task_pool.py
  tests/integration/test_workflow_db_mgr.py
  tests/integration/test_workflow_files.py
  tests/integration/utils/flow_tools.py
  tests/integration/utils/test_flow_tools.py
  tests/unit/conftest.py
  tests/unit/test_clean.py
  tests/unit/test_config.py
  tests/unit/test_install.py
  tests/unit/test_pathutil.py
  tests/unit/test_task_remote_mgr.py
  tests/unit/test_taskdef.py
  tests/unit/test_workflow_files.py
  tests/unit/xtriggers/test_workflow_state.py
Labels: small

#5616 pbs: trim trailing text from job ids
  CHANGES.md
  cylc/flow/job_runner_handlers/pbs.py
  cylc/flow/job_runner_mgr.py
  tests/unit/job_runner_handlers/test_pbs.py
Labels: bug

#5629 doc: explain whitespace in env vars
  cylc/flow/cfgspec/workflow.py
Labels: small, doc

#5633 Fix changelog [skip ci]
  CHANGES.md
Labels: small

#5631 Fix `cylc clean` remote re-invocation bug
  changes.d/5631.fix.md
  cylc/flow/clean.py
  cylc/flow/command_polling.py
  cylc/flow/scheduler_cli.py
  cylc/flow/scripts/clean.py
  cylc/flow/scripts/cycle_point.py
  cylc/flow/scripts/ext_trigger.py
  cylc/flow/scripts/scan.py
  tests/functional/cylc-clean/01-remote.t
  tests/unit/test_clean.py
Labels: bug, small

#5634 Use towncrier for changelog generation
  .github/workflows/1_create_release_pr.yml
  .github/workflows/test_fast.yml
  CHANGES.md
  CONTRIBUTING.md
  changes.d/changelog-template.jinja
  pyproject.toml
  setup.cfg
Labels: infrastructure

#5648 Fix style
  etc/bin/swarm
Labels: small

#5647 Bump dev version 8.3.0.dev
  cylc/flow/__init__.py
Labels: small

#5649 GH Actions: sync PR improvements
  .github/workflows/branch_sync.yml
Labels: infrastructure
