Repository cylc/cylc-flow, pull requests merged in 2023-10, with the labels that each got.

#5755 opt outputs: submitted is implicitly required
  changes.d/5755.fix.md
  cylc/flow/task_outputs.py
  cylc/flow/task_pool.py
  tests/functional/intelligent-host-selection/02-badhosts/flow.cylc
  tests/functional/spawn-on-demand/18-submitted.t
  tests/functional/spawn-on-demand/18-submitted/flow.cylc
  tests/functional/spawn-on-demand/18-submitted/reference.log
  tests/integration/test_task_pool.py
Labels: bug

#5756 Improve CLI 'Done' stdout.
  cylc/flow/network/multi.py
Labels: could be better

#5753 Fix execution time limit polling intervals [cylc 8]
  changes.d/5753.fix.md
  cylc/flow/task_events_mgr.py
  tests/integration/test_task_events_mgr.py
Labels: bug

#5760 Dump timeout
  cylc/flow/network/client.py
  cylc/flow/scripts/dump.py
Labels: small

#5748 clarify SLURM job handler docs
  cylc/flow/job_runner_handlers/slurm.py
Labels: doc

#5747 Fix.cycle task states query
  CHANGES.md
  lib/cylc/review_dao.py
Labels: bug, small

#5776 back-compat: submitted is implicitly required
  changes.d/5776.fix.md
  cylc/flow/task_pool.py
  tests/functional/spawn-on-demand/19-submitted-compat.t
Labels: bug, small

#5715 Fix data-store reloaded flag
  cylc/flow/data_store_mgr.py
  cylc/flow/network/resolvers.py
  cylc/flow/scheduler.py
Labels: small

#5778 Allow isodatetime 3.1
  conda-environment.yml
  setup.cfg
Labels: small, dependencies

#5786 Use cylc/release-actions branch-sync reusable workflow
  .github/workflows/branch_sync.yml
Labels: infrastructure

#5727 Cylc to ignore PYTHONPATH: Use CYLC_PYTHONPATH for custom Python for Cylc
  changes.d/5727.break.md
  cylc/flow/etc/tutorial/cylc-forecasting-workflow/etc/python-job.settings
  cylc/flow/scripts/cylc.py
  tests/unit/scripts/test_cylc.py
Labels: bug

#5712 Test the simulation mode code.
  cylc/flow/cfgspec/workflow.py
  cylc/flow/config.py
  cylc/flow/scheduler.py
  cylc/flow/simulation.py
  cylc/flow/task_events_mgr.py
  cylc/flow/task_job_mgr.py
  cylc/flow/task_pool.py
  tests/functional/modes/03-simulation.t
  tests/functional/modes/03-simulation/flow.cylc
  tests/functional/modes/03-simulation/reference.log
  tests/integration/test_simulation.py
  tests/unit/test_config.py
  tests/unit/test_simulation.py
Labels: could be better

#5744 respond to @joehickson comments
  cylc/flow/etc/tutorial/runtime-tutorial/flow.cylc
Labels: doc

#5797 Exclude broken pytest-asyncio version; remove pytest-mock
  setup.cfg
  tests/unit/test_id_cli.py
Labels: small

#5796 Fix test polluted by env vars
  tests/unit/test_remote.py
Labels: small
