Repository cylc/cylc-flow, pull requests merged in 2024-07, with the labels that each got.

#6183 Tests: fix `contains_ok` UTF-8 issue
  tests/functional/lib/bash/test_header
Labels: small

#6188 flake8-comprehensions
  cylc/flow/network/schema.py
  cylc/flow/task_outputs.py
  cylc/flow/tui/updater.py
Labels: small

#6178 tui: prevent hang on shutdown
  changes.d/fix.6178.md
  cylc/flow/tui/app.py
Labels: bug, small

#6182 tui: improve --comms-timeout documentation
  cylc/flow/scripts/tui.py
  cylc/flow/tui/updater.py
Labels: small, doc

#5411 portability: permit arpa address
  cylc/flow/hostuserutil.py
Labels: investigation

#6176 Ensure jobs are created if task is in waiting state
  changes.d/6176.fix.md
  cylc/flow/task_events_mgr.py
  tests/integration/test_task_events_mgr.py
Labels: bug

#6200 Fix stall status bug
  changes.d/6200.fix.md
  cylc/flow/commands.py
  cylc/flow/data_store_mgr.py
  cylc/flow/scheduler.py
  cylc/flow/tui/util.py
  cylc/flow/wallclock.py
  cylc/flow/workflow_status.py
  tests/unit/test_workflow_status.py
Labels: bug

#6206 sequential clock spawning fix
  changes.d/6206.fix.md
  cylc/flow/xtrigger_mgr.py
  tests/integration/test_xtrigger_mgr.py
Labels: bug, small

#6115 flow-nums data-store fix
  cylc/flow/data_store_mgr.py
  tests/functional/cylc-show/06-past-present-future.t
Labels: bug, small

#6137 Lint.job runner specific timeout
  changes.d/6137.feat.md
  cylc/flow/job_runner_handlers/loadleveler.py
  cylc/flow/job_runner_handlers/lsf.py
  cylc/flow/job_runner_handlers/moab.py
  cylc/flow/job_runner_handlers/pbs.py
  cylc/flow/job_runner_handlers/sge.py
  cylc/flow/job_runner_handlers/slurm.py
  cylc/flow/scripts/lint.py
  tests/unit/scripts/test_lint.py
Labels: small

#6186 `cylc set` bug fix for new flows
  changes.d/6186.fix.md
  cylc/flow/scripts/set.py
  cylc/flow/task_pool.py
  tests/integration/test_dbstatecheck.py
  tests/integration/test_task_pool.py
Labels: bug

#6215 fix towncrier message
  changes.d/6178.fix.md
Labels: small

#6212 tests/i: remove sleep
  tests/integration/test_dbstatecheck.py
Labels: small

#6185 tests/f: make shutdown/08 more explicit
  tests/functional/shutdown/08-now1/flow.cylc
Labels: small

#6220 Correct changelog [skip ci]
  CHANGES.md
Labels: small

#6228 install: fix colour formatting
  cylc/flow/scripts/install.py
Labels: bug, small

#6229 runahead: handle a workflow with an empty graph
  cylc/flow/task_pool.py
  tests/integration/test_task_pool.py
Labels: bug, small

#6223 example: extending workflow
  cylc/flow/etc/examples/extending-workflow/.validate
  cylc/flow/etc/examples/extending-workflow/index.rst
  cylc/flow/etc/examples/extending-workflow/simple/flow.cylc
Labels: doc

#6234 clean: change DB corruption advice
  cylc/flow/clean.py
Labels: small, doc

#6233 stop: remove reference to Cylc 7 --mode option
  cylc/flow/scripts/stop.py
Labels: doc

#6238 doc: add link to task comms section
  cylc/flow/cfgspec/globalcfg.py
Labels: small, doc

#6242 add share/bin to env path
  changes.d/6242.fix.md
  cylc/flow/config.py
Labels: small

#6235 messages: enforce unique task messages
  cylc/flow/config.py
  tests/integration/validate/test_outputs.py
Labels: small

#6103 data store: add absolute graph edges
  6103.fix.md
  cylc/flow/taskdef.py
  tests/integration/test_data_store_mgr.py
Labels: bug

#6241 flow merge for force-triggered n=0 (e.g. queued) tasks
  changes.d/6241.fix.md
  cylc/flow/data_store_mgr.py
  cylc/flow/task_pool.py
  tests/integration/test_task_pool.py
Labels: bug

#6249 glbl_cfg: reload without mutating the original
  changes.d/6249.fix.md
  cylc/flow/cfgspec/glbl_cfg.py
  cylc/flow/cfgspec/globalcfg.py
  tests/integration/test_config.py
Labels: bug

#6252 Logging: do not access global config object during emit
  cylc/flow/loggingutil.py
  tests/unit/test_loggingutil.py
Labels: bug

#6269 Upgrade towncrier
  pyproject.toml
  setup.cfg
Labels: small, infrastructure, dependencies

#6271 Fix help text colour for CLI options
  cylc/flow/option_parsers.py
  cylc/flow/terminal.py
Labels: small

#6168 Allow Symlinking for log/job
  changes.d/feat.6168.md
  cylc/flow/cfgspec/globalcfg.py
  cylc/flow/pathutil.py
  cylc/flow/workflow_files.py
  tests/functional/cylc-clean/00-basic.t
  tests/functional/cylc-clean/01-remote.t
  tests/functional/cylc-install/01-symlinks.t
  tests/functional/remote/04-symlink-dirs.t
  tests/unit/test_pathutil.py
Labels: config change
