Repository cylc/cylc-flow, pull requests merged in 2024-04, with the labels that each got.

#6031 Fix workflow-state alternate run-dir
  changes.d/6031.fix.md
  cylc/flow/id_cli.py
  cylc/flow/pathutil.py
  cylc/flow/scripts/workflow_state.py
  cylc/flow/workflow_files.py
  cylc/flow/xtriggers/workflow_state.py
  tests/unit/test_id_cli.py
  tests/unit/xtriggers/test_workflow_state.py
Labels: bug

#6047 tutorial: make the tutorial workflow run a little slower
  cylc/flow/etc/tutorial/cylc-forecasting-workflow/bin/consolidate-observations
  cylc/flow/etc/tutorial/cylc-forecasting-workflow/bin/forecast
  cylc/flow/etc/tutorial/cylc-forecasting-workflow/bin/get-observations
  cylc/flow/etc/tutorial/cylc-forecasting-workflow/bin/get-rainfall
  cylc/flow/etc/tutorial/cylc-forecasting-workflow/bin/post-process
  cylc/flow/etc/tutorial/cylc-forecasting-workflow/lib/python/util.py
  cylc/flow/etc/tutorial/runtime-tutorial/flow.cylc
Labels: small, tutorial-workflows

#6051 update documentation for string templates on "External Triggers" page
  .mailmap
  CONTRIBUTING.md
  cylc/flow/xtrigger_mgr.py
Labels: doc

#6063 tests/integration: address urwid deprecation warning
  tests/integration/tui/conftest.py
Labels: small

#6068 Play should have no cylc rose options
  changes.d/6068.break.md
  cylc/flow/scheduler.py
  cylc/flow/scheduler_cli.py
Labels: bug, small

#6072 cylc.nanorc
  changes.d/6072.feat.md
  cylc/flow/etc/syntax/cylc.nanorc
Labels: small

#6071 Include xtrigger function signatures in `cylc config`
  changes.d/6071.fix.md
  cylc/flow/subprocctx.py
  cylc/flow/xtrigger_mgr.py
  tests/integration/test_subprocctx.py
  tests/unit/scripts/test_config.py
Labels: small

#6070 Delete public DB if private DB does not exist on scheduler start
  cylc/flow/scheduler.py
Labels: bug?, small

#6021 Fix terminal/log color issues
  cylc/flow/option_parsers.py
  cylc/flow/scripts/lint.py
  cylc/flow/task_state_prop.py
  cylc/flow/terminal.py
  tests/unit/test_task_state_prop.py
  tests/unit/test_terminal.py
Labels: bug, small

#6078 `cylc lint` S007: fix regex catastrophic backtracking
  changes.d/6078.fix.md
  cylc/flow/scripts/lint.py
  tests/unit/scripts/test_lint.py
Labels: bug, small

#6080 Fix Nano syntax highlighter installation instruction
  cylc/flow/etc/syntax/cylc.nanorc
Labels: small

#6084 Improve xrandom validate function docstring
  cylc/flow/xtriggers/xrandom.py
Labels: small, doc

#6067 Distinguish never-spawned from never-submitted.
  changes.d/6067.fix.md
  cylc/flow/task_events_mgr.py
  cylc/flow/task_pool.py
  tests/functional/cylc-set/02-off-flow-out.t
  tests/functional/execution-time-limit/04-polling-intervals.t
  tests/functional/hold-release/05-release.t
  tests/functional/spawn-on-demand/09-set-outputs/flow.cylc
  tests/functional/triggering/15-suicide.t
  tests/functional/triggering/15-suicide/flow.cylc
  tests/functional/triggering/15-suicide/reference.log
  tests/functional/triggering/18-suicide-active.t
  tests/functional/triggering/18-suicide-active/flow.cylc
  tests/integration/test_task_events_mgr.py
  tests/integration/test_task_pool.py
Labels: bug

#5754 doc: clarify runahead limit
  cylc/flow/cfgspec/workflow.py
Labels: doc

#6086 Bump pytest-asyncio version
  .github/workflows/build.yml
  .github/workflows/test_fast.yml
  setup.cfg
Labels: infrastructure, dependencies

#6087 docs: reference active tasks entry in the glossary
  cylc/flow/cfgspec/workflow.py
Labels: doc
