Repository cylc/cylc-flow, pull requests merged in 2024-09, with the labels that each got.

#6175 workflow_state: reject invalid configurations
  changes.d/6175.fix.md
  cylc/flow/dbstatecheck.py
  cylc/flow/scripts/workflow_state.py
  cylc/flow/task_state.py
  cylc/flow/xtriggers/workflow_state.py
  tests/flakyfunctional/xtriggers/01-workflow_state/flow.cylc
  tests/functional/shutdown/08-now1/flow.cylc
  tests/functional/workflow-state/05-output.t
  tests/functional/workflow-state/07-message2.t
  tests/functional/workflow-state/11-multi.t
  tests/functional/workflow-state/11-multi/flow.cylc
  tests/unit/test_dbstatecheck.py
  tests/unit/xtriggers/test_workflow_state.py
Labels: bug

#6351 Fix.simulation mode started bug
  changes.d/6351.fix.md
  cylc/flow/task_events_mgr.py
  tests/integration/run_modes/test_simulation.py
Labels: bug

#6356 Flake8 B904
  cylc/flow/dbstatecheck.py
Labels: small

#6353 expiry: prevent expired tasks from retrying automatically
  changes.d/6353.fix.md
  cylc/flow/task_pool.py
  tests/integration/test_task_pool.py
Labels: bug, small

#6196 Command validation: include more in validation step
  cylc/flow/command_validation.py
  cylc/flow/commands.py
  cylc/flow/scripts/trigger.py
Labels: small

#6357 Fix potential type error & a few small mistakes
  cylc/flow/data_store_mgr.py
  cylc/flow/task_events_mgr.py
  cylc/flow/task_pool.py
  tests/integration/test_task_pool.py
Labels: bug?, small

#6364 `cylc clean`: fix bug where `--rm share` would not clean `share/cycle` symlink first
  changes.d/6364.fix.md
  cylc/flow/clean.py
  cylc/flow/pathutil.py
  tests/unit/filetree.py
  tests/unit/test_clean.py
  tests/unit/test_pathutil.py
Labels: bug, small

#6349 example: cycle on irregular intervals
  cylc/flow/etc/examples/cycle-over-irregular-dates/.validate
  cylc/flow/etc/examples/cycle-over-irregular-dates/index.rst
  cylc/flow/etc/examples/cycle-over-irregular-dates/inter-dependent/flow.cylc
  cylc/flow/etc/examples/cycle-over-irregular-dates/simple/flow.cylc
Labels: doc

#6384 fix typo
  cylc/flow/etc/examples/extending-workflow/index.rst
Labels: doc

#6382 Add ruff, black & isort configs
  cylc/flow/pathutil.py
  pyproject.toml
Labels: small

#6386 Use `flake8-implicit-str-concat`
  setup.cfg
  tox.ini
Labels: small, dependencies

#6376 subprocpool: populate missing 255 callback arguments
  changes.d/6376.fix.md
  cylc/flow/subprocpool.py
Labels: bug
