Repository cylc/cylc-flow, pull requests merged in 2024-03, with the labels that each got.

#6014 Upper-pin MyPy to <1.9
  setup.cfg
Labels: dependencies

#6008 Ensure task mail respects `[scheduler][mail]to/from`
  changes.d/6008.fix.md
  cylc/flow/scheduler.py
  cylc/flow/task_events_mgr.py
  cylc/flow/task_pool.py
  cylc/flow/workflow_events.py
  tests/integration/test_task_events_mgr.py
  tests/unit/test_db_compat.py
  tests/unit/test_subprocpool.py
  tests/unit/test_task_events_mgr.py
  tests/unit/test_task_events_mgr_2.py
  tests/unit/test_workflow_events.py
Labels: bug, db change

#6016 Fix type checking errors
  cylc/flow/clean.py
  cylc/flow/exceptions.py
  cylc/flow/task_remote_mgr.py
  cylc/flow/util.py
  cylc/flow/workflow_files.py
Labels: small

#6022 Remove burninated flake8 code
  tox.ini
Labels: small

#6027 Fix type annotation & tidy
  cylc/flow/rundb.py
  cylc/flow/task_pool.py
Labels: small

#6029 Preserve n-window depth on reload
  changes.d/6029.feat.md
  cylc/flow/data_store_mgr.py
  cylc/flow/network/resolvers.py
  tests/integration/test_data_store_mgr.py
Labels: small, could be better

#5738 parentless sequential xtrigger spawning
  changes.d/5738.feat.md
  cylc/flow/cfgspec/workflow.py
  cylc/flow/config.py
  cylc/flow/data_store_mgr.py
  cylc/flow/scheduler.py
  cylc/flow/subprocctx.py
  cylc/flow/task_pool.py
  cylc/flow/task_proxy.py
  cylc/flow/xtrigger_mgr.py
  cylc/flow/xtriggers/wall_clock.py
  tests/functional/cylc-config/00-simple/section1.stdout
  tests/functional/xtriggers/04-sequential.t
  tests/integration/test_config.py
  tests/integration/test_sequential_xtriggers.py
  tests/unit/test_xtrigger_mgr.py
Labels: efficiency, sod-follow-up, config change

#6032 Docs: add version-added admonition
  cylc/flow/cfgspec/workflow.py
Labels: small, doc

#5959 workflow events: fix an issue where "timeout" events would not fire
  changes.d/5959.fix.md
  cylc/flow/scheduler.py
  tests/integration/test_examples.py
  tests/integration/test_workflow_events.py
Labels: bug

#6038 Refactor run mode restart check to avoid unclosed DB connection
  cylc/flow/config.py
  cylc/flow/rundb.py
  cylc/flow/scheduler.py
  cylc/flow/scheduler_cli.py
  cylc/flow/scripts/validate.py
  cylc/flow/task_events_mgr.py
  cylc/flow/task_pool.py
  cylc/flow/workflow_status.py
  tests/integration/test_mode_on_restart.py
  tox.ini
Labels: could be better

#6017 Log subprocpool stdout/stderr at debug level
  cylc/flow/pathutil.py
  cylc/flow/subprocpool.py
  cylc/flow/task_events_mgr.py
  cylc/flow/task_job_mgr.py
  cylc/flow/xtrigger_mgr.py
  tests/functional/events/02-multi.t
  tests/integration/test_task_job_mgr.py
Labels: small

#5924 Error if graph has a dependency offset exclusively on the RHS
  changes.d/fix.5924.md
  cylc/flow/graph_parser.py
  tests/unit/test_graph_parser.py
Labels: bug

#6036 Fix.sim mode no increment
  changes.d/6036.fix.md
  cylc/flow/task_events_mgr.py
  tests/integration/test_task_events_mgr.py
Labels: bug, small
