Repository cylc/cylc-flow, pull requests merged in 2024-06, with the labels that each got.

#6121 Fix tests
  tests/integration/test_data_store_mgr.py
  tests/integration/test_graphql.py
  tests/integration/test_queues.py
  tests/integration/test_task_pool.py
Labels: small

#6124 Improve event handler doc
  cylc/flow/cfgspec/workflow.py
Labels: small, doc

#6123 Tokens: handle ISO 8601 long format cycle points
  changes.d/6123.fix.md
  cylc/flow/id.py
  cylc/flow/id_cli.py
  tests/unit/test_id.py
  tests/unit/test_id_cli.py
Labels: small, could be better

#6109 platforms: fix unreachable hosts not reset on platform group failure
  changes.d/fix.6109.md
  cylc/flow/exceptions.py
  cylc/flow/platforms.py
  cylc/flow/task_job_mgr.py
  cylc/flow/task_remote_mgr.py
  tests/integration/test_platforms.py
Labels: bug

#6134 Fix ID workflow count.
  cylc/flow/id_cli.py
  tests/unit/test_id_cli.py
Labels: bug

#6144 client: fix SSH client
  cylc/flow/network/ssh_client.py
Labels: bug

#6148 fix lint error
  cylc/flow/network/ssh_client.py
Labels: small

#6138 Fix xtrigger `sequential` arg validation & improve docs
  cylc/flow/dbstatecheck.py
  cylc/flow/task_outputs.py
  cylc/flow/xtrigger_mgr.py
  cylc/flow/xtriggers/wall_clock.py
  cylc/flow/xtriggers/workflow_state.py
  tests/integration/test_dbstatecheck.py
  tests/integration/test_sequential_xtriggers.py
  tests/unit/test_db_compat.py
Labels: bug, small, doc

#6150 Test fixes
  tests/functional/cylc-cat-log/01-remote.t
  tests/functional/events/11-cycle-task-event-job-logs-retrieve.t
  tests/functional/reload/24-reload-file-install.t
Labels: small

#6152 xtriggers: doc change
  cylc/flow/xtriggers/workflow_state.py
Labels: doc

#6156 Improve error logging for contact file checks.
  cylc/flow/workflow_files.py
Labels: small

#6159 Master Points to 8.4.0
  cylc/flow/__init__.py
Labels: small

#6160 Xtrigger validation: log traceback for unexpected user validation errors
  cylc/flow/xtrigger_mgr.py
Labels: small, could be better

#6130 Prevent commands which take Tasks IDs taking Job IDs.
  changes.d/6130.fix.md
  cylc/flow/command_validation.py
  cylc/flow/commands.py
Labels: small

#6163 `cylc version --long`: ensure correct path is printed for `cylc` executable
  cylc/flow/scripts/cylc.py
  tests/functional/cli/01-help.t
Labels: small, could be better

#6170 play: print the logo to the user's terminal only
  changes.d/fix.6170.md
  cylc/flow/scheduler_cli.py
Labels: bug

#6179 Fix mistake in changelog
  CHANGES.md
  changes.d/6170.fix.md
  changes.d/fix.5924.md
  changes.d/fix.6109.md
Labels: small

#6181 `cylc stop --now`: fix flaky test & clarify docs
  cylc/flow/scripts/stop.py
  tests/functional/shutdown/08-now1.t
  tests/functional/shutdown/08-now1/flow.cylc
Labels: small
