Repository cylc/cylc-flow, pull requests merged in 2024-01, with the labels that each got.

#5896 id: catch traceback in ID parsing
  cylc/flow/id_cli.py
Labels: bug, small

#5903 coverage: exclude report-timings and set 90% as the lower limit
  .codecov.yml
  .coveragerc
Labels: small

#5854 set CYLC_DEBUG env var when set-verbosity DEBUG
  cylc/flow/option_parsers.py
  tests/functional/cli/03-set-verbosity.t
Labels: bug

#5906 Added missing union type import
  cylc/flow/log_level.py
  cylc/flow/option_parsers.py
Labels: small

#5893 Simplify and fix runahead computation.
  .github/workflows/test_fast.yml
  changes.d/5893.fix
  cylc/flow/cycling/__init__.py
  cylc/flow/cycling/iso8601.py
  cylc/flow/task_pool.py
  pytest.ini
  setup.cfg
  tests/integration/test_task_pool.py
  tests/unit/cycling/test_cycling.py
Labels: bug

#5909 Ensure that sys argv cleaner cleans up --workflow-name=foo
  changes.d/5909.fix.md
  cylc/flow/option_parsers.py
  tests/unit/test_option_parsers.py
Labels: bug

#5902 Made execution time limit unsettable by reload or broadcast.
  changes.d/5902.fix.md
  cylc/flow/task_job_mgr.py
  tests/integration/test_task_job_mgr.py
Labels: bug

#5908 xtrigger efficiency fix.
  changes.d/5908.fix.md
  cylc/flow/rundb.py
  cylc/flow/scheduler.py
  cylc/flow/workflow_db_mgr.py
  cylc/flow/xtrigger_mgr.py
  setup.cfg
  tests/functional/xtriggers/02-persistence/flow.cylc
  tests/integration/test_xtrigger_mgr.py
  tests/unit/conftest.py
  tests/unit/test_xtrigger_mgr.py
Labels: bug, efficiency

#5915 xtriggers: test db / restart interaction
  tests/integration/test_xtrigger_mgr.py
Labels: small

#5901 Tests.move deprecations tests to integration battery
  tests/functional/deprecations/00-pre-cylc8.t
  tests/functional/deprecations/00-pre-cylc8/flow.cylc
  tests/functional/deprecations/04-simple-graph.t
  tests/integration/scripts/test_validate_integration.py
  tests/integration/utils/flow_tools.py
Labels: could be better

#5925 Turn off flake8-bugbear check 038 becuase it gave false positives.
  tox.ini
Labels: small

#5914 resolvers: optimize "uniq" iteration
  cylc/flow/network/resolvers.py
Labels: small, efficiency

#5929 tui: handle client timeout more elegantly and make it configurable
  cylc/flow/scripts/tui.py
  cylc/flow/tui/app.py
  cylc/flow/tui/updater.py
Labels: small, could be better

#5933 Fix bugs in `cylc broadcast`
  changes.d/5933.fix.md
  cylc/flow/parsec/validate.py
  cylc/flow/scripts/broadcast.py
  tests/functional/broadcast/10-file-1/broadcast.cylc
  tests/unit/parsec/test_validate.py
Labels: bug

#5873 Lint packaged workflows
  changes.d/5873.feat.md
  cylc/flow/etc/tutorial/consolidation-tutorial/.validate
  cylc/flow/etc/tutorial/cylc-forecasting-workflow/.validate
  cylc/flow/etc/tutorial/retries-tutorial/.validate
  cylc/flow/etc/tutorial/retries-tutorial/flow.cylc
  cylc/flow/etc/tutorial/runtime-introduction/.validate
  cylc/flow/scripts/lint.py
  tests/unit/scripts/test_lint.py
Labels: could be better

#5951 doc: correct spelling
  cylc/flow/etc/examples/event-driven-cycling/README.rst
Labels: small, doc

#5886 Tidy network code
  cylc/flow/network/schema.py
Labels: small
