Repository cylc/cylc-flow, pull requests merged in 2024-08, with the labels that each got.

#6257 Fix flaky integration tests
  .github/workflows/test_functional.yml
  tests/conftest.py
  tests/integration/conftest.py
Labels: small

#6280 Fix changelog fragment name
  changes.d/6168.feat.md
Labels: small

#6277 Skip some failing functional tests on MacOS GH Actions runner
  tests/functional/flow-triggers/11-wait-merge.t
  tests/functional/lib/bash/test_header
  tests/functional/modes/04-simulation-runtime.t
Labels: small, infrastructure

#6267 `cylc play` (restart): fix bug affecting run host reinvocation after interactive upgrade
  changes.d/6267.fix.md
  cylc/flow/scheduler_cli.py
  tests/unit/test_scheduler_cli.py
Labels: bug

#6287 `TaskState`: remove cached prereq satisfaction in preparation for `cylc remove`
  cylc/flow/task_pool.py
  cylc/flow/task_state.py
Labels: code refactor

#6294 Demote "timer stopped" warning to info & fix functional tests `contains_ok` function
  cylc/flow/timer.py
  tests/functional/lib/bash/test_header
  tests/unit/test_timer.py
Labels: small

#6264 Check run name as well as workflow name in Cylc install
  changes.d/6264.fix.md
  cylc/flow/install.py
  tests/unit/test_install.py
Labels: bug, small

#6300 Functional tests: fix unbound env var failure
  tests/functional/lib/bash/test_header
Labels: small

#6278 examples: extending workflow
  cylc/flow/etc/examples/extending-workflow/index.rst
Labels: small, doc

#6299 schema: minor docs changes
  cylc/flow/network/schema.py
Labels: small, doc

#6311 Flake8: remove wrongly ignored error code
  tox.ini
Labels: small

#6312 flake8-bugbear: opt-in to a couple of opinionated warnings
  cylc/flow/config.py
  cylc/flow/dbstatecheck.py
  cylc/flow/main_loop/health_check.py
  cylc/flow/network/__init__.py
  cylc/flow/param_expand.py
  cylc/flow/scripts/cylc.py
  cylc/flow/scripts/lint.py
  cylc/flow/scripts/report_timings.py
  cylc/flow/workflow_db_mgr.py
  cylc/flow/workflow_files.py
  cylc/flow/xtrigger_mgr.py
  tests/unit/scripts/test_lint.py
  tox.ini
Labels: small

#6309 GH Actions: include hidden files when uploading `~/cylc-run` artifact
  .github/workflows/bash.yml
  .github/workflows/test_fast.yml
  .github/workflows/test_functional.yml
Labels: small, infrastructure

#6214 fix.lint.U013 incomplete message
  changes.d/6214.fix.md
  cylc/flow/scripts/lint.py
  tests/unit/scripts/test_lint_checkers.py
Labels: bug, small

#6322 param expand: efficiency improvements
  cylc/flow/param_expand.py
Labels: small, efficiency

#6310 play: fix spurious traceback observed on some systems
  changes.d/6310.fix.md
  cylc/flow/scheduler_cli.py
  cylc/flow/scripts/validate_install_play.py
  cylc/flow/scripts/validate_reinstall.py
Labels: bug

#6321 Prevent a couple of unit tests from installing into `~/cylc-run`
  tests/unit/conftest.py
  tests/unit/test_clean.py
  tests/unit/test_install.py
Labels: small

#6324 Ensure that lint S014 has a proper test.
  cylc/flow/scripts/lint.py
Labels: small

#6305 Remove `c` char from prereq API dump
  cylc/flow/prerequisite.py
  tests/flakyfunctional/cylc-show/00-simple.t
Labels: small

#6289 jinja2: removed excessive context from Jinja2 raise/assert statements
  changes.d/6289.feat.md
  cylc/flow/parsec/jinja2support.py
  tests/functional/jinja2/03-bad.t
  tests/functional/jinja2/10-builtin-functions.t
  tests/functional/jinja2/10-builtin-functions/flow.cylc
  tests/functional/jinja2/include-exception/flow.cylc
  tests/functional/jinja2/include-exception/foo.cylc
  tests/integration/validate/test_jinja2.py
  tests/unit/parsec/test_jinja2support.py
Labels: small, could be better

#6332 Added f to format string
  .mailmap
  CONTRIBUTING.md
  changes.d/6332.fix.md
  cylc/flow/graph_parser.py
Labels: bug

#6327 Correctly reset log level when temporarily changing it
  cylc/flow/install.py
  cylc/flow/loggingutil.py
  cylc/flow/tui/util.py
  tests/unit/test_loggingutil.py
Labels: small, could be better

#6337 Fix duplicate job submissions.
  changes.d/6337.fix.md
  cylc/flow/task_queues/__init__.py
  cylc/flow/task_queues/independent.py
  tests/integration/test_task_pool.py
Labels: bug

#6340 Minor test follow-up
  tests/unit/test_loggingutil.py
Labels: small

#6335 broadcast: fix issue with multiple namespaces
  changes.d/6335.fix.md
  cylc/flow/broadcast_mgr.py
  cylc/flow/scripts/broadcast.py
  tests/integration/scripts/test_broadcast.py
Labels: bug
