Repository cylc/cylc-flow, pull requests merged in 2024-12, with the labels that each got.

#6511 cat-log list-dir mode: fail gracefully
  changes.d/6511.fix.md
  cylc/flow/scripts/cat_log.py
  tests/integration/scripts/test_cat_log.py
Labels: bug, small

#6503 convert from ids to tokens
  cylc/flow/scheduler.py
Labels: small

#6514 remove: enable command for stopping workflows
  cylc/flow/network/schema.py
Labels: small

#6516 Fix KeyError when using `cylc remove` after a reload changed the graph
  cylc/flow/config.py
  cylc/flow/scheduler.py
  cylc/flow/task_pool.py
  cylc/flow/taskdef.py
  cylc/flow/workflow_db_mgr.py
  tests/integration/test_optional_outputs.py
  tests/integration/test_reload.py
  tests/integration/test_remove.py
  tests/integration/test_stop_after_cycle_point.py
  tests/integration/test_task_pool.py
  tests/integration/utils/flow_tools.py
Labels: bug

#6528 Start-tasks: wait on xtriggers
  changes.d/6528.fix.md
  cylc/flow/scheduler.py
  cylc/flow/scheduler_cli.py
  tests/functional/cylc-play/05-start-task.t
  tests/functional/cylc-play/05-start-task/flow.cylc
  tests/functional/cylc-play/05-start-task/reference.log
  tests/integration/test_task_pool.py
Labels: small

#6526 Fix output consistency check when there are offsets.
  changes.d/6526.fix.md
  cylc/flow/graph_parser.py
  tests/flakyfunctional/cylc-show/04-multi.t
  tests/functional/graphing/06-family-or.t
  tests/integration/reftests/test_pre_initial.py
  tests/unit/test_graph_parser.py
Labels: bug
