Repository cylc/cylc-flow, pull requests merged in 2024-05, with the labels that each got.

#6095 Add "valid for" states to schema def for `cylc set`
  cylc/flow/network/schema.py
  tests/unit/network/test_schema.py
Labels: small, doc

#6096 prune suicide edges fix
  changes.d/6096.fix.md
  cylc/flow/data_store_mgr.py
Labels: bug, small

#6097 Add an option to the workflow config to force use of compat mode
  cylc/flow/config.py
  cylc/flow/workflow_files.py
  tests/unit/test_config.py
Labels: non-cylc bug

#6101 tests: reset global state before each test
  tests/conftest.py
Labels: small

#6102 `cylc vip/vr`: do not pass rose options to `cylc play`
  changes.d/6102.fix.md
  cylc/flow/option_parsers.py
  cylc/flow/scripts/validate_install_play.py
  cylc/flow/scripts/validate_reinstall.py
  tests/unit/test_option_parsers.py
Labels: bug, small

#6108 GH Actions: print towncrier draft in job summary
  .github/workflows/test_fast.yml
  changes.d/5873.feat.md
Labels: small, infrastructure

#6026 GraphQL: Improve schema error handling & tidy
  cylc/flow/network/graphql.py
  cylc/flow/network/resolvers.py
  cylc/flow/network/schema.py
Labels: small, code refactor

#6111 Fix mangled flow nums reported by data store for n>1 tasks
  cylc/flow/data_messages.proto
  cylc/flow/data_messages_pb2.py
  cylc/flow/data_messages_pb2.pyi
  cylc/flow/data_store_mgr.py
  cylc/flow/network/server.py
  cylc/flow/prerequisite.py
  cylc/flow/scripts/client.py
  mypy.ini
Labels: bug
