Repository cylc/cylc-flow, pull requests merged in 2024-11, with the labels that each got.

#6404 Pass pre-install plugins the value of workflow rundir
  cylc/flow/scripts/config.py
  cylc/flow/scripts/graph.py
  cylc/flow/scripts/list.py
  cylc/flow/scripts/validate.py
  cylc/flow/scripts/validate_reinstall.py
  cylc/flow/scripts/view.py
Labels: bug

#6463 Functional tests: allow `grep_fail` to accept options
  tests/functional/cli/05-colour.t
  tests/functional/lib/bash/test_header
Labels: small

#6457 Refactor task killing & simplify task state deltas
  cylc/flow/commands.py
  cylc/flow/data_store_mgr.py
  cylc/flow/scheduler.py
  cylc/flow/task_events_mgr.py
  cylc/flow/task_job_mgr.py
  cylc/flow/task_pool.py
  tests/integration/test_data_store_mgr.py
  tests/integration/tui/screenshots/test_task_states.filter-not-waiting-or-expired.html
  tests/integration/tui/screenshots/test_task_states.filter-not-waiting.html
  tests/integration/tui/screenshots/test_task_states.filter-submitted.html
  tests/integration/tui/screenshots/test_task_states.filter-waiting-or-expired.html
  tests/integration/tui/screenshots/test_task_states.unfiltered.html
Labels: small, code refactor

#6471 GH Actions shortlog: check out head ref
  .github/workflows/shortlog.yml
Labels: small, infrastructure

#6470 Db exception detail
  CONTRIBUTING.md
  cylc/flow/rundb.py
Labels: small

#6454 Remove `UTC mode` from tutorial workflows
  cylc/flow/etc/tutorial/consolidation-tutorial/flow.cylc
  cylc/flow/etc/tutorial/cylc-forecasting-workflow/flow.cylc
  cylc/flow/etc/tutorial/retries-tutorial/flow.cylc
  cylc/flow/etc/tutorial/runtime-introduction/flow.cylc
  cylc/flow/etc/tutorial/runtime-tutorial/flow.cylc
Labels: small, doc

#6484 Tweak 'cylc play' resume help.
  cylc/flow/workflow_files.py
Labels: small, could be better

#6482 coverage: fill some coverage holes
  cylc/flow/config.py
  cylc/flow/cycling/__init__.py
  cylc/flow/scripts/list.py
  tests/functional/cylc-config/09-platforms.t
  tests/functional/rnd/08-cylc-list.t
  tests/integration/scripts/test_list.py
  tests/integration/scripts/test_validate_integration.py
  tests/integration/test_config.py
  tests/integration/test_get_old_tvars.py
  tests/unit/cycling/test_integer.py
  tests/unit/cycling/test_iso8601.py
Labels: small

#6440 Modernise 'cylc dump -t' print format.
  changes.d/6440.feat.md
  cylc/flow/scripts/dump.py
  tests/flakyfunctional/hold-release/14-hold-kill/flow.cylc
  tests/flakyfunctional/restart/21-task-elapsed.t
  tests/functional/queues/qsize/flow.cylc
  tests/functional/reload/03-queues/flow.cylc
  tests/functional/runahead/06-release-update.t
  tests/functional/spawn-on-demand/13-trigger-runahead/flow.cylc
  tests/functional/spawn-on-demand/14-trigger-flow-blocker/flow.cylc
  tests/integration/scripts/test_dump.py
Labels: small, could be better

#6459 Lint: Tell users that backslashes are no longer necessary after => & |
  changes.d/6459.feat.md
  cylc/flow/scripts/lint.py
  tests/unit/scripts/test_lint.py
Labels: small

#6477 Fix workflow state docs
  cylc/flow/scripts/workflow_state.py
  cylc/flow/xtriggers/workflow_state.py
Labels: small, doc
