Repository cylc/cylc-flow, pull requests merged in 2025-09, with the labels that each got.

#6952 fix broadcast cancel error
  changes.d/6952.fix.md
  cylc/flow/cfgspec/workflow.py
  cylc/flow/scripts/broadcast.py
Labels: bug, small

#6947 Update ruff/black python target version to 3.12
  pyproject.toml
Labels: small

#6957 docs: always specify an interval with `cpu_percent`
  cylc/flow/cfgspec/globalcfg.py
  cylc/flow/host_select.py
Labels: doc

#6934 job log retrieval: remove duplicate logging
  cylc/flow/task_events_mgr.py
  tests/unit/test_task_events_mgr.py
Labels: small

#6835 Reimpliment suicide trigger as expire trigger
  changes.d/6835.feat.md
  cylc/flow/cfgspec/workflow.py
  cylc/flow/config.py
  cylc/flow/graph_parser.py
  cylc/flow/task_pool.py
  tests/integration/test_task_pool.py
Labels: bug

#6964 broadcast: reduce the broadcast expire limit
  changes.d/6964.feat.md
  cylc/flow/config.py
  cylc/flow/cycling/iso8601.py
  cylc/flow/scheduler.py
  pytest.ini
  tests/conftest.py
  tests/flakyfunctional/xtriggers/01-workflow_state.t
  tests/functional/broadcast/00-simple.t
  tests/integration/test_broadcast_mgr.py
Labels: small

#6842 Fix `cylc set` causing erroneous state changes
  changes.d/6842.fix.md
  cylc/flow/data_store_mgr.py
  cylc/flow/id.py
  cylc/flow/network/resolvers.py
  cylc/flow/run_modes/simulation.py
  cylc/flow/run_modes/skip.py
  cylc/flow/rundb.py
  cylc/flow/scheduler.py
  cylc/flow/task_events_mgr.py
  cylc/flow/task_job_logs.py
  cylc/flow/task_job_mgr.py
  cylc/flow/task_message.py
  cylc/flow/task_pool.py
  cylc/flow/task_proxy.py
  cylc/flow/workflow_db_mgr.py
  tests/functional/restart/20-event-retry/bin/my-handler
  tests/functional/restart/20-event-retry/flow.cylc
  tests/integration/scripts/test_set.py
  tests/integration/test_examples.py
  tests/integration/test_job_runner_mgr.py
  tests/integration/test_optional_outputs.py
  tests/integration/test_task_events_mgr.py
  tests/integration/test_task_job_mgr.py
  tests/unit/test_id.py
  tests/unit/test_task_proxy.py
Labels: bug, code refactor

#6986 doc: fix missing term
  cylc/flow/cfgspec/workflow.py
Labels: doc

#6989 profiler: fix minor plotting issue
  cylc/flow/main_loop/log_data_store.py
  cylc/flow/main_loop/log_memory.py
Labels: small

#6972 Update protobuf version pin
  setup.cfg
Labels: dependencies
