Repository cylc/cylc-flow, pull requests merged in 2025-07, with the labels that each got.

#6833 validation: correct flow validation failure message
  cylc/flow/command_validation.py
Labels: bug, small

#6854 demote warnings
  cylc/flow/commands.py
  cylc/flow/config.py
  cylc/flow/run_modes/skip.py
  cylc/flow/scheduler.py
  tests/integration/test_config.py
  tests/unit/run_modes/test_skip_units.py
Labels: small

#6852 no data-store n>0 flow num predictions
  changes.d/6852.fix.md
  cylc/flow/data_store_mgr.py
  cylc/flow/task_pool.py
  tests/integration/test_data_store_mgr.py
  tests/integration/test_increment_graph_window.py
  tests/integration/tui/screenshots/test_auto_expansion.later-time.html
  tests/integration/tui/screenshots/test_auto_expansion.on-load.html
  tests/integration/tui/screenshots/test_set_mutation.set-command-selected.html
  tests/integration/tui/test_app.py
Labels: small

#6880 Bump dev version
  cylc/flow/__init__.py
Labels: small

#6884 Actions: run shortlog weekly
  .github/workflows/shortlog.yml
  .mailmap
  CONTRIBUTING.md
Labels: small, infrastructure

#6889 Fix symlink dirs docs
  cylc/flow/cfgspec/globalcfg.py
Labels: small, doc
