Repository cylc/cylc-flow, pull requests merged in 2025-01, with the labels that each got.

#6530 Clarify trigger command help.
  cylc/flow/scripts/trigger.py
Labels: small

#6534 Fix flake8 E231
  .github/workflows/test_fast.yml
  cylc/flow/scripts/dump.py
  cylc/flow/scripts/show.py
Labels: small

#6538 GH Actions: test conda on min python version
  .github/workflows/test_conda-build.yml
Labels: small, infrastructure

#6533 Fix unlinking old job out/err files.
  cylc/flow/job_runner_mgr.py
  tests/integration/test_job_runner_mgr.py
Labels: bug, small

#6547 Bump dev version
  cylc/flow/__init__.py
Labels: small

#6522 GH Actions: automatically use latest `pypa/gh-action-pypi-publish`
  .github/workflows/2_auto_publish_release.yml
  .github/workflows/branch_sync.yml
  .github/workflows/test_conda-build.yml
Labels: small, infrastructure, dependencies

#6553 cli: correct --comms-timeout docs
  cylc/flow/option_parsers.py
  cylc/flow/scripts/tui.py
Labels: small, doc

#6117 Add `CYLC_TASK_SHARE_CYCLE_DIR` to task script.
  changes.d/6117.feat.md
  cylc/flow/etc/job.sh
  tests/functional/cylc-clean/01-remote.t
  tests/functional/jobscript/02-share-cycle-cycle.t
  tests/functional/jobscript/02-share-cycle-cycle/flow.cylc
Labels: small

#6555 Tidy `TaskJobManager`: remove unecessary `workflow` arg from many methods
  cylc/flow/commands.py
  cylc/flow/run_modes/__init__.py
  cylc/flow/run_modes/dummy.py
  cylc/flow/run_modes/simulation.py
  cylc/flow/run_modes/skip.py
  cylc/flow/scheduler.py
  cylc/flow/task_job_mgr.py
  tests/integration/conftest.py
  tests/integration/run_modes/test_mode_overrides.py
  tests/integration/run_modes/test_nonlive.py
  tests/integration/run_modes/test_simulation.py
  tests/integration/run_modes/test_skip.py
  tests/integration/test_job_runner_mgr.py
  tests/integration/test_platforms.py
  tests/integration/test_task_events_mgr.py
  tests/integration/test_task_job_mgr.py
Labels: code refactor

#6551 Lint S014: Only warn about `-W` when used for LSF
  changes.d/6551.fix.md
  cylc/flow/scripts/lint.py
Labels: bug, small

#6558 Deprecate async-timeout dependency
  conda-environment.yml
  cylc/flow/network/ssh_client.py
  setup.cfg
  tests/integration/test_publisher.py
  tests/integration/test_replier.py
  tests/integration/test_server.py
  tests/integration/test_workflow_events.py
  tests/integration/tui/test_updater.py
  tests/integration/utils/flow_tools.py
Labels: small, dependencies

#6562 GH Actions: don't fail fast
  .github/workflows/bash.yml
  .github/workflows/build.yml
  .github/workflows/test_conda-build.yml
  .github/workflows/test_tutorial_workflow.yml
Labels: small, infrastructure

#6566 doc: improve run host ranking docs
  cylc/flow/cfgspec/globalcfg.py
Labels: small, doc

#6569 pbs: update connection failed error message
  CHANGES.md
  lib/cylc/batch_sys_handlers/pbs.py
Labels: bug, small
