Repository cylc/cylc-flow, pull requests merged in 2025-04, with the labels that each got.

#6639 Kill foreground event handlers on timeout
  changes.d/6639.fix.md
  cylc/flow/subprocpool.py
  cylc/flow/workflow_events.py
  tests/integration/test_workflow_events.py
Labels: bug

#6691 set command: back out of bad prereqs
  changes.d/6691.fix.md
  cylc/flow/prerequisite.py
  cylc/flow/task_pool.py
  cylc/flow/taskdef.py
  tests/integration/scripts/test_set.py
  tests/integration/test_task_pool.py
  tests/unit/test_taskdef.py
Labels: bug

#6638 runahead: handle no sequences within start-stop cycle interval
  changes.d/6638.fix.md
  cylc/flow/task_pool.py
  tests/integration/test_task_pool.py
Labels: bug, small

#6709 Fix integration test sending mail
  tests/integration/events/__init__.py
  tests/integration/events/test_task_events.py
  tests/integration/events/test_workflow_events.py
  tests/integration/test_task_events_mgr.py
  tests/integration/test_workflow_events.py
Labels: small

#6658 Fix reinstall not detecting changed permissions by itself
  changes.d/6658.fix.md
  cylc/flow/install.py
  cylc/flow/remote.py
  cylc/flow/scripts/reinstall.py
  tests/integration/test_reinstall.py
  tests/unit/scripts/test_reinstall.py
Labels: bug, small

#6712 Fix flake8 lint
  tests/integration/scripts/test_set.py
  tests/integration/test_task_pool.py
  tests/unit/test_taskdef.py
Labels: small

#6715 Prepare 8.4.2
  .github/workflows/2_auto_publish_release.yml
  cylc/flow/__init__.py
Labels: release

#6710 reinstall: log reinstallation in the reinstall log
  changes.d/6710.fix.md
  cylc/flow/install.py
  tests/functional/cylc-reinstall/01-file-transfer.t
Labels: small, could be better

#6722 Tui memory leak
  changes.d/6722.fix.md
  cylc/flow/tui/app.py
  setup.cfg
Labels: bug, efficiency

#6721 Update datastore xtriggers on restart.
  changes.d/6721.fix.md
  cylc/flow/xtrigger_mgr.py
  tests/integration/test_xtrigger_mgr.py
Labels: bug

#6731 Add SQLite detailed error codes to error messages
  changes.d/6730.feat.md
  cylc/flow/rundb.py
  tests/unit/test_rundb.py
Labels: could be better

#6733 psutil: allow accessing psutil object methods
  changes.d/6733.fix.md
  cylc/flow/scripts/psutil.py
  cylc/flow/workflow_files.py
  tests/integration/test_workflow_files.py
  tests/unit/test_psutil.py
Labels: bug
