Repository cylc/cylc-flow, pull requests merged in 2025-08, with the labels that each got.

#6883 Ensure that test tests/functional/platforms/02-host-to-platform-upgra…
  tests/functional/platforms/02-host-to-platform-upgrade.t
  tests/functional/platforms/02-host-to-platform-upgrade/bad/flow.cylc
Labels: small, testing

#6896 remove obsolete config item
  cylc/flow/cfgspec/globalcfg.py
Labels: small, config change

#6844 trigger: support ^/$ syntax for referencing the initial/final cycle points
  changes.d/6844.feat.md
  cylc/flow/id_match.py
  cylc/flow/task_pool.py
  tests/functional/cylc-trigger/00-compat/flow.cylc
  tests/integration/test_task_pool.py
  tests/unit/test_id_match.py
Labels: small

#6918 more developer docs
  tests/README.md
  tests/functional/README.md
Labels: doc

#6910 Group trigger: re-use already-completed outputs of active group start tasks.
  changes.d/6910.fix.md
  cylc/flow/commands.py
  cylc/flow/scripts/trigger.py
  tests/integration/test_force_trigger.py
Labels: bug

#6926 Fix data store missing info for submit-failed jobs
  changes.d/6926.fix.md
  cylc/flow/data_store_mgr.py
  cylc/flow/task_events_mgr.py
  cylc/flow/task_job_mgr.py
  tests/integration/network/test_graphql.py
  tests/integration/test_data_store_mgr.py
  tests/integration/test_task_events_mgr.py
  tests/integration/tui/test_logs.py
Labels: bug, small

#6848 Allow platform setting to have prefix/suffix around subshell
  changes.d/6848.fix.md
  cylc/flow/cfgspec/workflow.py
  cylc/flow/platforms.py
  cylc/flow/task_remote_mgr.py
  tests/functional/job-submission/19-platform_select.t
  tests/functional/job-submission/19-platform_select/flow.cylc
  tests/functional/job-submission/19-platform_select/reference.log
  tests/unit/test_platforms_get_platform.py
Labels: small, could be better

#6903 restart timeout: fire event for stop after cycle point scenarios
  changes.d/6903.fix.md
  cylc/flow/cfgspec/globalcfg.py
  cylc/flow/scheduler.py
  tests/functional/restart/08-stop-after-cycle-point/flow.cylc
  tests/integration/test_workflow_events.py
Labels: bug, small

#6945 Fix cat-log test timing out
  cylc/flow/remote.py
  tests/functional/cylc-cat-log/12-delete-kill.t
Labels: small
