Repository cylc/cylc-flow, pull requests merged in 2025-02, with the labels that each got.

#6549 Remove vim.lang from syntax
  changes.d/6549.fix.md
  cylc/flow/etc/syntax/cylc.vim
  cylc/flow/resources.py
  cylc/flow/scripts/get_resources.py
  tests/unit/test_resources.py
Labels: small

#6586 pbs: update connection failed error message
  changes.d/6586.fix.md
  cylc/flow/job_runner_handlers/pbs.py
Labels: bug

#6592 Remove Empy reference file
  etc/syntax/reference-files/flow_empy.cylc
Labels: small

#6535 Kill tasks during job prep
  changes.d/6535.fix.md
  cylc/flow/network/server.py
  cylc/flow/scheduler.py
  cylc/flow/subprocctx.py
  cylc/flow/task_job_mgr.py
  cylc/flow/task_proxy.py
  cylc/flow/task_remote_mgr.py
  tests/functional/cylc-kill/03-simulation/flow.cylc
  tests/functional/cylc-kill/04-handlers.t
  tests/functional/cylc-kill/04-handlers/flow.cylc
  tests/functional/cylc-kill/04-handlers/reference.log
  tests/functional/cylc-kill/05-retries.t
  tests/functional/cylc-kill/05-retries/flow.cylc
  tests/functional/cylc-kill/05-retries/reference.log
  tests/functional/lib/bash/test_header
  tests/integration/conftest.py
  tests/integration/run_modes/test_mode_overrides.py
  tests/integration/run_modes/test_nonlive.py
  tests/integration/run_modes/test_skip.py
  tests/integration/test_kill.py
  tests/integration/test_task_events_mgr.py
  tests/integration/test_task_job_mgr.py
  tests/unit/test_scheduler.py
  tests/unit/test_task_remote_mgr.py
Labels: bug?

#6480 cat-log: list out/err files when available via tailer
  changes.d/6480.fix.md
  cylc/flow/scripts/cat_log.py
  tests/functional/cylc-cat-log/13-remote-out-err-tailer.t
  tests/functional/cylc-cat-log/13-remote-out-err-tailer/flow.cylc
Labels: could be better

#6606 Clarify task ID glob help
  cylc/flow/option_parsers.py
  cylc/flow/scripts/cylc.py
Labels: small

#6518 allow workflow config to unset global events config
  changes.d/6518.fix.md
  cylc/flow/parsec/config.py
  cylc/flow/workflow_events.py
  tests/unit/test_workflow_events.py
Labels: bug?, small

#6603 work around NFS caching issues
  changes.d/6506.fix.md
  cylc/flow/network/scan.py
  cylc/flow/workflow_files.py
Labels: bug

#6616 Wrapper script: fix `PATH` override preventing selection of Cylc version in GUI under Cylc Hub
  changes.d/6616.fix.md
  cylc/flow/etc/cylc
Labels: bug, small

#6604 examples: document expiry workflow design patterns
  cylc/flow/etc/examples/expiry/.validate
  cylc/flow/etc/examples/expiry/index.rst
  cylc/flow/etc/examples/expiry/one/flow.cylc
  cylc/flow/etc/examples/expiry/three/flow.cylc
  cylc/flow/etc/examples/expiry/two/flow.cylc
Labels: doc

#6624 Fix test
  pytest.ini
  tests/unit/test_workflow_events.py
Labels: small

#6578 Improve server-client communication error handling
  changes.d/6578.fix.md
  cylc/flow/exceptions.py
  cylc/flow/network/__init__.py
  cylc/flow/network/client.py
  cylc/flow/network/multi.py
  cylc/flow/network/replier.py
  cylc/flow/network/resolvers.py
  cylc/flow/network/scan.py
  cylc/flow/network/server.py
  cylc/flow/run_modes/dummy.py
  cylc/flow/run_modes/simulation.py
  cylc/flow/run_modes/skip.py
  cylc/flow/task_outputs.py
  tests/integration/conftest.py
  tests/integration/graphql/test_root.py
  tests/integration/network/__init__.py
  tests/integration/network/key_setup.py
  tests/integration/network/test_client.py
  tests/integration/network/test_graphql.py
  tests/integration/network/test_publisher.py
  tests/integration/network/test_replier.py
  tests/integration/network/test_resolvers.py
  tests/integration/network/test_scan.py
  tests/integration/network/test_server.py
  tests/integration/network/test_zmq.py
  tests/integration/test_install.py
Labels: bug

#6636 Remove vestiges of authorisation layer removed in #3845
  cylc/flow/network/__init__.py
  cylc/flow/network/authorisation.py
  cylc/flow/network/server.py
  tests/integration/network/test_replier.py
  tests/integration/network/test_server.py
Labels: small

#6631 tests: remove string templating in SQL statements
  tests/integration/test_workflow_db_mgr.py
  tests/unit/test_db_compat.py
  tests/unit/test_rundb.py
  tests/unit/test_templatevars.py
Labels: small

#6637 doc: improve NamespaceIDGlob description
  cylc/flow/network/schema.py
Labels: small, doc
