Repository cylc/cylc-flow, pull requests merged in 2025-06, with the labels that each got.

#6776 tests/f: fix restart/41
  tests/functional/restart/41-auto-restart-local-jobs.t
Labels: small

#6769 cylc: fix blindspot and fill some CLI coverage holes
  cylc/flow/scripts/cylc.py
  tests/functional/cli/01-help.t
  tests/unit/scripts/test_cylc.py
Labels: small, could be better

#6787 increase restart timeout to PT5M
  cylc/flow/cfgspec/globalcfg.py
Labels: small

#6745 Run hosts random-selection bug
  changes.d/6745.fix.md
  cylc/flow/exceptions.py
  cylc/flow/host_select.py
  cylc/flow/hostuserutil.py
  cylc/flow/main_loop/auto_restart.py
  cylc/flow/remote.py
  cylc/flow/scheduler.py
  cylc/flow/scheduler_cli.py
  tests/flakyfunctional/restart/39-auto-restart-no-suitable-host.t
  tests/functional/cylc-play/11-remote-reinvoke-uncontactable.t
  tests/unit/main_loop/test_auto_restart.py
  tests/unit/test_exceptions.py
  tests/unit/test_host_select.py
  tests/unit/test_host_select_remote.py
  tests/unit/test_scheduler.py
  tests/unit/test_scheduler_cli.py
Labels: bug

#6795 conda: bump urwid dependency
  conda-environment.yml
Labels: small, dependencies

#6783 scheduler: remove obsolete info_get_graph_raw interface
  cylc/flow/scheduler.py
Labels: small

#6798 fix infinite submission retry bug
  changes.d/6798.fix.md
  cylc/flow/task_job_mgr.py
Labels: bug, small

#6820 Improve error message when trying global reload on workflow running in <8.5.0
  cylc/flow/scripts/reload.py
Labels: small, could be better
